### ISSUE TITLE
alipay 插件如何使用？

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#101]
alipay:
    use: true
    appid: 2015012104922471
    notifyUrl: ''
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

求解这些参数的意义

**Comment by pexcn** [comment]
需要在 https://open.alipay.com/platform/home.htm 申请 api

**Comment by cokebar** [comment]
@pexcn 这个需要商家账号的吧

**Comment by pexcn** [comment]
不清楚…

**Comment by gyteng** [comment]
开通请参考这里：https://www.v2ex.com/t/326701
