### ISSUE TITLE
shadowsocks-manager安装问题

### ISSUE THREAD

**Issue by 1581052236** [shadowsocks/shadowsocks-manager#102]
**1，**
我按照文档https://github.com/shadowsocks/shadowsocks-manager/wiki/WebGUI     安装了以下软件：

- shadowsocks-libev

- Node.js 6.9

- shadowsocks-manager（执行npm i -g shadowsocks-manager安装）

**2，**
在/root目录下没有发现.ssmgr目录，于是新建了一个.ssmgr目录，然后复制/usr/lib/node_modules/shadowsocks-manager/config目录下的所有文件到~/.ssmgr/目录下

**3，**
在/root/.ssmgr目录下新建配置文件ss.yml，内容：
type: s
empty: false
**shadowsocks:
  address: 127.0.0.1:4000**
  _###### 这里的地址和端口需要跟上一步的 --manager-address 参数保持一致_
**manager:
  address: 0.0.0.0:4001**
  password: '123456'
db: 'ss.sqlite'

其中**shadowsocks:
  address: 127.0.0.1:4000**   这个ip（127.0.0.1）保持默认，不用更改么？

其中**manager:
  address: 0.0.0.0:4001**  这个ip填写自己服务器的ip，还是其他的？

**4，**
/root/.ssmgr/webgui.yml文件内容：
type: m
empty: false

manager:
  address: 1.1.1.1:4001
  password: '123456'
  _###### 这部分的端口和密码需要跟上一步 manager 参数里的保持一致_
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.03
        flow: 500000000
      day:
        price: 0.5
        flow: 7000000000
      week:
        price: 3
        flow: 50000000000
      month:
        price: 10
        flow: 200000000000
  email:
    use: true
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'
    _###### 这部分的邮箱和密码是用于发送注册验证邮件，重置密码邮件使用的_
  webgui:
    use: true
    **host: '0.0.0.0'**
    port: '80'
    site: 'http://yourwebsite.com'
  alipay:
    use: true
    appid: 2015012108272442
    notifyUrl: ''
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'

其中**host: '0.0.0.0'**   这个是保持默认，还是填写服务器ip？

感谢你的帮助

**Comment by gyteng** [comment]
都跟文档说的一致即可

**Comment by 1581052236** [comment]
@gyteng 好的，谢谢你
