### ISSUE TITLE
安装疑问

### ISSUE THREAD

**Issue by pbwind** [shadowsocks/shadowsocks-manager#104]
如https://github.com/shadowsocks/shadowsocks-manager/wiki/WebGUI  所述。
安装 shadowsocks-libev 、node js 6 、安装ssmgr（使用npm i -g shadowsocks-manage）
启动shadowsocks-libev 后，键入 ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000。 
系统提示 2017-03-01 07:25:42 INFO: running from root user。
只有了重连。
执行： ssmgr -c ss.yml
因为知道下部的问题。
直接新建/root/.ssmgr/，并从/usr/lib/node_modules/shadowsocks-manager/lib/复制文件到/root/.ssmgr/ 。 创建 ss.yml 。
然后再依照教程  输入ssmgr -c ss.yml

root@default:~# ssmgr -c ss.yml
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-01 07:44:01.025] [INFO] system - System start.
[2017-03-01 07:44:01.213] [INFO] system - Config file path:  /root/.ssmgr/ss.yml
不动了。。不动了 
原谅我的小白。 没有办法输入命令正常执行。
再次重连。

这次我聪明了。
执行 screen ssmgr -c webgui.yml 可以后台操作。
可惜还是跳红字。
root@default:~# screen ssmgr -c webgui.yml

/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-01 07:54:28.828] [INFO] system - System start.
[2017-03-01 07:54:29.020] [INFO] system - Config file path:  /root/.ssmgr/webgui.yml
[2017-03-01 07:54:29.881] [INFO] webgui - server start at ***.***.***.***:80
[2017-03-01 07:54:29.938] [ERROR] system - { Error: connect ECONNREFUSED ***.***.***.***:6001
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '***.***.***.***',
  port: 6001 }
[2017-03-01 07:54:29.946] [ERROR] system - Unhandled Rejection at: Promise Promise { <rejected> 'failure' } reason: failur

但是打开 我的个人主页。 
但是依照我这两天重装的经验，服务用不到1个小时，就断线，SS断，网页打开正常。

小白的推断一下，可能是服务器杀进程。
老大，能把各命令详细一点吗？
可能对你来说，就是在指令前加一个命令，或者一个快捷键就解决了。
对于我等小白来来说，可能是无数次的摸索 。

为了造福更多大白，小白，希望能写的简单，小白一点。

谢谢

**Comment by pbwind** [comment]
google   Object.exports._errnoException (util.js:1022:11)
有些人回答是因为没有执行 node server.js

于是接着装 
git clone https://github.com/shadowsocks/shadowsocks-manager.git
cd shadowsocks-manager
npm i
node server.js.

为了保险起见，再次运行以下：
 screen ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6000
ctrl+a+c
screen ssmgr -c ss.yml
ctrl+a+c
screen ssmgr -c webgui.yml

没想到错误依旧。而且 个人主页打开并不能注册。

自此安装错误。

接着重来

**Comment by gyteng** [comment]
请把你的配置文件贴出来（注意把密码的部分去掉）。
另外你要先了解一下Linux下如何让一个程序后台运行，参考关键词`screen nohup pm2`等

**Comment by pbwind** [comment]
SS.yml

type: s
empty: false
shadowsocks:
  address: 127.0.0.1:6000
  # 这里的地址和端口需要跟上一步的 --manager-address 参数保持一致
manager:
  address: ***.***.***.***:60001
  password: '**************'
db: 'ss.sqlite'

webgui.yml

type: m
empty: false

manager:
  address: ***.***.***.***:6001
  password: '**************'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.03
        flow: 500000000
      day:
        price: 0.5
        flow: 7000000000
      week:
        price: 3
        flow: 50000000000
      month:
        price: 10
        flow: 200000000000
  email:
    use: true
    username: '******@sina.com'
    password: '*****'
    host: 'smtp.sina.com'
  webgui:
    use: true
    host: '***.***.***.***'
    port: '80'
    site: 'http://www.****.***'
  alipay:
    use: true
    appid: 2017022805938041
    notifyUrl: ''
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'

**Comment by pbwind** [comment]
我在G+上面看到你有指点的。我有通过screen 后台运行后，用ctal+a+c   切换出来。
我有一个疑问。安装页面有两种安装方式：
From source:、From npm: 。 这两种都要同时安装把。

**Comment by gyteng** [comment]
不需要同时安装，选其中一种即可

**Comment by pbwind** [comment]
如果选一种安装。 会提示   Object.exports._errnoException (util.js:1022:11)

**Comment by gyteng** [comment]
请贴出完整的错误提示，注意代码用反引号包裹已保持缩进

2017-03-01 22:24 GMT+08:00 pbwind <notifications@github.com>:

**Comment by pbwind** [comment]
“root@default:~# screen ssmgr -c webgui.yml

/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-01 07:54:28.828] [INFO] system - System start.
[2017-03-01 07:54:29.020] [INFO] system - Config file path: /root/.ssmgr/webgui.yml
[2017-03-01 07:54:29.881] [INFO] webgui - server start at ***.***.***.***:80
[2017-03-01 07:54:29.938] [ERROR] system - { Error: connect ECONNREFUSED ***.***.***.***:6001
at Object.exports._errnoException (util.js:1022:11)
at exports._exceptionWithHostPort (util.js:1045:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect',
address: '***.***.***.***',
port: 6001 }
[2017-03-01 07:54:29.946] [ERROR] system - Unhandled Rejection at: Promise Promise { 'failure' } reason: failur”

**Comment by gyteng** [comment]
你把配置文件的ip地址隐去了我也不知道到底填对没有

**Comment by pbwind** [comment]
配置文件的IP 就是我服务器的IP地址。确认一致。
如果可以，我可以给你远程。谢谢

**Comment by gyteng** [comment]
出错的原因是连接到 `xxx.xxx.xxx.xxx:6001` 失败，请检查你的6001端口有没有打开

**Comment by pbwind** [comment]
root@default:~# netstat -nupl 6001
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 **.**.**.**:443         0.0.0.0:*                           254/ss-server   
udp        0      0 0.0.0.0:41150           0.0.0.0:*                           254/ss-server   
udp        0      0 0.0.0.0:39114           0.0.0.0:*                           254/ss-server   
udp        0      0 0.0.0.0:41429           0.0.0.0:*                           254/ss-server   
udp        0      0 0.0.0.0:59102           0.0.0.0:*                           254/ss-server   
udp        0      0 0.0.0.0:58620           0.0.0.0:*                           254/ss-server

**Comment by jiangkk** [comment]
这个问题解决了吗？ 同问

**Comment by jianjustin** [comment]
我也出现这个问题，但是解决方案呢？同问
