### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by CC-CL** [shadowsocks/shadowsocks-manager#105]
按照ｗｉｋｉ配置完成。并没有报错。但是自己的网页始终显示没法正常工作。不能使用代理。最后的https协议没有去申请。所以最后的代码没有动。希望大大能注释详细一点。
——————————————————————————————————————
ｕｂａｎｔｕ　１６．１０　
安装准备：　自己注册域名，添加ｄｎｓ解析。　申请支付宝ａｐｐｉｄ。ｗｉｋｉ最后链接有。
　１＞从库里安装了ｓｈａｄｏｗｓｏｃｋｓ-libev        |没有配置文件
   ２>从官网　安装了nodejs最新版（　官网会提示更新另外一个组件｜忘了叫什么了，从ｎｐｍ安装是需要的。最新的ｖｐｓ可能会提示安装ｃｕｉｌ。也需要安装。）
   3> 用npm 直接安装了ｓｈａｄｏｗｓｏｃｋｓ-manager 。
   4> 配置文件　修改：　ss.yml   部分代码　password: '******'   其余保持不变。
　　　　　　　修改　：　webgui.yml 配置文件　password:'****'　　与前面密码一致。｜　不要怀疑
　　　　　　　　 email　部分　ｕｓｅｒｎａｍｅ　自己的邮箱
　　　　　　　　ｐａｓｓｗｏｒｄ　邮箱密码
　　　　　　　　ｈｏｓｔ　我用的是Ｇｍａｉｌ　｜　　ｈｍｔｐ.gmail.com
                        sit 　自己的域名地址。修改ａｐｐｉｄ。完事　。　－－－－－－没缩进就是烦
　　５> 运行　ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000
　　再运行　ｓｓｍｇｒ　-c ss.yml 和　ｓｓｍｇｒ　-c webgui,yml   ||| 这里有一个疑问好像nohup 能同时对两个ssmgr 使用。　　

最后还是没搞成　气　啊！！　大大哪里漏了还是错了啊！！

**Comment by gyteng** [comment]
请贴出详细的错误信息，并注意 markdown 的代码缩进
