### ISSUE TITLE
ReferenceError: orderId is not defined

### ISSUE THREAD

**Issue by napasa** [shadowsocks/shadowsocks-manager#106]
用户用支付宝完成支付时webgui.yml出现以下出错提示，不过似乎不影响使用。
`[2017-03-04 10:45:02.691] [ERROR] system - Unhandled Rejection at: Promise Promise {
  <rejected> ReferenceError: orderId is not defined
    at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:98:34 } reason: ReferenceError: orderId is not defined
    at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:98:34`

**Comment by gyteng** [comment]
你能描述一下具体什么情况能重现这个问题吗？

这个错误确实不会影响整体功能，本来用户支付完，那个显示二维码的弹窗会变成“支付成功”，如果出现你这个报错就无法及时提示了。

2017-03-04 23:55 GMT+08:00 No.6 <notifications@github.com>:

**Comment by napasa** [comment]
是的。确实是无法及时提示的。不过后来还是有提示的。问题可以重现，由于我对node不熟悉，我尽可能的具体描述下：

1. 支付金额都是一小时类型

1. 我没有开启shadowsocks server。

1. 这个问题我支付两次都重复出现。

1. 当时我是用手机浏览webgui

1. 还有什么需要提的吗？我会点node，改天我也调试看看~
