### ISSUE TITLE
wiki中关于alipay支付接口使用的补充说明

### ISSUE THREAD

**Issue by napasa** [shadowsocks/shadowsocks-manager#107]
在完成[个人免费开通支付宝商家收款码](https://www.v2ex.com/t/326701)之后，[进入商家中心](b.alipay.com)进行签约管理。然后在蚂蚁金服开放平台中的**PID和公钥管理**的[开放平台密钥](https://openhome.alipay.com/platform/keyManage.htm)对你生成的应用进行密钥设置。其中的主要步骤如下：

1. 设置RSA(SHA1)密钥，按官网提示完成密钥上传

1. 将步骤1中生成的 **rsa_public_key.pem**文件中的public key填到**alipayPublicKey**项，将**rsa_private_key.pem**中的private key填到**merchantPrivateKey**项即可完成支付接口的对接。

**Comment by gyteng** [comment]
thx

**Comment by jumkey** [comment]
alipayPublicKey不是 rsa_public_key.pem文件中的内容，应该是商户后台的“查看支付宝公钥”内容 @gyteng

**Comment by gyteng** [comment]
@jumkey 已修复，多谢。
