### ISSUE TITLE
Support URL Scheme Client Wake-up

### ISSUE THREAD

**Issue by coderfox** [shadowsocks/shadowsocks-manager#109]
Various clients can all be woken up by links like <ss://YWVzLTI1Ni1jZmI6dTFyUldUc3NOdjBw@198.199.101.152:8388>. It can make configuration more convenient.

**Comment by gyteng** [comment]
What do you mean Various clients? I can not find it in the docs of [shadowsocks.org](http://shadowsocks.org/en/config/quick-guide.html)

**Comment by coderfox** [comment]
The docs are at <http://shadowsocks.org/en/config/quick-guide.html>. You may create a link to the url, for example: `<a href="ss://YmYtY2ZiOnRlc3RAMTkyLjE2OC4xMDAuMTo4ODg4Cg"></a>`.

**Comment by gyteng** [comment]
Thanks,
But I have another question, the docs shows:

```
ss://YmYtY2ZiOnRlc3RAMTkyLjE2OC4xMDAuMTo4ODg4Cg#example-server
```

what does the `example-server` mean?

2017-03-05 10:17 GMT+08:00 小傅Fox <notifications@github.com>:

**Comment by coderfox** [comment]
It is just a note used for recognizing, and is ignored by the client.
