### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by CC-CL** [shadowsocks/shadowsocks-manager#110]
![_20170306_102815](https://cloud.githubusercontent.com/assets/24436808/23594852/ed15e036-01e2-11e7-911f-edbf6f9fbedc.JPG)
![1488733322848 01](https://cloud.githubusercontent.com/assets/24436808/23594863/0417121e-01e3-11e7-9b4b-e71269fadabd.jpg)
![1488733249828 01](https://cloud.githubusercontent.com/assets/24436808/23594868/0ff24d38-01e3-11e7-9004-11bdc1fdf861.jpg)
![1488733165181 01](https://cloud.githubusercontent.com/assets/24436808/23594871/1a710812-01e3-11e7-919b-9c5dce868da0.jpg)
如上配置后，系统无报错。但自己的网站没法打开。用ping 测试域名，可以解析到自己的服务器地址。
建议开发ppid守护功能。

**Comment by gyteng** [comment]
请先在运行的时候加上个`--debug`参数显示所有的日志，
然后再用`netstat -na | grep 8080`看看你的端口有没有打开

**Comment by CC-CL** [comment]
![1488768403026](https://cloud.githubusercontent.com/assets/24436808/23595115/f71b9b32-01e4-11e7-8653-cd07885126c4.jpg)

**Comment by gyteng** [comment]
端口已经打开了，请检查你的防火墙或者nginx之类的
