### ISSUE TITLE
如何调整新注册账号试用策略？

### ISSUE THREAD

**Issue by eyyoung** [shadowsocks/shadowsocks-manager#111]
是否有相关的配置？

**Comment by gyteng** [comment]
目前还没有，正在开发这个功能，包括是否开放注册、注册完试用的时长等等，如果有好的方案请在这里提出。

2017-03-07 10:48 GMT+08:00 MrYoung91 <notifications@github.com>:

**Comment by gyteng** [comment]
最新版本已经加上此功能
