### ISSUE TITLE
不要强制使用 os.homedir 作为配置文件路径的开头

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/shadowsocks-manager#113]
比如我想将配置放在当前目录或 /etc，就不行了。但这个修改会损坏现有配置，可以考虑新加配置项或智能判断。

**Comment by gyteng** [comment]
最近几个版本已经修正了这个问题，你可以使用相对路径或绝对路径。只有只填文件名的时候才会去.ssmgr目录里找

Tian Yunhao <notifications@github.com>于2017年3月10日 周五21:49写道：
