### ISSUE TITLE
ss-server每分钟都在重启，这正常吗？

### ISSUE THREAD

**Issue by aqaqaqq** [shadowsocks/shadowsocks-manager#114]
> $tail /var/logmessages -n 100
Mar 11 02:57:21 host_name_here ss-server[651]: tcp server listening at 0.0.0.0:55312
Mar 11 02:57:21 host_name_here ss-server[651]: udp port reuse enabled
Mar 11 02:57:21 host_name_here ss-server[651]: udp server listening at 0.0.0.0:55312
Mar 11 02:57:21 host_name_here ss-server[651]: running from root user
Mar 11 02:57:21 host_name_here ss-server[654]: UDP relay enabled
Mar 11 02:57:21 host_name_here ss-server[654]: initializing ciphers... aes-256-cfb
Mar 11 02:57:21 host_name_here ss-server[654]: using nameserver: 8.8.8.8
Mar 11 02:57:21 host_name_here ss-server[654]: tcp port reuse enabled
Mar 11 02:57:21 host_name_here ss-server[654]: tcp server listening at 0.0.0.0:55401
Mar 11 02:57:21 host_name_here ss-server[654]: udp port reuse enabled
Mar 11 02:57:21 host_name_here ss-server[654]: udp server listening at 0.0.0.0:55401
Mar 11 02:57:21 host_name_here ss-server[654]: running from root user
Mar 11 02:58:21 host_name_here ss-server[661]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[661]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[661]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[661]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[661]: tcp server listening at 0.0.0.0:39888
Mar 11 02:58:21 host_name_here ss-server[661]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[661]: udp server listening at 0.0.0.0:39888
Mar 11 02:58:21 host_name_here ss-server[661]: running from root user
Mar 11 02:58:21 host_name_here ss-server[664]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[664]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[664]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[664]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[664]: tcp server listening at 0.0.0.0:55012
Mar 11 02:58:21 host_name_here ss-server[664]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[664]: udp server listening at 0.0.0.0:55012
Mar 11 02:58:21 host_name_here ss-server[664]: running from root user
Mar 11 02:58:21 host_name_here ss-server[667]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[667]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[667]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[667]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[667]: tcp server listening at 0.0.0.0:55023
Mar 11 02:58:21 host_name_here ss-server[667]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[667]: udp server listening at 0.0.0.0:55023
Mar 11 02:58:21 host_name_here ss-server[667]: running from root user
Mar 11 02:58:21 host_name_here ss-server[670]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[670]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[670]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[670]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[670]: tcp server listening at 0.0.0.0:55093
Mar 11 02:58:21 host_name_here ss-server[670]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[670]: udp server listening at 0.0.0.0:55093
Mar 11 02:58:21 host_name_here ss-server[670]: running from root user
Mar 11 02:58:21 host_name_here ss-server[673]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[673]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[673]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[673]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[673]: tcp server listening at 0.0.0.0:55139
Mar 11 02:58:21 host_name_here ss-server[673]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[673]: udp server listening at 0.0.0.0:55139
Mar 11 02:58:21 host_name_here ss-server[673]: running from root user
Mar 11 02:58:21 host_name_here ss-server[676]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[676]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[676]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[676]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[676]: tcp server listening at 0.0.0.0:55156
Mar 11 02:58:21 host_name_here ss-server[676]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[676]: udp server listening at 0.0.0.0:55156
Mar 11 02:58:21 host_name_here ss-server[676]: running from root user
Mar 11 02:58:21 host_name_here ss-server[679]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[679]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[679]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[679]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[679]: tcp server listening at 0.0.0.0:55195
Mar 11 02:58:21 host_name_here ss-server[679]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[679]: udp server listening at 0.0.0.0:55195
Mar 11 02:58:21 host_name_here ss-server[679]: running from root user
Mar 11 02:58:21 host_name_here ss-server[682]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[682]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[682]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[682]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[682]: tcp server listening at 0.0.0.0:55239
Mar 11 02:58:21 host_name_here ss-server[682]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[682]: udp server listening at 0.0.0.0:55239
Mar 11 02:58:21 host_name_here ss-server[682]: running from root user
Mar 11 02:58:21 host_name_here ss-server[685]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[685]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[685]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[685]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[685]: tcp server listening at 0.0.0.0:55253
Mar 11 02:58:21 host_name_here ss-server[685]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[685]: udp server listening at 0.0.0.0:55253
Mar 11 02:58:21 host_name_here ss-server[685]: running from root user
Mar 11 02:58:21 host_name_here ss-server[688]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[688]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[688]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[688]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[688]: tcp server listening at 0.0.0.0:55312
Mar 11 02:58:21 host_name_here ss-server[688]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[688]: udp server listening at 0.0.0.0:55312
Mar 11 02:58:21 host_name_here ss-server[688]: running from root user
Mar 11 02:58:21 host_name_here ss-server[691]: UDP relay enabled
Mar 11 02:58:21 host_name_here ss-server[691]: initializing ciphers... aes-256-cfb
Mar 11 02:58:21 host_name_here ss-server[691]: using nameserver: 8.8.8.8
Mar 11 02:58:21 host_name_here ss-server[691]: tcp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[691]: tcp server listening at 0.0.0.0:55401
Mar 11 02:58:21 host_name_here ss-server[691]: udp port reuse enabled
Mar 11 02:58:21 host_name_here ss-server[691]: udp server listening at 0.0.0.0:55401
Mar 11 02:58:21 host_name_here ss-server[691]: running from root user

> $ss-server -h
shadowsocks-libev 2.6.3 with mbed TLS 2.4.0

> $ssmgr -V
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-11 03:01:42.750] [INFO] system - System start.
shadowsocks-manager 0.5.17

**Comment by gyteng** [comment]
请提供你的ssmgr版本号

**Comment by aqaqaqq** [comment]
0.5.17

**Comment by aqaqaqq** [comment]
好的，也不影响使用，定时删删日志就好
谢谢！

**Comment by gyteng** [comment]
@aqaqaqq 0.5.42 解决了这个问题，你可以试下

**Comment by aqaqaqq** [comment]
确实解决了，谢谢
