### ISSUE TITLE
工作目录不在当前文件夹时（例如 systemd 启动），渲染失败

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/shadowsocks-manager#116]
将如下文件放到 `/lib/systemd/system/ssmgr.service` 中（假设 shadowsocks-manager 在 /var/ssmgrv2 中）
```ini
[Unit]
Description=Shadowsocks Node Service Master 2
After=network.target

[Service]
Type=simple
User=root
LimitNOFILE=32768
# 加上下面的行，工作正常
# WorkingDirectory=/var/ssmgrv2
ExecStart=/usr/bin/node /var/ssmgrv2/server.js -t m -c /etc/ssmgr/config.yml

[Install]
WantedBy=multi-user.target
```
会导致
` Error: Failed to lookup view "index" in views directory "/plugins/webgui/views" `

**Comment by gyteng** [comment]
我估计把 ExecStart 部分的 `var/ssmgrv2/server.js` 改为 `/var/ssmgrv2/bin/ssmgr`，不加 WorkingDirectory 也可以的
