### ISSUE TITLE
流量显示有问题 且不会停止使用？

### ISSUE THREAD

**Issue by relei1988** [shadowsocks/shadowsocks-manager#117]
显示已经用了近800MB，刚注册的默认350MB，然后上头统计又是仅15KB，求解

**Comment by relei1988** [comment]
![1](https://cloud.githubusercontent.com/assets/13428255/23823869/76be0508-06a6-11e7-8651-98db032bcd84.png)

**Comment by lucas-chou** [comment]
能不能教我怎么安装~@relei1988

**Comment by relei1988** [comment]
@lucas-chou 这个readme写的蛮清楚的我就跟着这个装的，只有一个错误就是这里需要一个数据库mongod 装好了照步骤走就对拉

**Comment by gyteng** [comment]
请提供一下你的shadowsocks版本（python or libev），还有ssmgr版本

**Comment by relei1988** [comment]
shadowsocks是libev，ssmgr是0.5.17

**Comment by gyteng** [comment]
明白了，你那个800mb是不是之前有另外一个用户使用过这个端口，然后也统计进去了？

2017-03-11 22:36 GMT+08:00 relei1988 <notifications@github.com>:

**Comment by relei1988** [comment]
@gyteng 并没有，我检查过，每个端口都对应一个邮箱号，这个端口是个新注册用户的，管理员只有我一个也没别人会知道这个号的，我自己肯定没用过，进后台看了眼看到的

**Comment by gyteng** [comment]
我知道了，那个15k的流量是指一个周期内的（按你目前的是一小时），而下面的800m是指一天的

**Comment by relei1988** [comment]
欸，但是确实没有自动停止掉呀，按照这个逻辑不是应该分配350MB，有效期和流量哪个先到就停吗？另外，这个人也是今天注册的，试用好像是8小时应该都在今天这一个周期内的……

**Comment by gyteng** [comment]
这个周期是这么计算的，如果按小时来算的话，每小时的流量超过350就会停止，过了一个小时重新从0开始统计。

在 2017年3月11日 下午10:43，relei1988 <notifications@github.com>写道：

**Comment by relei1988** [comment]
哦哦原来如此，这个设计精妙，谢谢解答

**Comment by lucas-chou** [comment]
@relei1988 谢谢，我安装好，但是有个问题，注册收不到验证码，QQ 163和gmail都不行，求助

**Comment by relei1988** [comment]
邮件服务器设置对不对，gmail有没有让你允许不太安全的登录？打开就好了

**Comment by lucas-chou** [comment]
@relei1988 关掉了两部验证，启用了不安全的，注册的时候一直在转圈

**Comment by relei1988** [comment]
那我也不知道了，具体情况描述下新开个issue吧

**Comment by gyteng** [comment]
@lucas-chou 请到你的 `~/.ssmgr/logs` 目录下查查发送邮件的时候有没有报错的日志
