### ISSUE TITLE
请问使用mysql作为数据库，导入的数据表在哪获得。

### ISSUE THREAD

**Issue by lovage** [shadowsocks/shadowsocks-manager#118]
如题

**Comment by gyteng** [comment]
导入？这个不需要导入的呀，没明白你的意思

2017-03-12 22:41 GMT+08:00 lovage <notifications@github.com>:

**Comment by lovage** [comment]
小白一枚，不太懂其中原理。
sspanel是需要导入sql到数据库，然后读取user表。。。
这个的工作原理是什么，用户信息存储在哪。

**Comment by gyteng** [comment]
你现在是否已经按文档的步骤做好了，并可以打开你搭建的网站了
lovage <notifications@github.com>于2017年3月12日 周日23:02写道：
