### ISSUE TITLE
修改账号时间，开始时间也会跟着到期时间一起变动。

### ISSUE THREAD

**Issue by KaiyangNi** [shadowsocks/shadowsocks-manager#123]
0.5.32

docker gyteng/ssmgr

修改账号时间，开始时间也会一起变动。

开始时间应该的固定的，到期时间才会变动，加减时间，只需改变到期时间。

如图 今天是14日，刚开始开通了一个星期，然后添加一个星期的时间后，开始时间变成了21日
![2017-03-14 15 44 59](https://cloud.githubusercontent.com/assets/11040801/23890689/cc5f38dc-08cd-11e7-9c74-9f25292219b4.png)

**Comment by gyteng** [comment]
是这样的，因为计费周期只能整数，当你从小时换成周时会变

KaiyangNi <notifications@github.com>于2017年3月14日 周二15:50写道：

**Comment by KaiyangNi** [comment]
懂了，意思是这个是计费的周期 ，不是使用时间的周期，明白了，谢谢！
