### ISSUE TITLE
用 MySQL 作数据库时注意

### ISSUE THREAD

**Issue by KaiyangNi** [shadowsocks/shadowsocks-manager#124]
把数据库从 SQLite 转为 MySQL 时，服务器统计数据的图表画不出来。

错误日志信息如下:

> Error: ER_WRONG_FIELD_WITH_GROUP: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ssmgr.user.username' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

网上找到原因 是 MySQL5.7.5 版本以后默认开启 only_full_group_by 模式 
user.username 带 group 导致出问题

简单解决办法是在MySQL配置文件里面去掉即可

**Comment by lixiaolusunshine** [comment]
得是先安装mysql数据库嘛 使用pip install cymysql数据库
