### ISSUE TITLE
支付接口设置以及配置文件疑问

### ISSUE THREAD

**Issue by guigeng** [shadowsocks/shadowsocks-manager#125]
### What version of shadowsocks-manager are you using?
0.5.33

### What operating system are you using?
CentOS7

配置文件中：
webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://yourwebsite.com'
    gcmSenderId: '456102641793'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
alipay:
    use: true
    appid: 2015012108272442
    notifyUrl: ''
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

gcmSenderId 、gcmAPIKey 这2个需要修改吗？是什么？
支付宝的接入是按照wiki上的那个帖子说明申请成功
那么appid是支付宝里面的应用的ID吗还是合作伙伴身份ID？
notifyUrl需要填写什么？
merchantPrivateKey是私钥
alipayPublicKey是支付宝公钥

支付时，提示“生成支付订单出错”
附log
{ message: '生成请求签名时错误',
  info: 
   Error: error:0906D064:PEM routines:PEM_read_bio:bad base64 decode
       at Error (native)
       at Sign.sign (crypto.js:283:26)
       at Object.getSign (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/signHelper.js:56:27)
       at ex (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:67:32)
       at Object.execute (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:49:16)
       at Promise (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:107:11)
       at alipay_f2f.createQRPay (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:57:13)
       at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:40:37)
       at next (native)
       at step (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:253)
       at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:423 }
[2017-03-15 16:42:29.795] [ERROR] express - [undefined] POST 403 64ms /api/user/order/qrcode

谢谢

**Comment by gyteng** [comment]
gcmSenderId 、gcmAPIKey 这两个是Chrome推送用的，跟支付无关

**Comment by gyteng** [comment]
appid是应用ID，merchantPrivateKey和alipayPublicKey用支付宝提供的工具生成rsa格式的密钥，alipayPublicKey是支付宝公钥

**Comment by gyteng** [comment]
notifyUrl是支付宝支付成功回调的地址，可以不填

**Comment by guigeng** [comment]
merchantPrivateKey: 'MII-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------4S1'
    alipayPublicKey: 'MIG-------------------------------------------------------------------------------------------------------------------------------------------------------QAB'

是填写这些吗？
很长的一段密钥。
仍然会报错。

支付宝上的密钥也填入相应的位置了。

不知道是什么问题

谢谢！

**Comment by gyteng** [comment]
alipayPublicKey 是在支付宝的页面上查看到的，不要搞错哦

**Comment by guigeng** [comment]
我描述一下我的流程，不知道对不对：
1.按照帖子里面开通当面付
2.下载签名工具，生成密钥：应用私钥&应用公钥
3.在支付宝开放平台https://openhome.alipay.com/platform/keyManage.htm
开放平台密钥：记录APPID
设置RSA2(SHA256)密钥(推荐):填入工具生成的公钥，记录生成的支付宝公钥
4.把第3步的APPID、支付宝公钥、工具生成的私钥分别填入webgui.yml的appid、alipayPublicKey、merchantPrivateKey
5.运行ssmgr -c webgui.yml 测试支付功能

以上，请斧正。谢谢！

**Comment by gyteng** [comment]
不是 RSA2 类型的

在 2017年3月17日 上午9:42，Guigeng Ding <notifications@github.com>写道：

**Comment by guigeng** [comment]
我再研究一下，谢谢！

**Comment by gyteng** [comment]
因为目前文档还不够完善，所以有什么疑问尽管在这里提问

**Comment by xiaobuu** [comment]
请问appid是要在开放平台中申请一个新应用才能获得吗？

**Comment by xiaobuu** [comment]
原来是要支付宝扫那帖子的码。。。 。。

**Comment by jiuqianyuan** [comment]
支付宝新的应用只支持RSA2，这个怎么破啊

**Comment by houstar** [comment]
我新设置的shadowsocks-manager也用不了支付宝，就是因为新应用只支持RSA2

**Comment by autodataming** [comment]
选择套餐后，点击下一步，出现支付失败。怎么查看log 文件？

**Comment by drshiki** [comment]
请问下你们，申请当面付接口是不是要提交应用审核，这样我是不是要提交应用地址给他们审核，那他们看到是ss的付款接入是不是会拒绝通过审核呢？如果是这样，你们是怎么申请的
