### ISSUE TITLE
抛出异常HTTP Error (429)

### ISSUE THREAD

**Issue by guigeng** [shadowsocks/shadowsocks-manager#127]
### What version of shadowsocks-manager are you using?
shadowsocks-manager 0.5.33

### What operating system are you using?
CentOS Linux release 7.3.1611 (Core) 

### What is your config in detail (with all sensitive info masked)?
type: s
empty: false
shadowsocks:
  address: 127.0.0.1:4000
manager:
  address: 0.0.0.0:4001
  password: '123456'
db: 'ss.sqlite'

debug:
# ssmgr -c ss.yml --debug
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-17 12:52:05.361] [INFO] system - System start.
[2017-03-17 12:52:05.702] [INFO] system - Config file path:  /root/.ssmgr/ss.yml
[2017-03-17 12:52:06.411] [INFO] system - server listen on 0.0.0.0:4001
[2017-03-17 12:52:06.413] [INFO] system - Receive flow from shadowsocks: (libev)
{}
raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting

补充：
国内主机npm i -g shadowsocks-manager，到sqlite的时候会出错，无法下载，使用npm.taobao.org镜像
cnpm i -g shadowsocks-manager安装成功

**Comment by gyteng** [comment]
这个是网络问题，如果遇到sqlite没安装成功，删除重装即可。

**Comment by guigeng** [comment]
使用mysql和sqlite一样的问题
都是rate limiting
昨天正常的机器也出现这个提示。

**Comment by 873314461** [comment]
楼主解决了没，我也遇到这个问题了。。。
