### ISSUE TITLE
请问作者，直接用npm安装，如何修改前台？

### ISSUE THREAD

**Issue by relei1988** [shadowsocks/shadowsocks-manager#131]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.5.37

### What operating system are you using?

centos 6
### What is your config in detail (with all sensitive info masked)?

npm安装完成后显示

```
/usr/bin/ssmgr -> /usr/lib/node_modules/shadowsocks-manager/bin/ssmgr
/usr/lib
```

在 /usr/lib/node_modules/shadowsocks-manager/bin目录下搜索了html结尾有2个目录，都修改了相应文件重启了ssmgr，但前台无变化

**Comment by gyteng** [comment]
请定义何为“修改前台”？

**Comment by relei1988** [comment]
就是，修改页面显示，html

**Comment by gyteng** [comment]
请用git clone的方式下载

**Comment by relei1988** [comment]
那个方式run Server.js时候报错…
