### ISSUE TITLE
modify raven key 版本改动之后所有版本的数据统计失效

### ISSUE THREAD

**Issue by KaiyangNi** [shadowsocks/shadowsocks-manager#132]
0.5.37

docker gyteng/ssmgr

modify raven key 版本改动之后，之前所有版本的数据统计失效

无法统计服务器流量数据，无法获取用户最后连接信息。
最开始我以为是新版本的问题，用快照回退到之前正常使用版本（0.5.35），然后又试了几个版本（0.5.36），删掉了原有镜像，重新拉取（0.5.37）试过之后，依然有问题。

可能是某个接口出问题了。看了一下最后有记录的连接时间，大概就是 modify raven key 版本改动之后。

**Comment by gyteng** [comment]
我没有尝试docker版本，我自己在用的npm版本是没有问题的，你能说说具体如何重现这个问题吗？

**Comment by KaiyangNi** [comment]
这个是在正常使用中突然出现的，所以我也不知道怎么复现，您那边没问题的话，等我再好好检查下一个配置方面或者我个人服务器的问题。

**Comment by gyteng** [comment]
docker镜像你也可以自己生成：

```
FROM ubuntu:16.04
MAINTAINER gyteng <igyteng@gmail.com>
RUN apt-get update && \
    apt-get install curl git sudo -y && \
    curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get install -y nodejs && \
    npm i -g shadowsocks-manager && \
    git clone https://github.com/shadowsocks/shadowsocks-libev.git ~/shadowsocks && \
    mkdir -p ~/build-area/ && \
    cp ~/shadowsocks/scripts/build_deb.sh ~/build-area/ && \
    cd ~/build-area && \
    ./build_deb.sh
ENTRYPOINT ["/usr/bin/ssmgr"]
```

**Comment by KaiyangNi** [comment]
谢谢！大致问题找到了，还是 MySQL 的问题，换成 SQLite 就正常了，具体原因还在排查。

**Comment by gyteng** [comment]
你是不是用5.7的mysql
KaiyangNi <notifications@github.com>于2017年3月18日 周六01:05写道：

**Comment by KaiyangNi** [comment]
是的

**Comment by gyteng** [comment]
only_full_group_by 的问题，之前你自己告诉我的

**Comment by KaiyangNi** [comment]
这次不是，only_full_group_by，我早就去掉了，only_full_group_by 的问题是画不出图表，这次是有图表，没有数据，神奇的是我把 MySQL 里面 sessions 清空就正常了，依然不知道为什么，可能数据有什么冲突。
