### ISSUE TITLE
Creation of this event was denied due to rate limiting

### ISSUE THREAD

**Issue by kmm996** [shadowsocks/shadowsocks-manager#133]
root@ubuntu:~# ssmgr -c webgui.yml
/usr/local/nodejs/node-v6.9.1-linux-x64/lib/node_modules/shadowsocks-manager/lib/
[2017-03-17 15:34:40.477] [INFO] system - System start.
raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting

**Comment by gyteng** [comment]
这个是我的一个错误收集工具调用频率达到上限了，不用管这个错误
