### ISSUE TITLE
邀请码注册和自定义续费模式

### ISSUE THREAD

**Issue by now163** [shadowsocks/shadowsocks-manager#134]
这两个功能都还蛮有用的。不知道以后是否会实现。

还有一个问题就是，用户修改或密码以后，需要手动刷新页面。才会正常现实新密码。

**Comment by gyteng** [comment]
暂时不考虑加功能，目前主要计划是完成公告发布功能以及浏览器消息推送

**Comment by gyteng** [comment]
另外，修改密码后会自动刷新的，可能是你在用一个比较旧的版本

**Comment by now163** [comment]
了解。我是用的npm安装的。
今天用源码试试。
