### ISSUE TITLE
发送邮件需要开放那几个端口？

### ISSUE THREAD

**Issue by now163** [shadowsocks/shadowsocks-manager#135]
### What operating system are you using?
ubuntu16.04

webgui放在了google cloud。发送邮件时，连接smtp服务器失败导致不能发送注册验证码。我在防火墙上开放了25，465，587。是不是还要开通其他的端口？

**Comment by gyteng** [comment]
这个我也不是很清楚

2017-03-18 11:03 GMT+08:00 YuLu <notifications@github.com>:

**Comment by now163** [comment]
多谢回复。我再去调试一下。如有进展，会回来贴一下解决方法。‘

**Comment by now163** [comment]
google cloud关闭25和465端口。没有办法使用smtp发送邮件。
但可以使用第三方的mailgun的API来发邮件，要是能添加这个功能就好啦。毕竟邮件代发还是很好的一个方案。站长可以省去自架邮件服务的工作。
记得ss-panel好像也有相关设置。

**Comment by soliury** [comment]
@gyteng 可以支持mailgun API么，我觉得这个应该比较简单，有计划支持么

**Comment by gyteng** [comment]
可能会支持
