### ISSUE TITLE
How to monitor ipv6 traffic?

### ISSUE THREAD

**Issue by AurelianoY** [shadowsocks/shadowsocks-manager#136]
The accounts created by ssmgr cannot be used in ipv6.

**Comment by Aur3l14no** [comment]
In config.json write
{
    "server":["::0","0.0.0.0"],
    "method":"aes-256-cfb"
}
Then, "ss-manager -c config.json --manager-address 127.0.0.1:6001"

**Comment by gyteng** [comment]
not support IPv6 now, I don't have an ipv6 vps to test it
