### ISSUE TITLE
Causing unstablity?

### ISSUE THREAD

**Issue by Aur3l14no** [shadowsocks/shadowsocks-manager#137]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.5.38

### What operating system are you using?
Debian 7
with 512 Ram

### What did you do?
ss-manager -c config.json --manager-address 127.0.0.1:6001 
pm2 --name "ssmgr-s" -f start ssmgr -x -- -c config.yml
pm2 --name "ssmgr-m" -f start ssmgr -x -- -c webgui.yml

config.json:
{
    "server":["::0","0.0.0.0"],
    "method":"aes-256-cfb"
}

### What did you expect to see?
Run stably.

### What did you see instead?
Shadowsocks client report
```
System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
```

every 1 min or so

**Comment by gyteng** [comment]
请提供shadowsocks版本，node版本


2017年3月19日 13:57，"Aur3l14no" <notifications@github.com>写道：

**Comment by Aur3l14no** [comment]
Node.js v6.10.0
shadowsocks v3.0.4

**Comment by gyteng** [comment]
试试把ipv6的监听端口去掉

**Comment by Aur3l14no** [comment]
貌似是这个原因...

**Comment by gyteng** [comment]
我没有ipv6的环境，所以测不了这种情况
