### ISSUE TITLE
如何使同一用户在各服务器下的流量额共享？

### ISSUE THREAD

**Issue by kongwy** [shadowsocks/shadowsocks-manager#141]
### What version of shadowsocks-manager are you using?

0.5.42

### What operating system are you using?

Ubuntu 16.04.2

### What version of Node.js are you using?

6.10.0

---

按文档默认配置在各服务器配置完 ssmgr with type s 之后，在 webgui 看各服务器流量用量是分别独立的，是不是因为各服务器已用量是记录在 ss.sqlite 中？是否需要更换 MySQL 使各 type s 共用一个 ss 数据库来实现流量额度共享？

**Comment by gyteng** [comment]
目前的账户体系设计比较简单，没有这个功能。
应该以后会增加

2017-03-21 14:05 GMT+08:00 Weiyi Kong <notifications@github.com>:

**Comment by kongwy** [comment]
所以目前改 MySQL 共用一个库也是没用的吗？

**Comment by gyteng** [comment]
是的，而且设计的时候并没有考虑多台服务器共用库的情况，都是单独计算流量的，这种情况需要在业务逻辑上面解决。

**Comment by kongwy** [comment]
好吧，顺便问下有没有加入自动生成 Surge 配置功能的计划？另外订价里的时、日、周有没有办法单独关掉？

**Comment by gyteng** [comment]
我不知道 Surge 配置是怎么样的，有没有文档，起什么作用？
现在没法单独关掉，关于用户帐号、价格这一块因为现在只是实现了一个最简易的功能，我还没想好如何把这块剥离出来做成可自由配置的。

2017-03-21 14:20 GMT+08:00 Weiyi Kong <notifications@github.com>:

**Comment by kongwy** [comment]
Surge 文档：https://manual.nssurge.com/

配置文件样例：[ZH](http://www.nssurge.com/config-example/zhHans.conf) | [EN](http://www.nssurge.com/config-example/en.conf)

另外这是一些常见的几个 Surge 配置版本：

 - https://gist.github.com/scomper/a487a9d5ac7290bc78514c3c9ac3e75a
 - https://gist.github.com/jason5ng32/648597df6ca7da5aeb41

生成时需要固定修改的应该只有 `[Proxy]` 和 `[Proxy Group]` 段，shadowsocks 的语法是：

    SSProxy = custom,$IP,$PORT,$METHOR,$PASSWORD,$SS_MODULE_URL 

`$SS_MODULE_URL` 是一个固定的模块，[ss-panel 项目下就有一个](https://github.com/orvice/ss-panel/blob/master/public/downloads/SSEncrypt.module)。
