### ISSUE TITLE
ERROR server already exists at 0.0.0.0:50013

### ISSUE THREAD

**Issue by Restry** [shadowsocks/shadowsocks-manager#142]
### What version of shadowsocks-manager are you using?
shadowsocks-manager 0.5.37

### What operating system are you using?
Ubuntu

### What version of Node.js are you using?
v7.6.0

### What did you do?
正常配置启动服务器  ，还启动了webgui
ssserver -m aes-256-cfb -k Google --manager-address 127.0.0.1:14000
ssmgr -c ss.yml

=============ss.yml===========
type: s
empty: false
shadowsocks:
  address: 127.0.0.1:14000
manager:
  address: 0.0.0.0:14808
  password: '1qaz2wsx'
db: 'ss.sqlite'

### What did you see instead?
日志里面有很多这种  server already exists at 0.0.0.0:50000  错误
1|sm       | /usr/local/lib/node_modules/shadowsocks-manager/lib/
1|sm       | [2017-03-18 05:03:30.521] [INFO] system - System start.
1|sm       | [2017-03-18 05:03:30.573] [INFO] system - ~/.ssmgr/default.yml not found, make file for it.
1|sm       | raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
1|sm       | /usr/local/lib/node_modules/shadowsocks-manager/lib/
1|sm       | [2017-03-19 20:31:08.072] [INFO] system - System start.
1|sm       | raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting

/root/.pm2/logs/server-error-0.log last 15 lines:
0|server   | 2017-03-21 02:18:11 ERROR    server already exists at 0.0.0.0:50013
0|server   | 2017-03-21 02:18:14 WARNING  timed out: api.pinterest.com:443
0|server   | 2017-03-21 02:18:14 WARNING  timed out: mtalk.google.com:5228
0|server   | 2017-03-21 02:18:27 ERROR    [Errno 104] Connection reset by peer
0|server   | 2017-03-21 02:18:39 INFO     connecting api.pinterest.com:443 from 211.167.232.50:49634
**0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50000**
0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50001
0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50002
0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50003
0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50004
0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50005
**0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50006**
0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50007
0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50012
0|server   | 2017-03-21 02:19:11 ERROR    server already exists at 0.0.0.0:50013

我想知道这个是正常的吗？晚上用的人多的时候还会掉线，掉得很频繁

**Comment by gyteng** [comment]
请更新到 0.5.42，已经解决了问题

2017-03-21 14:22 GMT+08:00 Restry <notifications@github.com>:

**Comment by jacklau88** [comment]
在最新的版本中依然存在 这个问题
