### ISSUE TITLE
请问WebGui中如何设置每个服务器中的用户数量？

### ISSUE THREAD

**Issue by Restry** [shadowsocks/shadowsocks-manager#143]
如标题所说：
版本是shadowsocks-manager 0.5.38

请问WebGui中如何设置每个服务器中的用户数量？
还有公告怎么样去设置？

**Comment by gyteng** [comment]
最大用户数量？

**Comment by Restry** [comment]
不是，比如我有2个服务器，10个用户。我要设置5个用户到服务器1中，5个用户到服务器2中。

公告的问题我知道更新版本就可以。不好意思提问前没有检查版本。谢谢

**Comment by gyteng** [comment]
目前还没有这个功能，无法指定这个用户只能用哪个服务器，只要添加的服务器都会有。

公告功能还没完成的。

**Comment by Restry** [comment]
再问一下:)  shadowsocks-manager 的WEBGUI  有人用VUE或者React重写过吗？

**Comment by gyteng** [comment]
目前没有吧
