### ISSUE TITLE
右下角加号按钮的问题

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#145]
目前点击行为是放在正中心的“+”上，而不是整个粉红色圆形上，PC上高分屏真的不大好点。准确的说是容易点到圆形单没点到加号，给人点了没反应的错觉。能否更改一下呢？参考inbox.google.com的加号

**Comment by gyteng** [comment]
已修复，之前没留意到这个细节，多谢提醒

**Comment by cokebar** [comment]
好快！谢谢！

**Comment by cokebar** [comment]
@gyteng 今天又发现一些同类问题。
许多地方虽然光标变为手性但不能点击，如：
![222](https://cloud.githubusercontent.com/assets/9136591/24183806/656c1378-0f05-11e7-90e3-1750794be68f.png)
再如：
![333](https://cloud.githubusercontent.com/assets/9136591/24183849/b547a9fc-0f05-11e7-95d4-7416db777eff.png)
