### ISSUE TITLE
[webgui] 添加公告后 后退按钮无限循环

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#148]
ssmgr版本：
0.5.48

重现方式：
1. 手机端用chrome添加桌面app
2. 进入公告设置（侧边栏消失）
3. 设置好后保存
4. 点击后退，无限循环
5. 对于桌面app 只能退出重进

**Comment by gyteng** [comment]
fix in 309dde9c1493d54caf701f87963d1fb6dee48835

**Comment by cokebar** [comment]
thanks for the great work! I'll make a donate.
