### ISSUE TITLE
webgui.yml中更新ss服务器信息后不生效 且无法在webgui中删除无效的服务器配置

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#149]
ssmgr应该是首次启动时候将ss服务器信息存储在数据库中了，这样即使更改了配置文件也无法改变服务器配置。由于可能存在IP失效（比如说突然IP blocked，或者到期了），或者需要端口更改的情况，可能导致之前的地址无效，此时需要修改服务器配置，这时候webgui上是无法修改已经无效的服务器配置的，也不能删除，也会一直报错。如果想要修改只能删除数据库（不可行），或者进行手动进行数据库操作（很麻烦）
而yml中配置的服务器，只在第一次时有效，以后修改的话都是数据库中，那么不如干脆yml中不要包含这条配置。

**Comment by gyteng** [comment]
这个问题我早就留意到了，这个改动涉及前端界面的部分较多，所以一直还没改

**Comment by niclau** [comment]
@gyteng 或者可否在webgui中加入服务器当前状态的信息？

**Comment by gyteng** [comment]
@niclau 状态信息是指？

**Comment by cokebar** [comment]
问题仍然存在。重现：
```
ssmgr -V
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-24 17:24:51.398] [INFO] system - System start.
shadowsocks-manager 0.5.52
```
原来bind的IP为公网IP，网页显示的也是公网IP，正常工作，现在将配置文件统一改成127.0.0.1，mode s正常启动：
```
root@cokebar:~/shadowsocks-manager# ssmgr -c ssmgr.yml --debug
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-24 17:20:02.426] [INFO] system - System start.
[2017-03-24 17:20:02.617] [INFO] system - Config file path:  /root/.ssmgr/ssmgr.yml
[2017-03-24 17:20:03.082] [INFO] system - server listen on 127.0.0.1:5775
[2017-03-24 17:20:03.084] [INFO] system - Receive flow from shadowsocks: (libev)
{}
raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
```

webgui mode m 出错，仍然未更新IP信息：
```
ssmgr -c webgui.yml --debug

```
/usr/lib/node_modules/shadowsocks-manager/lib/
[32m[2017-03-24 17:18:16.901] [INFO] system - [39mSystem start.
[32m[2017-03-24 17:18:17.089] [INFO] system - [39mConfig file path:  /root/.ssmgr/webgui.yml
[32m[2017-03-24 17:18:17.545] [INFO] system - [39mLoad plugin: flowSaver
[32m[2017-03-24 17:18:17.546] [INFO] system - [39mLoad plugin db: flowSaver/db/saveFlow.js
[32m[2017-03-24 17:18:17.548] [INFO] system - [39mLoad plugin db: flowSaver/db/server.js
[32m[2017-03-24 17:18:17.550] [INFO] system - [39mLoad plugin: user
[32m[2017-03-24 17:18:17.550] [INFO] system - [39mLoad plugin db: user/db/user.js
[32m[2017-03-24 17:18:17.551] [INFO] system - [39mLoad plugin: account
[32m[2017-03-24 17:18:17.552] [INFO] system - [39mLoad plugin db: account/db/account.js
[32m[2017-03-24 17:18:17.553] [INFO] system - [39mLoad plugin: email
[32m[2017-03-24 17:18:17.554] [INFO] system - [39mLoad plugin db: email/db/email.js
[32m[2017-03-24 17:18:17.555] [INFO] system - [39mLoad plugin: webgui
[32m[2017-03-24 17:18:17.555] [INFO] system - [39mLoad plugin db: webgui/db/notice.js
[32m[2017-03-24 17:18:17.558] [INFO] system - [39mLoad plugin db: webgui/db/push.js
[32m[2017-03-24 17:18:17.560] [INFO] system - [39mLoad plugin db: webgui/db/setting.js
[32m[2017-03-24 17:18:17.561] [INFO] system - [39mLoad plugin: alipay
[32m[2017-03-24 17:18:17.561] [INFO] system - [39mLoad plugin db: alipay/db/alipay.js
[32m[2017-03-24 17:18:17.579] [INFO] system - [39mLoad plugin index: user/index
[32m[2017-03-24 17:18:17.583] [INFO] system - [39mLoad plugin index: account/index
[32m[2017-03-24 17:18:17.607] [INFO] system - [39mLoad plugin index: email/index
[32m[2017-03-24 17:18:17.673] [INFO] system - [39mLoad plugin index: webgui/index
[32m[2017-03-24 17:18:18.041] [INFO] webgui - [39mserver start at 127.0.0.1:5777
[32m[2017-03-24 17:18:18.046] [INFO] system - [39mLoad plugin index: alipay/index
[32m[2017-03-24 17:18:18.048] [INFO] system - [39mLoad plugin index: flowSaver/index
[31m[2017-03-24 17:18:18.072] [ERROR] system - [39m{ Error: connect ECONNREFUSED 110.110.110.110:5775
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '110.110.110.110',
  port: 5775 }
[31m[2017-03-24 17:18:18.077] [ERROR] flowSaver - [39mError: connect to ssmgr[s] fail
    at Socket.client.on.err (/usr/lib/node_modules/shadowsocks-manager/lib/services/manager.js:102:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
```

**Comment by cokebar** [comment]
哦 是webgui里可以修改IP了

**Comment by niclau** [comment]
@gyteng 就是显示服务器是否可用，如绿色表示可用，红色不可用。

**Comment by cokebar** [comment]
1. webgui里可以删除服务器配置了
2. 无法修改配置，点击确定没反应
3. 对于已无法连接的服务器配置，终端会报错，webgui会点不开，这样一来还是无法编辑、删除无效的服务器

**Comment by gyteng** [comment]
可以删除无效的，编辑保存的时候会检测有效性，无效的不能保存

Cokebar Chi <notifications@github.com>于2017年3月24日 周五17:39写道：

**Comment by cokebar** [comment]
@gyteng 
1.无效的可以加个提示
2. 已存在的无效的根本点不进去

**Comment by cokebar** [comment]
@gyteng 删空原来的服务器配置 重新设置又好了

**Comment by liangzhenghui** [comment]
@cokebar 怎么删空服务器配置？我遇到的问题和你的很像。ssmgr -c ssmgr.yml --debug 指向的是127.0.0.0.1:4001 。但是 at Object.exports._errnoException (util.js:1018:11)
at exports._exceptionWithHostPort (util.js:1041:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect',
address: '公网ip',
port: 4009 }
求助如何解决这个问题？
