### ISSUE TITLE
Different display address and manage address

### ISSUE THREAD

**Issue by wzxjohn** [shadowsocks/shadowsocks-manager#151]
When webgui runs on the same server, ssmgr's manage socket can be access from 127.0.0.1. But because webgui also use this address for display and QR code generate, the config json will be totally wrong. Maybe these two config should be split.

当 Web 界面与服务端跑在相同机器上时，实际上可以用 127.0.0.1 来访问管理端口。但是由于 Web 界面会展示这个连接管理端口的 IP 地址，并用来做二维码生成，所以这里是否应该分开配置管理用 IP 和展示用 IP 呢？

**Comment by gyteng** [comment]
fix in bc0dca9bb6d63db470820a7e5975378faa3a3f5c

**Comment by wzxjohn** [comment]
你确定数据库里直接存 1.2.3.4:2.3.4.5 不会影响连接管理地址？
