### ISSUE TITLE
希望增加管理员手动添加/删除用户的功能

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#153]
对于不想开放注册的站点来说应该很有用

**Comment by DearTanker** [comment]
同意啊。这个必须要有啊

**Comment by gyteng** [comment]
目前暂不考虑增加额外功能，或许以后会添加

**Comment by zhfreal** [comment]
@gyteng，老大没有手动添加用户也行。端口那里加个备注总行吧？

**Comment by loseheaven** [comment]
+1

**Comment by angusding** [comment]
这个很有用，顶下！

**Comment by miniers** [comment]
https://github.com/miniers/shadowsocks-manager/tree/manager-user

自己fork改了份管理员能够管理用户的分支，有需求的可以自取

**Comment by gyteng** [comment]
已添加
