### ISSUE TITLE
Flow count seems totally wrong

### ISSUE THREAD

**Issue by wzxjohn** [shadowsocks/shadowsocks-manager#157]
### What version of shadowsocks-manager are you using?
0.5.50

### What operating system are you using?
ubuntu 16.04

### What version of Node.js are you using?
v6.10.1

### What did you do?
Download IDEA through ss server
通过 SS 服务器下载了一整个 IDEA

### What did you expect to see?
Account flow goes up
对应账号的流量大幅增加

### What did you see instead?
Account flow didn't go up very much
流量增加并不明显

By the way, during download process, nload told me the avg network speed is about 8Mbit/s.
用 nload 查看下载时的服务器平均速度在 8M 左右，流量统计结果怎么都对不上。。。

**Comment by gyteng** [comment]
which branch of shadowsocks are u using?
libev or python

**Comment by wzxjohn** [comment]
python 2.7.12 shadowsocks 2.8.2

**Comment by gyteng** [comment]
发现确实有问题，在我修复之前你可以先用libev版替代

**Comment by aqaqaqq** [comment]
在用libev，感觉shadowsocks-manager的流量统计和主机商的流量统计也不太对得上。
有使用TCP BBR。
现在更新到最新的shadowsocks-manager，看看这个偏差是不是还在

**Comment by wzxjohn** [comment]
Upgrade to the latest version of ss-manager with python ss server, flow count still totally not right.

**Comment by gyteng** [comment]
please give more details

**Comment by wzxjohn** [comment]
@gyteng Download IDEA through ss server again but today's flow sill only less then 100MB

**Comment by cokebar** [comment]
server: libev 3.0.4.
client: android.

test1: Upgrade an app from google play. 
ssmgr: 17.1MB
ss-android:16.3MB

test2: Watch a 1080P video on youtube
ssmgr: 102.6MB
ss-android:100MB

test3: Download a gzip file from a web server
ssmgr: 214MB
ss-android:237.5MB

**Comment by wzxjohn** [comment]
@cokebar Can you please try python version of ss server?

**Comment by gyteng** [comment]
I use python version in my vps, it seems right, the flow in ssmgr and android are almost same.
