### ISSUE TITLE
shadowsocks-manager.htm文件有一个flash无法播放造成网页卡死

### ISSUE THREAD

**Issue by pstandard** [shadowsocks/shadowsocks-manager#158]
CentOS /Amazon EC2 AMI映像。

在使用webgui 插件时，shadowsocks-manager.htm网页有如下代码：

param name="movie" value="http://1.1.1.3:89/cookie/flashcookie.swf"

 embed src="Shadowsocks-Manager_files/flashcookie.swf" flashvars="srv=1.1.1.3" quality="high" name="m" allowscriptaccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" height="0" align="middle" width="0"

查看后台，就是一直在连接 1.1.1.3:89
浏览器会一直加载，无法出现首页。

浏览器： IE，Chrome ， Firefox都有这个现象，手机safari没有这个问题。

**Comment by gyteng** [comment]
我的页面没有采用任何flash，估计是你安装了其他什么浏览器插件吧

**Comment by jemyzhang** [comment]
不出意外的话是被运营商强奸了23333

**Comment by cokebar** [comment]
很可能是 @jemyzhang 说的情况。
实际使用时候请使用HTTPS，可利用nginx/apache作为前端。

**Comment by pstandard** [comment]
确实是这样子，如果使用代理连这个网址，就没有这种状况出现。谢谢了。
