### ISSUE TITLE
Python版本流量统计没有用

### ISSUE THREAD

**Issue by mohuishou** [shadowsocks/shadowsocks-manager#16]

**Comment by gyteng** [comment]
请提供更详细的信息，如shadowsocks的版本、安装方式、操作系统版本、shadowsocks-manager的配置截图等

**Comment by mohuishou** [comment]
**开启命令：**
```
ssserver --manager-address 0.0.0.0:6001  -c /root/ss.json --fast-open -d start
```
**ss.json**
```
{
    "server": "0.0.0.0",
    "port_password": {
       "8000":"lailin"
    },
    "timeout": 300,
    "method": "aes-256-cfb"
}
```
**ss版本**
2.8.2
**后台服务器配置截图**
![image](https://cloud.githubusercontent.com/assets/15172509/16226069/4fdc18a6-37dc-11e6-96b2-689379187fa1.png)

![image](https://cloud.githubusercontent.com/assets/15172509/16226112/8836480c-37dc-11e6-8daf-e5877bdfb918.png)

**操作系统**
![image](https://cloud.githubusercontent.com/assets/15172509/16226139/a0e8f44e-37dc-11e6-916b-21b4be87d7c0.png)

**安装方式**
pip

**Comment by gyteng** [comment]
现在是不是管理界面添加端口后可以成功，但无法统计流量？
如果是的话，你试试去掉--fast-open能否成功，目前我也不清楚具体什么原因。

**Comment by mohuishou** [comment]
是的，去掉--fast-open之前就试过了

**Comment by mohuishou** [comment]
我刚刚试了一下libev版本的，没有问题可以使用流量统计
但是Python的还是不行，试了很久了
![image](https://cloud.githubusercontent.com/assets/15172509/16227561/ef14399c-37e3-11e6-82c4-1bd448280f6d.png)

**Comment by gyteng** [comment]
这个问题很奇怪，我跟你用的一样的系统，一样的版本，但统计功能正常。之前也有另一个人跟我提过统计功能不工作，依然没找出原因。

**Comment by mohuishou** [comment]
真是一个奇怪的问题，过两天我考完试再仔细看看是不是哪儿有bug或者重现一下

**Comment by xlliu** [comment]
请问这个问题解决了吗？ 我现在用最新版的 libev 可以通过web页面 添加账号，也可以使用， 但是流量统计 还是无效 。

**Comment by chy06201** [comment]
> **开启命令：**
> 
> ```
> ssserver --manager-address 0.0.0.0:6001  -c /root/ss.json --fast-open -d start
> ```
> **ss.json**
> 
> ```
> {
>     "server": "0.0.0.0",
>     "port_password": {
>        "8000":"lailin"
>     },
>     "timeout": 300,
>     "method": "aes-256-cfb"
> }
> ```
> **ss版本**
> 2.8.2
> **后台服务器配置截图**
> ![image](https://cloud.githubusercontent.com/assets/15172509/16226069/4fdc18a6-37dc-11e6-96b2-689379187fa1.png)
> 
> ![image](https://cloud.githubusercontent.com/assets/15172509/16226112/8836480c-37dc-11e6-8daf-e5877bdfb918.png)
> 
> **操作系统**
> ![image](https://cloud.githubusercontent.com/assets/15172509/16226139/a0e8f44e-37dc-11e6-916b-21b4be87d7c0.png)
> 
> **安装方式**
> pip

输入了开启命令报错：
No such file or directory: '/var/run/shadowsocks.pid'

**Comment by gyteng** [comment]
@chy06201 这个古老的版本已经不维护了
