### ISSUE TITLE
npm安装报错，ssmgr不能正常使用

### ISSUE THREAD

**Issue by aqaqaqq** [shadowsocks/shadowsocks-manager#161]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.5.64

### What operating system are you using?
Debian 8.7

### What version of Node.js are you using?
v6.10.1

### What did you do?
从0.5.55用`npm i -g shadowsocks-manager`升级到0.5.64

### What did you expect to see?
安装后能正常使用

### What did you see instead?

> $npm i -g shadowsocks-manager
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> /usr/bin/ssmgr -> /usr/lib/node_modules/shadowsocks-manager/bin/ssmgr
> 
> > shadowsocks-manager@0.5.64 postinstall /usr/lib/node_modules/shadowsocks-manager
> > gulp
> 
> 
> 
> $

且ssmgr不能正常使用。

再次`npm i -g shadowsocks-manager`：

> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> /usr/bin/ssmgr -> /usr/lib/node_modules/shadowsocks-manager/bin/ssmgr
> 
> > shadowsocks-manager@0.5.64 postinstall /usr/lib/node_modules/shadowsocks-manager
> > gulp
> 
> [01:47:43] Using gulpfile /usr/lib/node_modules/shadowsocks-manager/gulpfile.js
> [01:47:43] Starting 'clean'...
> [01:47:43] Starting 'webguiBuild'...
> [01:47:43] Starting 'freeAccountBuild'...
> [01:47:43] Finished 'clean' after 175 ms
> [01:47:43] Starting 'babelCopy'...
> [01:47:44] Finished 'babelCopy' after 567 ms
> [01:47:47] Version: webpack 1.14.0
>     Asset   Size  Chunks             Chunk Names
> bundle.js  51 kB       0  [emitted]  main
> [01:47:48] Version: webpack 1.14.0
>     Asset     Size  Chunks             Chunk Names
> bundle.js  6.83 kB       0  [emitted]  main
> [01:47:48] Finished 'webguiBuild' after 4.74 s
> [01:47:48] Starting 'webguiCopy'...
> [01:47:48] Finished 'freeAccountBuild' after 4.64 s
> [01:47:48] Starting 'freeAccountCopy'...
> [01:47:48] Finished 'freeAccountCopy' after 123 ms
> [01:47:48] Finished 'webguiCopy' after 198 ms
> [01:47:48] Starting 'babel'...
> Killed
> $[01:51:12] Finished 'babel' after 3.4 min
> [01:51:12] Starting 'default'...
> [01:51:12] Finished 'default' after 6.66 μs

ssmgr可正常使用。

`npm i -g shadowsocks-manager@0.5.55`可正常安装并使用。

**Comment by gyteng** [comment]
安装完后应该会自动运行gulp，然后就完成了，你那中间的 `killed` 是咋回事？

**Comment by aqaqaqq** [comment]
我想表述的基本上就是gulp有时不会自动运行。又重新安装了几次，问题有时能够复现，发现可能是内存不够（`killed`）

$npm i -g shadowsocks-manager@0.5.64
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Killed          ...] \ extract:rx: verb gentlyRm don't care about contents; nuking /usr/lib/node_mo
$

开始安装前有420MB的空闲内存，被系统杀掉前只剩13MB左右，这对大部分的VPS不太友好。

0.5.55和0.5.58安装时的内存占用也不小，但比0.5.59和之后的版本少，能够顺利完成安装

**Comment by gyteng** [comment]
看来我要考虑一下上传npm的时候自动build好

**Comment by gyteng** [comment]
你试一下 0.5.66 版本的，是已经 build 好的

**Comment by aqaqaqq** [comment]
0.5.66 能够顺利安装，有些WARN，目前看来不影响使用

> $npm i -g shadowsocks-manager
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> /usr/bin/ssmgr -> /usr/lib/node_modules/shadowsocks-manager/bin/ssmgr
> /usr/lib
> `-- shadowsocks-manager@0.5.66
>   `-- express-validator@3.1.2
>     `-- @types/express@4.0.35
>       `-- @types/express-serve-static-core@4.0.44
>         `-- @types/node@7.0.12
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/shadowsocks-manager/node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by smilingsun** [comment]
请问，最近一个已build的版本是什么？512MB的OpenVZ弱机求build版。
