### ISSUE TITLE
pls help install some issues

### ISSUE THREAD

**Issue by jiashooter** [shadowsocks/shadowsocks-manager#162]
### What version of shadowsocks-manager are you using?
latest version through git got it

### What operating system are you using?
Centos7

### What version of Node.js are you using?
v6.10.1

### What did you do?
when I used command "npm -i" install it will pop-up some issues, please see error message on below.

[root@instance-2 shadowsocks-manager]# npm i
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Killed           ..] | extract:webpack: sill gunzTarPerm extractEntry node_modules/node-pre-gyp/node_modules/re 

How can i fix it and fully installation.
Thanks :)

**Comment by gyteng** [comment]
maybe you can remove node_modules and reinstall

2017-03-30 12:10 GMT+08:00 jiashooter <notifications@github.com>:

**Comment by jiashooter** [comment]
I have removed "node_modules" folder and reinstall but still had new issue. 
"Killed           ..] | extract:minimist: sill gunzTarPerm extractEntry lib/dot/allOf.jst"

**Comment by gyteng** [comment]
Maybe you have to increase your vps's memory or swap space

**Comment by jiashooter** [comment]
At least how much both memory and swap space were needed?

**Comment by gyteng** [comment]
I don't know, I use a 512m VPS and it works well.
