### ISSUE TITLE
compress log files

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#165]
Please compress log files or it will be very big.

**Comment by gyteng** [comment]
I'm so sorry, I just add a compress params as the docs of log4js, but I can not find the compress file either.
Maybe I use the wrong way, I will fix it later.

**Comment by gyteng** [comment]
hey, the compress function work well now, the new verison will upgrade log4js from 0.6 to 1.1 to solve this problem.
