### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by holyen** [shadowsocks/shadowsocks-manager#166]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
最新版

### What operating system are you using?

ubuntu 16
### What version of Node.js are you using?
v6.10.1

### What did you do?
npm i -g shadowsocks-manager

### What did you expect to see?
安装成功

### What did you see instead?
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/shadowsocks-manager/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 2.6.32-042stab120.18
npm ERR! argv "/root/node-v6.10.1-linux-x64/bin/node" "/root/node-v6.10.1-linux-x64/bin/npm" "i" "-g" "shadowsocks-manager"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1

**Comment by gyteng** [comment]
可能是网络问题导致的，重试几次都是这样吗？

**Comment by holyen** [comment]
可以了 但出现了另一个问题 麻烦看看 @gyteng [https://github.com/shadowsocks/shadowsocks-manager/issues/167](url)
