### ISSUE TITLE
连接失败  flowSaver - connect to server c12345@127.0.0.1:4001 fail.

### ISSUE THREAD

**Issue by holyen** [shadowsocks/shadowsocks-manager#167]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
最新

### What operating system are you using?
ubuntu 16.4

### What version of Node.js are you using?
6.10.1

### What did you do?
安装 manager

### What did you expect to see?
安装成功

### What did you see instead?
失败
[2017-03-31 06:19:53.282] [ERROR] flowSaver - connect to server c12345@127.0.0.1:4001 fail.

### What is your config in detail (with all sensitive info masked)?
麻烦看看,不知道是哪出问题
/etc/shadowsocks-libev/config.json内容是:
```javascript
    {
        "server":"127.0.0.1",
        "server_port":8388,
        "local_port":1080,
        "password":"c12345",
        "timeout":60,
        "method":"aes-256-cfb"
    }
```

终端命令
```javascript
ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:8388
```

~/.ssmgr/ss.yml 的内容:

```javascript
type: s
empty: false

shadowsocks:
    address: 127.0.0.1:8388

manager:
    address: 127.0.0.1:4001
    password: 'c12345'

db: 'ss.sqlite'
```
 
 执行终端命令:
```javascript
ssmgr -c ss.yml
``` 后提示:

 [2017-03-31 06:17:03.800] [INFO] SYSTEM - SYSTEM START.
RAVEN@1.2.0 ALERT: FAILED TO SEND EXCEPTION TO SENTRY: HTTP ERROR (429): CREATION OF THIS EVENT WAS DENIED DUE TO RATE LIMITING
```

~/.ssmgr/webgui.yml 内容:
```json
type: m
empty: false
manager:
    address: 127.0.0.1:4001
    password: 'c12345'
plugins:
    flowSaver:
        use: true
    user:
        use: true
    account:
        use: true
        pay:
            hour:
                price: 0.03
                flow: 500000000
            day:
                price: 0.5
                flow: 7000000000
            week:
                price: 3
                flow: 50000000000
            month:
                price: 10
                flow: 200000000000
            season:
                price: 30
                flow: 200000000000
            year:
                price: 120
                flow: 200000000000
    email:
        use: true
        username: 'username'
        password: 'password'
        host: 'smtp.your-email.com'
    webgui:
        use: true
        host: '0.0.0.0'
        port: '80'
        site: '<?~Y?~B??~\??~]~@>'
        gcmSenderId: '456102641793'
        gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
    alipay:
        use: true
        appid: <?~T??~X?~] APPID>
        notifyUrl: ''
        merchantPrivateKey: '<rsa_private_key.pem 中?~Z~D?~A?~R?>'
        alipayPublicKey: '<?~T??~X?~]?~E??~R?>'
        gatewayUrl: 'https://openapi.alipay.com/gateway.do'
db: 'webgui.sqlite'
```

执行 ssmgr -c webgui.yml 后:
```javascript
[2017-03-31 06:19:52.560] [INFO] system - System start.
[2017-03-31 06:19:53.278] [ERROR] system - { Error: connect ECONNREFUSED 127.0.0.1:4001
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4001 }
[2017-03-31 06:19:53.282] [ERROR] flowSaver - connect to server c12345@127.0.0.1:4001 fail.
```

**Comment by holyen** [comment]
麻烦看看,不知道是哪出问题
/etc/shadowsocks-libev/config.json内容是:
{
"server":"127.0.0.1",
"server_port":8388,
"local_port":1080,
"password":"c12345",
"timeout":60,
"method":"aes-256-cfb"
}

终端命令
ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:8388

~/.ssmgr/ss.yml 的内容:

type: s
empty: false

shadowsocks:
address: 127.0.0.1:8388

manager:
address: 127.0.0.1:4001
password: 'c12345'

db: 'ss.sqlite'

执行终端命令:
ssmgr -c ss.yml 后提示:

[2017-03-31 06:17:03.800] [INFO] system - System start.
raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting

~/.ssmgr/webgui.yml 内容:
type: m
empty: false
manager:
address: 127.0.0.1:4001
password: 'c12345'
plugins:
flowSaver:
use: true
user:
use: true
account:
use: true
pay:
hour:
price: 0.03
flow: 500000000
day:
price: 0.5
flow: 7000000000
week:
price: 3
flow: 50000000000
month:
price: 10
flow: 200000000000
season:
price: 30
flow: 200000000000
year:
price: 120
flow: 200000000000
email:
use: true
username: 'username'
password: 'password'
host: 'smtp.your-email.com'
webgui:
use: true
host: '0.0.0.0'
port: '80'
site: '' gcmSenderId: '456102641793' gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX' alipay: use: true appid: notifyUrl: '' merchantPrivateKey: ''
alipayPublicKey: ''
gatewayUrl: 'https://openapi.alipay.com/gateway.do'
db: 'webgui.sqlite'

执行 ssmgr -c webgui.yml 后:
[2017-03-31 06:19:52.560] [INFO] system - System start.
[2017-03-31 06:19:53.278] [ERROR] system - { Error: connect ECONNREFUSED 127.0.0.1:4001
at Object.exports._errnoException (util.js:1018:11)
at exports._exceptionWithHostPort (util.js:1041:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 4001 }
[2017-03-31 06:19:53.282] [ERROR] flowSaver - connect to server c12345@127.0.0.1:4001 fail.

**Comment by gyteng** [comment]
请检查4001端口是否已经开启：

`netstat -na | grep 4001`

**Comment by holyen** [comment]
空的 @gyteng

**Comment by gyteng** [comment]
端口都没开，当然无法连接了

**Comment by holyen** [comment]
可是我已经执行了命令

**Comment by holyen** [comment]
```javascript
root@localhost:~# ssmgr -c ss.yml
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-31 21:52:11.510] [INFO] system - System start.
raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
```

**Comment by gyteng** [comment]
是不是你执行以后又关掉了

**Comment by holyen** [comment]
没有啊,提示的就是这个 错误

**Comment by gyteng** [comment]
执行的时候加上 --debug 显示更详细的信息

**Comment by holyen** [comment]
没有啊,提示的就是这个 错误,[2017-03-31 21:52:11.510] [INFO] system - System start.
raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting

**Comment by holyen** [comment]
```javascript
root@localhost:~# ssmgr -c ss.yml --debug
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-31 22:00:45.244] [INFO] system - System start.
[2017-03-31 22:00:45.421] [INFO] system - Config file path:  /root/.ssmgr/ss.yml
[2017-03-31 22:00:45.864] [INFO] system - server listen on 127.0.0.1:4001
raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
```

**Comment by holyen** [comment]
现在可以了...这好奇怪 我执行完 ssmgr -c ss.yml 再开一个终端 执行ssmgr -c webgui.yml 才可以 ubuntu操作这么麻烦

**Comment by gyteng** [comment]
是这样的，你执行完后不能关了，关了当然不能连接。
需要后台运行程序的话，请参考 pm2 或者 screen 之类的工具

**Comment by holyen** [comment]
还有一个问题呃, 就是我注册了新用户 分配了一个ip,但这个ip显示的是 127.0.0.1 这个ip是在哪改的啊 @gyteng

**Comment by gyteng** [comment]
`~/.ssmgr/ss.yml` 这个文件需要改动一下：

```
manager:
    address: 0.0.0.0:4001
```

然后在web界面把服务器删除，重新添加，IP写你vps的公网ip

**Comment by holyen** [comment]
最后一个问题哈 支付宝续费貌似没用,这个要在哪设置了 @gyteng

**Comment by holyen** [comment]
支付宝私钥是指什么啊,我支付宝只看到了 RSA(SHA1)密钥 和 RSA2(SHA256)密钥 @gyteng  谢谢~~~

**Comment by gyteng** [comment]
这个wiki里有写
