### ISSUE TITLE
shadowsocks-manager是否可以在ubuntu开机自启

### ISSUE THREAD

**Issue by holyen** [shadowsocks/shadowsocks-manager#169]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

**Comment by jiashooter** [comment]
你可以去研究下supervisord

**Comment by gyteng** [comment]
可以使用pm2
