### ISSUE TITLE
新账号分配策略

### ISSUE THREAD

**Issue by mnzn** [shadowsocks/shadowsocks-manager#171]
### What did you do?
在服务器管理页面添加一台新服务器

### What did you expect to see?
该服务器只为以后新注册用户提供账号

### What did you see instead?
该服务器为系统中所有用户提供账号

PS：建议在服务器或设置中提供一个选项，设定当前新注册用户默认在哪台服务器中创建账号。
谢谢

**Comment by mnzn** [comment]
目前的逻辑下，添加十台服务器后，每个用户都会有10个账号，且每个用户可用流量也变为以前10倍。如果服务器再多的话系统很难管理了，希望能尽快添加该功能 ，谢谢！@gyteng

**Comment by gyteng** [comment]
当前版本的账号策略是这样的，我还没想好该如何实现一个灵活配置的账号策略，如果你有好的办法请提出

**Comment by zhfreal** [comment]
@gyteng ，服务器分组，然后用户/账号归结到服务器组，如何？

**Comment by mnzn** [comment]
1.在新用户自动分配账号的选项下面增加“服务器”选项，以控制新账号分配到哪个服务器中；
![sp170405_113750](https://cloud.githubusercontent.com/assets/3492200/24690003/f1980c9c-19fc-11e7-9c8a-aec1ef70accf.png)
2.账号页面中将账号用所在服务器来进行分组显示
3.账号页面中手动添加账号时增加服务器设置项
![bbbb](https://cloud.githubusercontent.com/assets/3492200/24690301/9adaed8c-19fe-11e7-8ed9-7baa0288cd3b.png)
4.我的账号中tab中，只显示该用户已有的账号，而不是所有服务器的账号
![cccc](https://cloud.githubusercontent.com/assets/3492200/24690394/1cac5ad0-19ff-11e7-90a6-59cc18e18c0e.png)
5.其他前端显示账号信息的地方增加该账号所在服务器的信息。
@gyteng

**Comment by mnzn** [comment]
6.修改账号的页面上增加“服务器”选项

**Comment by mnzn** [comment]
这样“自动分配”加“手动分配”应该足够灵活满足绝大多数场景需求了吧

**Comment by cokebar** [comment]
@mnzn 我觉得应该划分用户组。而针对每个用户组，可以为其分配允许使用那些服务器，每个服务器的流量配额是多少

**Comment by cokebar** [comment]
另外，服务器管理里面，如果同一个服务器下开了多个ssmgr mode s（比如需要开多种加密方式），应该视为同一个服务器，流量计算算两个总和

**Comment by mnzn** [comment]
@gyteng

**Comment by miniers** [comment]
@mnzn https://github.com/miniers/shadowsocks-manager/tree/manager-user
可以瞅瞅我的 fork 版本提供了此类功能，可以制定服务器是否自动添加到新建账号

**Comment by damonYuan** [comment]
@miniers  提PR啊

**Comment by hjyApple** [comment]
可以连接上，但是账户都是停用状态怎么解决啊
