### ISSUE TITLE
ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000 -bash: ss-manager: 未找到命令

### ISSUE THREAD

**Issue by holyen** [shadowsocks/shadowsocks-manager#174]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
最新

### What operating system are you using?
centos 7

### What version of Node.js are you using?
v6.10.1

### What did you do?
ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000

### What did you expect to see?
success

### What did you see instead?
 -bash: ss-manager: 未找到命令

### What is your config in detail (with all sensitive info masked)?
我是通过 npm i -g shadowsocks-manager这个命令去安装manager的,是否缺少步骤

**Comment by gyteng** [comment]
你需要先安装shadowsocks-libev

holyen <notifications@github.com>于2017年4月5日 周三12:36写道：

**Comment by holyen** [comment]
我已经安装了 @gyteng ,通过如下形式安装的:
curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"

python get-pip.py

pip install --upgrade pip

pip install shadowsocks
