### ISSUE TITLE
通过 通过 npm i -g shadowsocks-manager这个命令去安装manager 如何修改原代码

### ISSUE THREAD

**Issue by holyen** [shadowsocks/shadowsocks-manager#175]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What is your config in detail (with all sensitive info masked)?
谢谢~

**Comment by gyteng** [comment]
请用 git clone 去安装

**Comment by holyen** [comment]
有 centos7 git clone的教程吗 centos7 没有apt-get 没法安装呃 @gyteng

**Comment by cokebar** [comment]
centos 是yum 。。。

**Comment by holyen** [comment]
已经用git clone ; npm -i安装了 但源码的路径是哪 能否告知下 谢谢~~~ @gyteng @cokebar

**Comment by cokebar** [comment]
clone到的目录

holyen <notifications@github.com>于2017年4月5日 周三 15:32写道：

**Comment by cokebar** [comment]
你clone到哪，源码就在那

**Comment by holyen** [comment]
thanks~ @cokebar
