### ISSUE TITLE
如何在一台服务器上开两种/多种加密方式？

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#176]
想了半天，目前一个帐号对应所有服务器上都是相同端口 貌似无解。 除非再开一个webgui。
能否改善一下账号和服务器的对应策略，目前的是在太死了。
还有自动分配端口号希望可以定义端口单位，默认50000起太高了，很多isp，10000以上都封差不多了

**Comment by gyteng** [comment]
没有办法，这个是由 manager api 决定的，没有办法启动后更改加密方式

**Comment by cokebar** [comment]
@gyteng 但是可以开多个ss-manager达成多种加密方式，然而ssmgr的账号分配策略导致同一个服务器上躲开ss-manager是不可行的，因为多开的话，ssmgr会视为多个服务器，这样账号分配时候会分配同一个端口，直接造成端口冲突

**Comment by cokebar** [comment]
好吧连双开ss-manager都不行，暂时放弃了：https://github.com/shadowsocks/shadowsocks-libev/issues/1436

**Comment by qwIvan** [comment]
@gyteng 能否改进manager api

**Comment by cokebar** [comment]
@qwIvan 多开ss-manager，不过需要以不同用户身份运行，否则working dir相同，冲突的。

**Comment by cokebar** [comment]
@gyteng 如果可以对不同服务器分配不同范围的端口可以解决这个文件。

**Comment by whtsky** [comment]
hi, looks like ss-manager has supported setting different method for different users, see https://github.com/shadowsocks/shadowsocks-libev/pull/1403
