### ISSUE TITLE
pm2 --name "ssmgr" -f start ssmgr -x -- -c ss.yml 管理网站没有运行成功

### ISSUE THREAD

**Issue by holyen** [shadowsocks/shadowsocks-manager#177]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
最新

### What operating system are you using?
centos7

### What version of Node.js are you using?
v6.10.1

### What did you do?

pm2 --name "ssmgr" -f start ssmgr -x -- -c ss.yml
### What did you expect to see?

能打开管理网站
### What did you see instead?
无响应

### What is your config in detail (with all sensitive info masked)?
pm2 --name "ssmgr" -f start ssmgr -x -- -c ss.yml
pm2 --name "ssmgr" -f start ssmgr -x -- -c web.yml
是哪里出错了吗

**Comment by gyteng** [comment]
先别用 pm2 去启动，加上参数 `--debug`，看有啥异常信息出来

**Comment by holyen** [comment]
ssmgr -c ss.yml --debug
显示是正常的

**Comment by gyteng** [comment]
那应该就是你pm2的命令有问题，用pm2 logs可以查看日志

2017-04-07 13:37 GMT+08:00 holyen <notifications@github.com>:
