### ISSUE TITLE
How to modified index page?

### ISSUE THREAD

**Issue by jiashooter** [shadowsocks/shadowsocks-manager#178]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What is your config in detail (with all sensitive info masked)?

If I wanna to modified index page how can I do that.
Thanks.

**Comment by siuond** [comment]
You can try to modify these files.
```sh
$ sudo vim /usr/lib/node_modules/shadowsocks-manager/plugins/webgui/views/index.html
$ sudo vim /usr/lib/node_modules/shadowsocks-manager/plugins/webgui/public/views/home/home.html
$ sudo vim /usr/lib/node_modules/shadowsocks-manager/plugins/webgui/public/controllers/home.js
$ sudo vim /usr/lib/node_modules/shadowsocks-manager/plugins/webgui/public/serviceworker.js
```

After you modified the files, you need re-pack via executing below command in path 
`/usr/lib/node_modules/shadowsocks-manager/`
```sh
$ sudo npm run-script build
```
