### ISSUE TITLE
wingy扫码错误

### ISSUE THREAD

**Issue by relei1988** [shadowsocks/shadowsocks-manager#181]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?

0.5.49
### What operating system are you using?

ios
### What version of Node.js are you using?

6

用ios上的app wingy扫描生成的二维码，显示错误，无法直接生成信息，但shadowrocket可以

**Comment by gyteng** [comment]
加密方式是？

**Comment by relei1988** [comment]
aes256-cfb

**Comment by relei1988** [comment]
@gyteng 刚刚我在iphone上用safari浏览器保存了二维码，解码后得到
`aes-256-cfb:djjf***@883@139.16***:33***`
如果在电脑上直接截图的话中间的`@883`并不会多出来，感觉问题是出在这个上头

**Comment by gyteng** [comment]
估计是浏览器兼容性的问题，用Chrome打开的话wingy和shadowrocket都没有问题，我回头再多测试几个浏览器

**Comment by relei1988** [comment]
@gyteng 我拿电脑试了下，都是没问题的，用iphone上用自带浏览器打开会出现该问题，系统是ios10.2.1 之前ios9时候记得也有该问题

**Comment by relei1988** [comment]
@gyteng 我拿电脑试了下，都是没问题的，用iphone上用自带浏览器打开会出现该问题，系统是ios10.2.1 之前ios9时候记得也有该问题

**Comment by gyteng** [comment]
我在iOS下用Chrome和Safari都是正常的，你能重现你所说的问题吗？

**Comment by relei1988** [comment]
可以重现，已发邮件
