### ISSUE TITLE
Add capability to specify the published server name for ss

### ISSUE THREAD

**Issue by zxkane** [shadowsocks/shadowsocks-manager#182]
(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
latest gyteng/ssmgr image

### What operating system are you using?
gyteng/ssmgr image

### What version of Node.js are you using?
gyteng/ssmgr image

### What did you do?
I ran ss-manager, ssmgr type s and ssmgr type m in docker swarm as separated containers.

For example, the ssmgr type s named as 'ssmgr-type-s' in the cluster, ssmgr type m is using the service name 'ssmgr-type-s'. But the published ss server is not 'ssmgr-type-s'.

### What did you expect to see?
I would like to specify the server name for the public ss service.

### What is your config in detail (with all sensitive info masked)?
You can refer to below gist for detail configuration.
https://gist.github.com/zxkane/a2a6d5ddee24f0145e12149b814cc3b9

**Comment by gyteng** [comment]
What did you mean `the published ss server is not 'ssmgr-type-s'`?

2017-04-11 15:53 GMT+08:00 Meng Xin Zhu <notifications@github.com>:

**Comment by zxkane** [comment]
I deployed ss-manager, ssmgr-type-s and ssmgr-type-m(webgui plugin) in swarm cluster. Every service is a separated container. Webgui service can access `ssmgr-type-s` via its host name(ssmgr-type-s) inside swarm's network. 

However the ss client can not use the name `ssmgr-type-s`(which only is available inside swarm's network) to access the service of ss. However the generated barcode of account uses `ssmgr-type-s` as server address of ss. The users have to manually update it to the ip/domain of remote server in ss client.

**Comment by gyteng** [comment]
I know, you mean the barcode of webgui if incorrect?

2017-04-11 16:58 GMT+08:00 Meng Xin Zhu <notifications@github.com>:

**Comment by zxkane** [comment]
Yes. See below screenshot, the server address of account is the one specified in webui.yml. It works fine when webui plugin accesses ssmgr service. But it is meaningless for ss client if sharing the account via barcode. 

![image](https://cloud.githubusercontent.com/assets/843303/24902040/8658cc44-1edb-11e7-8427-39142f6fca4b.png)

**Comment by gyteng** [comment]
the problem will be fix later

**Comment by gyteng** [comment]
now you can edit your server info in the webside, set the host like this:

```
ssmgr-type-s:xxx:xxx:xxx:xxx
```

and the barcode will use the address xxx.xxx.xxx.xxx
