### ISSUE TITLE
手机打开订单详情页面后无法回退

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#183]
v0.5.75
缺少返回按钮，按系统返回键也无用。

![img_20170412_002854](https://cloud.githubusercontent.com/assets/9136591/24919974/17cbd4f4-1eab-11e7-809b-6850b774302b.png)

**Comment by gyteng** [comment]
再按一次就会自动缩小了

Cokebar Chi <notifications@github.com>于2017年4月12日 周三00:38写道：

**Comment by cokebar** [comment]
@gyteng 额。。好吧
有空的话建议改改吧 这已经是全屏的页面而不是PC上的对话框式了 习惯上都是点后退的；目前这种不符合习惯，估计十有八九的人不会想到是再点一下

**Comment by gyteng** [comment]
这个问题我早就意识到了，因为之前只先考虑把基本功能做出来，没考虑界面的美观和易用，除了这个，还有那个饼图之类的后面都要改动
