### ISSUE TITLE
续费流量不叠加问题

### ISSUE THREAD

**Issue by xiaosong** [shadowsocks/shadowsocks-manager#185]
### What version of shadowsocks-manager are you using?
v0.5.78

### What operating system are you using?
CentOS 7

### What version of Node.js are you using?
v6.10.2

### What did you do?
用户续费成功，通过支付宝付款并成功

### What did you expect to see?
用户续费成功后，新旧流量叠加为用户的可用流量

### What did you see instead?
用户续费成功后，新流量与旧流量没有叠加，而是新的流量替换了旧的，有效时长倒是叠加了

### What is your config in detail (with all sensitive info masked)?
官方推介的配置没改

**Comment by gyteng** [comment]
是这么设计的，不会叠加，但过了一个周期后统计数字会清零
