### ISSUE TITLE
免费帐户发送验证码失败

### ISSUE THREAD

**Issue by tututo** [shadowsocks/shadowsocks-manager#186]
换过系统换过VPS，都是出现一样的问题，实在找不到解决方法了，特来问下，是那里出了问题，正常帐户没有问题。感谢！
![20170413193500.png](https://ooo.0o0.ooo/2017/04/13/58ef62a65b313.png)
![20170413193431.png](https://ooo.0o0.ooo/2017/04/13/58ef62a6c9a4a.png)

**Comment by gyteng** [comment]
请提供版本号等信息

tututo <notifications@github.com>于2017年4月13日 周四19:38写道：

**Comment by tututo** [comment]
我是从0.5.6*开始折腾，到现在0.5.79都试过了，就是同样这个问题，一开始我以为可能是BUG，就等版本更新，然后一直试都这样，所以才来问的，正常帐户没什么问题。

**Comment by gyteng** [comment]
帐户是不分免费付费的，你的意思是新用户无法注册吗

tututo <notifications@github.com>于2017年4月13日 周四19:44写道：

**Comment by tututo** [comment]
不是的，是正常要验证码注册的，可以发送验证码正常注册成功，但是免费帐户同样的邮箱配置就发送不成功

**Comment by gyteng** [comment]
哦，你是指freeaccount这个插件是吧

tututo <notifications@github.com>于2017年4月13日 周四19:50写道：

**Comment by tututo** [comment]
嗯，是的哈

**Comment by tututo** [comment]
点击发送后，出现403，/email  是我配置的问题？
![20170413195731.png](https://ooo.0o0.ooo/2017/04/13/58ef67e8a2663.png)

**Comment by gyteng** [comment]
估计是从某个版本开始对webgui的相关插件改动影响到它了，在我没修复之前建议你先退回到之前正常使用的那个版本

2017-04-13 19:53 GMT+08:00 tututo <notifications@github.com>:

**Comment by tututo** [comment]
![20170413195731.png](https://ooo.0o0.ooo/2017/04/13/58ef68e29aad0.png)
你看这个对分析有没帮助。。。
还有。。。
我就没正常使用过这个插件。。。
没人反馈，我一直以为可能是我自己配置的问题。。。
