### ISSUE TITLE
node server.js error raven@1.2.1 alert: failed to send exception to sentry: HTTP Error (401): Invalid api key

### ISSUE THREAD

**Issue by viewplatgh** [shadowsocks/shadowsocks-manager#187]
### What version of shadowsocks-manager are you using?
b509cb8dce20692980ae6055a753683b794df8bd

### What operating system are you using?
MacOS Sierra 10.12.3 

### What version of Node.js are you using?
v6.9.2

### What did you do?
run `node server.js`

### What did you expect to see?
node launch successfully

### What did you see instead?
error
`raven@1.2.1 alert: failed to send exception to sentry: HTTP Error (401): Invalid api key`

### What is your config in detail (with all sensitive info masked)?
no idea

**Comment by gyteng** [comment]
Please ignore this error message, It's a tool for bug trace
