### ISSUE TITLE
运行`node server.js`后，访问哪个端口看web管理界面呢？6002？

### ISSUE THREAD

**Issue by viewplatgh** [shadowsocks/shadowsocks-manager#188]
请把端口号相关信息写到readme中好吗？
运行`node server.js`后
尝试访问`localhost:6002`，卡住，进入永久等待。

**Comment by gyteng** [comment]
运行的时候加上 --debug 参数，日志里有写

2017-04-14 9:51 GMT+08:00 Rob Lao <notifications@github.com>:
