### ISSUE TITLE
能否开一个gitter.im讨论组

### ISSUE THREAD

**Issue by viewplatgh** [shadowsocks/shadowsocks-manager#189]
请开一个gitter.im讨论组 方便交流讨论
https://gitter.im/#createcommunity

**Comment by gyteng** [comment]
我之前没用过这个东西，就相当于一个聊天的群组吗？

**Comment by viewplatgh** [comment]
是的，讨论组，很多github项目用

**Comment by gyteng** [comment]
它有什么功能是跟github结合的吗？感觉不如用telegram方便啊

**Comment by tututo** [comment]
@gyteng 有telegram组吗？大家交流方便点

**Comment by gyteng** [comment]
@tututo 本来是打算建个telegram组的，但我发现需要邀请一个有手机号的朋友才能建立，而我的tg好友全都没有

**Comment by viewplatgh** [comment]
好像开好了，谢谢啦

**Comment by tututo** [comment]
@gyteng  来来来，加我，咱俩组一个😂https://t.me/daykor

**Comment by tututo** [comment]
@gyteng  来来来，加我，咱俩组一个😂https://t.me/daykor

**Comment by pbwind** [comment]
@Gu 电脑群组有弄好吗？如果没有可以加我。我有手机号号

Gu <notifications@github.com>于2017年4月14日周五 下午6:37写道：

**Comment by gyteng** [comment]
https://t.me/joinchat/AAAAAAocQVv8fK_K6JDBgw
