### ISSUE TITLE
图片均无法显示

### ISSUE THREAD

**Issue by fiepi** [shadowsocks/shadowsocks-manager#19]
系统: archlinux ，所有软件包均是通过包管理安装的，arch的软件源软件版本非常新，应该都是最新的。
参考了ubuntu的安装过程，安装了对应依赖，一切顺利，但网页的图片资源均无法加载显示。
![screenshot_20160622-100444 01](https://cloud.githubusercontent.com/assets/15153999/16252521/8ecbe132-37f4-11e6-8dd9-45ec6a204ce3.png)

**Comment by gyteng** [comment]
你是不是在 bower install 这一步按了 ctrl + C 取消？

**Comment by gyteng** [comment]
图标对应的是 material-design-icons 这个包，请检查项目路径的 bower_components 文件夹下是否有 material-design-icons 文件夹，如果没有，请再次执行 bower install, 如果有，请尝试删除这个文件夹后执行 bower install

**Comment by fiepi** [comment]
重新 bower install 了一遍，图标依旧不显示
![result-2016-06-22-17-39-56](https://cloud.githubusercontent.com/assets/15153999/16262080/caba9582-3833-11e6-874f-b609acc2e505.png)

**Comment by fiepi** [comment]
可能是中间的angular的版本不对

**Comment by gyteng** [comment]
angular 版本用 1.5.7 的，请运行后打开浏览器的调试工具看具体哪个地方出错。

**Comment by fiepi** [comment]
不少类似这样的错误:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://xxx.com:1666/libs/material-design-icons/iconfont/MaterialIcons-Regular.woff Failed to load resource: the server responded with a status of 404 (Not Found)
http://xxx.com:1666/libs/material-design-icons/iconfont/MaterialIcons-Regular.ttf Failed to load resource: the server responded with a status of 404 (Not  Found)
```

```
$ls  bower_components/material-design-icons
LICENSE  README.md  action  alert  av  bower.json  communication  content  device
```

**Comment by gyteng** [comment]
看对应的路径是否有那个404的文件
2016年6月22日 下午6:46，"妹妹你好胸" <notifications@github.com>写道：

**Comment by fiepi** [comment]
material-design-icons 目录下边并没有 iconfont 这个目录。。
比如执行:
`$ find ./ -name MaterialIcons-Regular.woff` 
也找不到相关文件。

**Comment by gyteng** [comment]
请重新安装这个包
