### ISSUE TITLE
新开了Telegram讨论组

### ISSUE THREAD

**Issue by gyteng** [shadowsocks/shadowsocks-manager#192]
今天新开了Telegram讨论组，如果遇到任何问题请加入后讨论：

[https://t.me/ssmgr](https://t.me/ssmgr)

**Comment by Caibiy** [comment]
请问什么时候写一些那个文档 谢谢作者了！

**Comment by Caibiy** [comment]
请问什么时候写一下那个文档 谢谢作者了！

**Comment by k1er** [comment]
@gyteng Telegram 收不到验证码，你们是怎么用的
