### ISSUE TITLE
续费后只叠加使用时间不叠加使用流量吗?

### ISSUE THREAD

**Issue by Joehaivo** [shadowsocks/shadowsocks-manager#193]
我试用的是wall.gyteng.com

**Comment by gyteng** [comment]
是的，注意有个周期，过了那个周期流量会清零重新开始计算

2017-04-16 13:37 GMT+08:00 Joehaivo <notifications@github.com>:

**Comment by Joehaivo** [comment]
我觉得可以改一下,因为我就是因为流量用完了而周期还没到,而我在这段时间是没法使用的

**Comment by reversengineer** [comment]
I feel that this is unexpected behavior, when a user renews the account, they would expect to have access to the traffic immediately, instead of waiting for the time period to end. This could especially be a problem for hourly users.
