### ISSUE TITLE
注册用户激活后总是显示加载数据错误

### ISSUE THREAD

**Issue by qiwihui** [shadowsocks/shadowsocks-manager#20]
正常注册用户激活后，用户登录时显示500数据加载错误，接口`/api/user/userinfo`返回500，请问这是怎么回事呢？

<img width="1634" alt="screen shot 2016-06-22 at 2 38 49 pm" src="https://cloud.githubusercontent.com/assets/3297411/16256809/321dc796-3887-11e6-8c39-b1cd02e06ad5.png">

**Comment by gyteng** [comment]
这是一个bug，我遇到过两次，但后来一直难以重现，因此目前尚未解决。
重新登陆就好了。

2016-06-22 14:42 GMT+08:00 qiwihui <notifications@github.com>:

**Comment by qiwihui** [comment]
这个问题会导致一直卡在这个界面，点击确定后页面刷新又重新请求，无法操作其他按钮。
有没有直接接口退出的方法？

**Comment by gyteng** [comment]
目前有个比较简单粗暴的解决方法，是直接把数据库的sessions表清空

**Comment by gyteng** [comment]
似乎已经解决了这个bug，如果你更新后还遇到这个问题，请麻烦告诉我。

**Comment by qiwihui** [comment]
这个问题应该是我的mongodb的版本太低了，但我升到3.2之后这个问题就解决了。
