### ISSUE TITLE
Attempting to control ss-manager from python

### ISSUE THREAD

**Issue by virgil** [shadowsocks/shadowsocks-manager#200]
### What version of shadowsocks-manager are you using?

Using shadowsocks-libev 3.0.5.

### What operating system are you using?
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
### What version of Node.js are you using?

```
root@doethvpn:~# nodejs --version
v7.9.0
```

### What did you do?
I am running ss-manager with a unix socket, and the standard `nc -Uu` works perfectly.  I am attempting to control ss-manager using a python script the same way I can manually control ss-manager using `nc -Uu`.

I attach my current python code:

```
class ShadowSocksManager():

	def __init__(self, domain_socket):

		self.SOCKET_BUFFER_SIZE = 4096
		self.sock = None

		self.sock_address = domain_socket

		if not os.path.exists( domain_socket ):
			raise ValueError( "socket %s did not exist." % self.sock_address )

		# Datagram (udp) socket
		try :
			self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
			print( 'Socket created.' )

		except socket.error as err:
			print('Failed to create socket. Error Code : ' + str(err[0]) + ' Message ' + err[1] )
			sys.exit()

		self.sock.connect( self.sock_address )
		print("Connected to socket", self.sock_address, '.' )


	def mylist(self):
		'''returns the list of all ports and their bandwidth usage.'''

		#sig_ping = bytes('ping\n', 'utf-8')

		self.sock.sendto( b'ping', self.sock_address )
		self.sock.sendto( b'ping\n', self.sock_address )

		return self.myrecv()


	def myrecv(self):
		data = self.sock.recvfrom( self.SOCKET_BUFFER_SIZE )
		z = repr(data)

		print("got back:", z )
		return z




if __name__ == '__main__':

	DOMAIN_SOCKET = '/tmp/manager.sock'

	SS = ShadowSocksManager( DOMAIN_SOCKET )

	print("We connected.")
	print("doing ss.mylist()")
	pprint( SS.mylist() )

```

### What did you expect to see?

When running ss.mylist() I expect to see an (empty) list of all ports and how many bytes have gone through each---identical to what happens when I type `ping` into netcat.  However, I get an error message instead, and after a day or fiddling with various ways of sending `ping` across the socket I am resorting to here.  I'm confident it's not a bug, I'm just doing something stupid and I'm posting here so others can learn from my error.

### What did you see instead?

I get the following output on the ss-manager screen,
```
root@doethvpn:~# ./run_ss-manager.sh 
-- config file: /root/cfg/ss_server.json...
- Opening manager interface on /tmp/manager.sock
 2017-04-26 09:13:00 INFO: using tcp fast open
 2017-04-26 09:13:00 INFO: running from root user
 2017-04-26 09:13:16 ERROR: ping_sendto: Transport endpoint is not connected
 2017-04-26 09:13:16 ERROR: ping_sendto: Transport endpoint is not connected
```

### What is your config in detail (with all sensitive info masked)?

```
$ cat /root/cfg/ss_server.json
{
 "method": "aes-128-cfb",
 "timeout": 600,
 "fast_open": true,
 "mode": "tcp_and_udp"
}
```

**Comment by gyteng** [comment]
You have to post the issue in [this project](https://github.com/shadowsocks/shadowsocks-libev).
