### ISSUE TITLE
关于flowSaver历史流量信息的问题

### ISSUE THREAD

**Issue by mnzn** [shadowsocks/shadowsocks-manager#201]
账户到期后、自动或手动删除后请将flowSaver表中该账户的流量信息删除；

**Comment by gyteng** [comment]
这个问题我之前有考虑过，如果删除的话，在“服务器”菜单统计的总流量就不准确了

2017-04-27 13:38 GMT+08:00 mnzn <notifications@github.com>:

**Comment by mnzn** [comment]
哦，那就把1个月以前的流量信息删除吧，这些信息应该没用了吧

**Comment by gyteng** [comment]
嗯，这个问题后面会考虑，目前我记得好像删除服务器的时候会删除flowSaver表相应的条目

**Comment by mnzn** [comment]
好，我先关了
