### ISSUE TITLE
How to disable service worker when using http?

### ISSUE THREAD

**Issue by qwIvan** [shadowsocks/shadowsocks-manager#205]

**Comment by gyteng** [comment]
service worker can't run in http, you don't have to disable it.

**Comment by qwIvan** [comment]
![image](https://cloud.githubusercontent.com/assets/7613160/25774303/4511185c-32bf-11e7-8f37-c64aa15af11d.png)

**Comment by qwIvan** [comment]
I can't login in http when service worker is enabled.

**Comment by qwIvan** [comment]
我切换到chrome的访客模式下，service worker是关闭的，我就可以登录成功。我切换到firefox下，service worker关闭，我也可以登录成功。

**Comment by gyteng** [comment]
try to use neither localhost nor 127.0.0.1
