### ISSUE TITLE
用户登陆问题

### ISSUE THREAD

**Issue by mnzn** [shadowsocks/shadowsocks-manager#206]
各版本都偶有出现：输入用户名密码点登陆后圆圈一直旋转不消失，不会自动跳转到登陆成功界面户界面。
必须强制刷新一下。不知有人遇到过吗，出现的概率极小，但在一台新机器上（以前从没登陆过此账户）登陆又比较容易出现。还有顺便问一下这样的问题该怎么调试？
![default](https://cloud.githubusercontent.com/assets/3492200/25940574/231ea266-3669-11e7-8afa-88555a8fd65a.png)

**Comment by mnzn** [comment]
webgui.log里面看到登陆的POST成功了，然后就什么都没有了
[2017-05-11 16:06:35.197] [INFO] express - [undefined] POST 200 9ms /api/home/login

**Comment by gyteng** [comment]
能具体说说该如何重现这个问题吗？

**Comment by zeeqy** [comment]
@mnzn 出现过，虽然不知道怎么重现....囧
在 Windows 和 Mac 上都出现过。其实已经登录了，但是圈一直转，刷新一下就进去了。

版本号 0.10.17
