### ISSUE TITLE
好吧一个很白的问题

### ISSUE THREAD

**Issue by wjz2001** [shadowsocks/shadowsocks-manager#21]
请问shadowsocks-manager的安卓端在哪里下载？？网页版网址是什么？

**Comment by gyteng** [comment]
请自己搭建在服务器上。

**Comment by wjz2001** [comment]
可是我已经搭建好了

**Comment by gyteng** [comment]
根据 config.js 里的 express.http 字段来访问

**Comment by wjz2001** [comment]
明白了，谢谢
如果我需要更新就重新执行一遍安装就可以了是吗？
