### ISSUE TITLE
PC端样式(流量趋势图和饼图重叠)

### ISSUE THREAD

**Issue by pyyzcwg2833** [shadowsocks/shadowsocks-manager#210]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.6.23

### What operating system are you using?
CentOS7.3 64bit

### What version of Node.js are you using?
6.10.2

### What did you do?
多用户管理，部署

### What did you expect to see?
页面整齐

### What did you see instead?
PC端，流量趋势图和饼图重叠

### What is your config in detail (with all sensitive info masked)?
nothing
![2017-05-20 6 47 48](https://cloud.githubusercontent.com/assets/24390069/26275160/de6f674c-3d8c-11e7-8949-b95565a81f9b.png)

**Comment by gyteng** [comment]
这个问题一开始我就知道，因为对CSS不太熟悉，或许在不久的将来会解决

2017-05-20 18:48 GMT+08:00 pyyzcwg2833 <notifications@github.com>:
