### ISSUE TITLE
支付宝问题请教-验签出错, 未配置对应签名算法的公钥或者证书

### ISSUE THREAD

**Issue by junhuoku007** [shadowsocks/shadowsocks-manager#215]
### What version of shadowsocks-manager are you using?

0.6.11

### What did you do?

已按 Wiki 中的要求开通支付宝商家收款码，但是在签约管理中没有找到 Wiki 中提及的 RSA(SHA2) 密钥，倒是有 RSA(SHA1) 密钥，因此我是在 RSA(SHA1) 密钥这里设置的。

![](https://ws4.sinaimg.cn/large/006tKfTcgy1ffvbi8oe0vj31gk0x6q41.jpg)

然后把 appid 填好，密钥是用支付宝RAS密钥生成器SHAwithRSA1024_V1.0生成的，把生成的 rsa_private_key.pem 中的 private key 填到 merchantPrivateKey 项，将“查看支付宝公钥”内容填到 alipayPublicKey 项

![](https://ws2.sinaimg.cn/large/006tKfTcgy1ffvbp3v9k8j30xc0nswev.jpg)

### What did you see instead?

```shell
[2017-05-23 03:04:51.308] [INFO] system - System start.
{ message: '支付宝签名验证失败',
  info:
   { alipay_trade_precreate_response:
      { code: '40003',
        msg: 'Insufficient Conditions',
        sub_code: 'isv.missing-signature-config',
        sub_msg: '验签出错, 未配置对应签名算法的公钥或者证书' },
     sign: 'WpGe9b17TsXk0mjs******+WjdW/CQF2Fcg==' } }
[2017-05-23 03:08:59.555] [ERROR] express - [undefined] POST 403 794ms /api/user/order/qrcode
```

### What is your config in detail (with all sensitive info masked)?

```shell
alipay:
    use: true
    appid: 20170523*****
    notifyUrl: ''
    merchantPrivateKey: "MIICXAIBAAKBgQDSZlhhEW4Z*****dKioeEfSYBzyfYgwHZWEAc="
    alipayPublicKey: "MIGfMA0GCSqGSIb3DQEBAQUA******3/cNMW0QIDAQAB"
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
```

**Comment by gyteng** [comment]
错误信息很明显：未配置对应签名算法(rsa2)的公钥或者证书

**Comment by junhuoku007** [comment]
可以那两个密钥也填了，是不是我的签名工具用错了

**Comment by junhuoku007** [comment]
我支付宝后台没有 Wiki 中提及的 RSA(SHA2) ，这个应该没关系吧

**Comment by junhuoku007** [comment]
库中 https://github.com/Srar/AlipayF2F/blob/master/lib/aop.js#L54 一行指定的签名类型是 RSA2， AlipayF2F 库里面的 RSA2，跟 shadowsocks-manager Wiki 里提到 RSA(SHA2) ，还有签约管理后台只显示到的 RSA(SHA1) ，这三个是不是同一个加密方式，我没明白，最好能在 Wiki 中说明一下

**Comment by gyteng** [comment]
wiki里已经写了用rsa2，你的图上也表明了你没设置rsa2的密钥
