### ISSUE TITLE
只支持shadowsocks原版？shadowsocksR不支持？

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/shadowsocks-manager#219]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
还没用

### What operating system are you using?
debian7

### What version of Node.js are you using?
还没用

**Comment by gyteng** [comment]
不支持
