### ISSUE TITLE
安装ssmgr的出错信息

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/shadowsocks-manager#220]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
newest

### What operating system are you using?
debian 8

### What version of Node.js are you using?
6.10.3

### What did you do?
npm i -g shadowsocks-manager

### What did you expect to see?
安装时候的提示和错误信息需要解决吗？

**Comment by hdstar2009** [comment]
补：
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/shadowsocks-manager/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by gyteng** [comment]
WARN 类型的信息不用管它

2017-05-27 15:31 GMT+08:00 hdstar2009 <notifications@github.com>:

**Comment by hdstar2009** [comment]
上面的信息都不用管？我现在装个node7.x看下会不会有其他警告信息？
7.x我看wiki是说兼容对吧？

**Comment by gyteng** [comment]
理论上6以上都可以的

hdstar2009 <notifications@github.com>于2017年5月27日 周六15:54写道：

**Comment by hdstar2009** [comment]
汇报下，在node7.10.0x外安装ssmgr是一样的提示信息。
所以我想是因为ssmgr自身代码的关系，和node系统无关对吧
