### ISSUE TITLE
注册用户获得的账号ip是0.0.0.0

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/shadowsocks-manager#222]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
python版
### What operating system are you using?
debian8

### What version of Node.js are you using?
7.10.0

### What did you expect to see?
分配的账号ip应该是外网ip才对

### What did you see instead?
分配的账号ip是显示0.0.0.0，形如：0.0.0.0：50001 这样

### What is your config in detail (with all sensitive info masked)?
ss.yml的文件内容：
type: s
empty: false
shadowsocks:
  address: 127.0.0.1:8000
manager:
  address: 0.0.0.0:8001
  password: '123456'
db: 'ss.sqlite'

想问的是ss.yml文件的manager下面的address：0.0.0.0这个应该是和webgui通讯用的？

webgui.yml文件开头部分：
type: m
empty: false

manager:
  address: 0.0.0.0.:8001
  password: '123456'

因为我测试将webgui和ss服务端在一个vps上，所以webgui.yml我把address也设置为了0.0.0.0（我原本以为这个0.0.0.0应该代表本机的内外网ip地址）。是否因为这里没有设置为外网ip而导致生成的账号ip是0.0.0.0？

意识到这个问题后，我改了webgui.yml中的ip为外网ip，但是我发现重新注册新的用户还是分配的0.0.0.0开头的账号。应该怎么改正确？

**Comment by gyteng** [comment]
请在web界面的“服务器”项目里更改
