### ISSUE TITLE
在 Android 的 Chrome 浏览器上，无法编辑公告

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/shadowsocks-manager#223]
### What version of shadowsocks-manager are you using?
0.6.30

### What did you see instead?
点击公告文字后就自动全选，无法取消，也无法编辑。

**Comment by gyteng** [comment]
目前我还没找到原因

**Comment by pyyzcwg2833** [comment]
同样的环境我是可以的，可能是你的手机或者系统原因

**Comment by gyteng** [comment]
这似乎是angular-material的textarea控件的bug，目前还是没有找到解决办法。

**Comment by gyteng** [comment]
似乎 `0.6.54` 已经解决问题
