### ISSUE TITLE
从0.5.x升级到0.6.x之后，流量统计无效了

### ISSUE THREAD

**Issue by zhfreal** [shadowsocks/shadowsocks-manager#230]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.6.46

### What operating system are you using?
Ubuntu 16.04 x64

### What version of Node.js are you using?
7.10.0

### What did you do?
upgrade from 0.5.x to 0.6.46

### What did you expect to see?
work normally

### What did you see instead?
flow stastics is not working

**Comment by gyteng** [comment]
能提供一些更详细的信息吗，比如哪个地方无效？

**Comment by zhfreal** [comment]
@gyteng ，账号里的流量、最近连接时间和下面的图统计，都是空的。昨天升级前都有值。刚用该账号试了，产生了十几m流量，但其统计还是为0，最近连接时间也不对。

**Comment by zhfreal** [comment]
最近连接时间是升级前的值

**Comment by zhfreal** [comment]
而账号流量都是0

**Comment by gyteng** [comment]
贴日志里的错误信息

**Comment by gyteng** [comment]
还有你数据库当前的表结构

**Comment by zhfreal** [comment]
用的是sqlite, 你需要看什么日志，日志有点多

**Comment by zhfreal** [comment]
robin@zhfreal:~/.ssmgr$ find logs/ -type "f" -name "*.log" | xargs grep ERROR
logs/webgui/express.log:[2017-06-13 13:35:14.052] [ERROR] express - [45.77.16.223] GET 401 36ms /api/admin/user?page=1&pageSize=30&sort=id_asc
logs/webgui/express.log:[2017-06-13 13:35:14.078] [ERROR] express - [45.77.16.223] GET 401 52ms /api/admin/order/recentOrder
logs/webgui/express.log:[2017-06-13 13:35:14.085] [ERROR] express - [45.77.16.223] GET 401 53ms /api/admin/user/recentSignUp
logs/webgui/express.log:[2017-06-13 13:35:14.093] [ERROR] express - [45.77.16.223] GET 401 59ms /api/admin/user/recentLogin
logs/webgui/system.log:[2017-06-12 09:59:10.058] [ERROR] system - { Error: SQLITE_ERROR: index index already exists errno: 1, code: 'SQLITE_ERROR' }

**Comment by zhfreal** [comment]
ssm的sqlite3数据库

table|account|account|2|CREATE TABLE "account" ("port" integer, "password" varchar(255), primary key ("port"))
table|command|command|3|CREATE TABLE "command" ("code" varchar(255), "time" bigint, primary key ("code"))
table|flow|flow|5|CREATE TABLE "flow" ("port" integer, "flow" integer, "time" bigint)

**Comment by zhfreal** [comment]
webgui的sqlite3数据库

table|account|account|2|CREATE TABLE "account" ("port" integer, "password" varchar(255), primary key ("port"))
table|command|command|3|CREATE TABLE "command" ("code" varchar(255), "time" bigint, primary key ("code"))
table|flow|flow|5|CREATE TABLE "flow" ("port" integer, "flow" integer, "time" bigint)
table|saveFlow|saveFlow|6|CREATE TABLE "saveFlow" ("id" integer, "port" integer, "flow" integer, "time" bigint)
table|server|server|7|CREATE TABLE "server" ("id" integer not null primary key autoincrement, "name" varchar(255), "host" varchar(255), "port" integer, "password" varchar(255), "method" varchar(255) default 'aes-256-cfb', "scale" float default '1')
table|sqlite_sequence|sqlite_sequence|8|CREATE TABLE sqlite_sequence(name,seq)
table|email|email|9|CREATE TABLE "email" ("to" varchar(255), "subject" varchar(255), "text" varchar(255), "type" varchar(255), "remark" varchar(255), "ip" varchar(255), "session" varchar(255), "time" bigint)
table|user|user|10|CREATE TABLE "user" ("id" integer not null primary key autoincrement, "username" varchar(255), "email" varchar(255), "telegram" varchar(255), "password" varchar(255), "type" varchar(255), "createTime" bigint, "lastLogin" bigint, "resetPasswordId" varchar(255), "resetPasswordTime" bigint)
table|account_plugin|account_plugin|12|CREATE TABLE "account_plugin" ("id" integer not null primary key autoincrement, "type" integer, "userId" integer, "server" varchar(255), "port" integer, "password" varchar(255), "data" varchar(255), "status" integer, "autoRemove" integer default '0')
table|push|push|14|CREATE TABLE "push" ("id" integer not null primary key autoincrement, "endpoint" varchar(255), "auth" varchar(255), "p256dh" varchar(255))
table|webguiSetting|webguiSetting|16|CREATE TABLE "webguiSetting" ("id" integer not null primary key autoincrement, "key" varchar(255), "value" varchar(255))
table|alipay|alipay|18|CREATE TABLE "alipay" ("id" integer not null primary key autoincrement, "orderId" varchar(255), "orderType" integer default '3', "amount" varchar(255), "user" integer, "account" integer, "qrcode" varchar(255), "status" varchar(255), "alipayData" varchar(255), "createTime" bigint, "expireTime" bigint)
table|sessions|sessions|20|CREATE TABLE "sessions" ("sid" varchar(255), "sess" text not null, "expired" datetime not null, primary key ("sid"))
table|saveFlow5min|saveFlow5min|260|CREATE TABLE "saveFlow5min" ("id" integer, "port" integer, "flow" integer, "time" bigint)
table|saveFlowDay|saveFlowDay|282|CREATE TABLE "saveFlowDay" ("id" integer, "port" integer, "flow" integer, "time" bigint)
table|saveFlowHour|saveFlowHour|283|CREATE TABLE "saveFlowHour" ("id" integer, "port" integer, "flow" integer, "time" bigint)
table|notice|notice|284|CREATE TABLE "notice" ("id" integer not null primary key autoincrement, "title" varchar(255), "content" varchar(16384), "time" bigint)

**Comment by zhfreal** [comment]
@gyteng , 服务器的流量统计也全是0，ss.sqlite3的flow表还有新数据，最新一条时间是1497505920007，应该是今天的。但webui上帐号和服务器的流量统计都没有，请教下怎么解决？

**Comment by zhfreal** [comment]
原数据库文件备份了下，重新初始化数据库后可以统计流量。之前的流量统计数据没有管了，算了懒得折腾。
