### ISSUE TITLE
缩减Docker image大小的建议

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#231]
目前readme中给出的dockerfile使用了ubuntu作为基础镜像，并且使用apt安装了curl git等包并且没有做清理，这样导致生成的image会比较大，对于某些渣渣vps(硬盘巨小)来说不太友好。因此建议：
1.  直接使用官方npm/alpine之类的小image作为基础镜像 步骤官方也有介绍：https://nodejs.org/en/docs/guides/nodejs-docker-webapp/ 
2. 把shadowsocks-libev也做进docker image中是否不大合适，ss-libev和ssmgr保持独立性，使用不同镜像，用不同容器运行是否更合适？而且，ss-libev也有个现成的Dockerfile：https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/Dockerfile
这个也使用alpine作为基础镜像，并做了清理，体积不大。

Docker本人也是初学者 也不清楚这些建议是否合理

**Comment by gyteng** [comment]
我对docker不是很了解，所以就随便搞了个能用的镜像。

**Comment by liukangxu** [comment]
可以试试 https://hub.docker.com/r/liukangxu/ssmgr/，基于 alpine，集成了 ss-libev 和 ssmgr

**Comment by cokebar** [comment]
@liukangxu 感谢推荐 试试去

**Comment by gyteng** [comment]
@liukangxu 话说改用alpine的话，相对于用ubuntu，除了体积上的优势以外，有没有什么性能上或者资源占用上的提升呢？

**Comment by liukangxu** [comment]
> 1. 下载速度加快。
> 2. 安全性提高。
> 3. 主机之间的切换更方便。
> 4. 不用再占用那么多磁盘空间。

via http://dockone.io/article/1014

**Comment by damonYuan** [comment]
@cokebar 我刚刚提了一个pr, 但是因为没有测试过alpine所以还是基于ubuntu，你可以帮忙改进一下吗
