### ISSUE TITLE
支付宝付款后收到两个订单支付成功的提示

### ISSUE THREAD

**Issue by kesuki** [shadowsocks/shadowsocks-manager#232]
### What version of shadowsocks-manager are you using?
0.6.46

### What operating system are you using?
Linux azure 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### What version of Node.js are you using?
v6.10.3

### What did you do?
创建订单进行支付宝付款后，连续开通两个服务

### What did you expect to see?
只开通一个服务

### What did you see instead?
[2017-06-14 12:43:00.257] [INFO] alipay - 订单支付成功: [20170614124112864429][2][account: null]
[2017-06-14 12:43:00.478] [INFO] alipay - 订单支付成功: [20170614124112864429][2][account: null]

**Comment by gyteng** [comment]
能重现吗？

**Comment by kesuki** [comment]
订单有大概50%的概率出现这样的情况

**Comment by gyteng** [comment]
目前只有你反馈这个问题，我也无法重现，日志里边有没有报错的信息？

**Comment by kesuki** [comment]
不知道是不是服务器通信链路差造成的，然后导致支付宝发送了两次回调，但是程序是否应该适当增加容错的逻辑。

**Comment by gyteng** [comment]
如果一个订单已经完成了，再次收到完成的通知是不会做任何操作的，估计是两次收到的间隔很短，这里估计我要加个锁之类的

2017-06-16 11:09 GMT+08:00 kesuki <notifications@github.com>:

**Comment by beiyouren101** [comment]
我测试程序的时候遇到同样的问题，选择一天的流量套餐用支付宝付款后，提示大约2分钟内会生成订单，这个时候如果再选择一个月的流量套餐用支付宝付款，就会开通另外一个服务。最终一个订单使用端口50013端口，另一个订单使用50025端口服务。
