### ISSUE TITLE
关于webgui和alipay插件的问题

### ISSUE THREAD

**Issue by hurui200320** [shadowsocks/shadowsocks-manager#234]
### What version of shadowsocks-manager are you using?
最新版（2017.6.22）

### What operating system are you using?
Debian8

### What version of Node.js are you using?
6.11.0

### What did you do?
I used the webgui plugin

### What did you expect to see?
If I can modify the website view and use another way to purchase.

### What did you see instead?
I don't know how to edit web view and i cannot apply alipay's API.

### What is your config in detail (with all sensitive info masked)?
Just follow the wiki.

我想请教一下关于webgui插件和alipay插件的事。首先是有没有办法修改webgui的网页，我找到了相关的文件并修改了一些内容，之后重启了ssmgr，但是网页好像没有任何变化。所以我想知道如何修改未登录时的首页。
然后是关于支付宝插件的事情，我尝试申请当面付，但是支付宝说需要工商局的营业执照，可是我没有，这该怎么办，有没有办法使用其他方法完成自动化的操作？

**Comment by gyteng** [comment]
1. 修改后需要用gulp重新打包，请参考`package.json`和`gulpfile.js`
2. 申请营业执照
