### ISSUE TITLE
系统错误 生成支付订单出错，请稍后再试

### ISSUE THREAD

**Issue by davymai** [shadowsocks/shadowsocks-manager#236]
webgui.yml 添加应用APPID,私钥，公钥后无法生成订单。

付款点击下一步就提示 “系统错误 生成支付订单出错，请稍后再试”

**Comment by gyteng** [comment]
请贴出详细的信息


davymai <notifications@github.com>于2017年7月6日 周四22:33写道：

**Comment by davymai** [comment]
alipay:
    use: true
    appid: 2017061907518530
    notifyUrl: 'http://ss.xmyunwei.com/api/user/alipay/callback'
    merchantPrivateKey: 'MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCCZ4Rw76rHI4s7555+4kJvhpeEwdale7L7V9C7u9jDy5xG52eraUhk6Qkc0y4LhCuiYruBL7mYOYhYtqaXUpdmb//yLsIXsWPaU9b4MK2MLcUHWN14S03aMIA/5qVw0XWF3vVAUbjF2hfK+P/5txUb7DUZI+jEEoWFU86UwVBbkOdHlI67EsNYOvaI9mmZE0lXohL2bhSBkndr
l7Ul3XmiWEuMVbjY5KdWiuYWfZxAtE09nxGfwqV+DNI9Vbp4uXxdv67xI7TxRyFzFN3VbJ4p9BW55OQACZFakmp+GgJ74MV7QHsCCcFyx3UW/P+2+JwNWZnL9plhCF1CfuMjuvVhAgMBAAECggEAaN+bkcANli2tsjWqL90DFPInNOs3FssOvDh5dCG0SHKdciB0LVR0lkMbwwTLSRO4i9XfehvJpPTQBJiQDa6seAOm0Txtd+R/q3w1rFBpogzFIg2Dv1TAfbL30WxKrRqm60zN7
DZM5UFqVSA/rLJi1Zv3cAqDDfzfSMSHpPZ7C8enuw1DfSTWF1pmSfQZYCsLrVgGZICsf/7pdjJERF2YN9ZxT6BoxGUBuf1dRcTPFPg+YD7BfLDRVOxGs2K/6XURVWcUA0dFYpkV3RU8LWk2wpq2zeagxzMC6imNCuuqjwu8RsWmsJK/Zapw0RnOVBWQanfwBFvGGCTDKcvhu1pyAQKBgQDeicYUhIiPWRGS/V+S2LOfsPbI5SyxGRfxncI9MfkbbiLU7q6z0N4bH0rmb79fTl+IZW
pdQ2WWaCqzfZQImOIvbyF27b++fwCMKdKDIM94Ssy2j1nlDVPNt2sG/FKPzjlIRTpdh5HNt40K0MCXV451Zf/rxT58HfA7ARbTOFONMQKBgQCWAzXLsb6Jngk8gvsBgyl8rA/cxQg5htQtocpr04PdGCuWi9j37sAKfxTo5SCyndb47hipJzmaDJ4mt2Uy8mF7aZ44vXYCMQrKJAJmMcGG6wb1RxiO/fXM0kGNljvgPffKXnR7RL3gID9i8TuukYpwU5ebGfbT0Byxc2QZ3uQfMQK
BgH2y4JnSSrh9nPmj+IofsUYwVRUgrd/Sxr2JWJ/sTEL8MNyJfVDAV9SGFm6XDEevIzMN5ciMOyN77zK3ahh5ErmsUgC1Ris53XtOXEQJEmdmCL/NtP82SfHW+rNVbuUfnSd/Qvp1ixvh498KDt7ta+BQHwBzx1mgJ4OMl/HyzO7hAoGAGpa3EkOO4hWAzZjppHr6/33/0cGak5eyQ+RJXJNA7A88qpJfApLutu2PZzg1c3NGhxishk7NhuB1p6cZ6M3NOXKe+K+cGwdWQj3frv1i
r+c4dIEFeVLKHmOl+tKGCljxco0LWE322aLdmUvoqChjwUUPug4AEcrxSwKI240GIgECgYAQNpgMXjQwXPUVfUq+MklLd3sqEg3ziZPIuujBUtCDl0b3qcIdOJElVLBYHWvzJF0zRohFquwlDETEKRy0OO2phhMOrOJQ2knRgozjseq9eJiQqf9Vk3ZtiNg22Pjnmq347Pp0p+lEF/KgzPqlbPjlB3KogO6MUFEFrISr0TU4nw=='
    alipayPublicKey: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk2LgTlNtYiw2gOMCvja8Y4CBQ8wWScxG7AukfFs7xbJ+BEpeUt3gZLATPPNkU/uciUiLtnv47cCikuJybNB475RlYLqLzbwsCrCR+1XmDXAzCB+xQA/FFT5/N4QNZ87MuOT/Wi0YFBhJJ4NHUTebDi54zfUQprqZc3CGglTYf77LTsBI5IUffpPGHtmKWkd211dZdHOoePEdX2i1bQEvKkE
EQMhl5Njjv0C9OeEL0pWxknD5Lrx0kYzRT5iuIPG3iuyq/UzWVa1oaCT/2BmLR7bp2mR+ZZsz/WGfUKPypTt9Ym3Jx90cYA/6OBXgDZWsv1bkOK/n/i5y5UN0twPx8QIDAQAB'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db:
  host: '127.0.0.1'
  user: 'ssmgr'
  password: 'LdG6gzG3OmXaLRyF'
  database: 'ssmgr'

**Comment by gyteng** [comment]
我的意思是说帖控制台的错误信息，别把你的privatekey贴出来了

davymai <notifications@github.com>于2017年7月6日 周四22:37写道：

**Comment by davymai** [comment]
控制台错误信息怎么查？ >_< 上面标题那句就是用户充值提示的信息

**Comment by davymai** [comment]
please help me

**Comment by davymai** [comment]
[2017-07-07 10:29:50.970] [INFO] express - [103.72.166.77] GET 200 22ms /api/user/server
[2017-07-07 10:29:51.600] [WARN] express - [103.72.166.77] GET 304 22ms /api/user/order/price
[2017-07-07 10:29:52.601] [ERROR] express - [103.72.166.77] POST 403 27ms /api/user/order/qrcode
[2017-07-07 10:30:29.582] [WARN] express - [103.72.166.77] GET 304 21ms /api/user/account
[2017-07-07 10:30:50.925] [WARN] express - [103.72.166.77] GET 304 15ms /api/user/account
[2017-07-07 10:31:29.583] [WARN] express - [103.72.166.77] GET 304 22ms /api/user/account
[2017-07-07 10:31:50.947] [WARN] express - [103.72.166.77] GET 304 36ms /api/user/account
