### ISSUE TITLE
plugins/webgui/libs/bundle.js 能否提供可以未混淆的版本？

### ISSUE THREAD

**Issue by beiyouren101** [shadowsocks/shadowsocks-manager#240]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?

0.7.5
### What operating system are you using?

window7 
### What version of Node.js are you using?

node 6.7
### What did you do?
修改bundle.js的部分逻辑

### What did you expect to see?
希望能够看到bundle.js未混淆的代码

**Comment by gyteng** [comment]
bundle.js 是用其它代码生成的，修改前端代码后运行 npm run build 可重新生成 bundle.js

2017-07-13 9:04 GMT+08:00 beiyouren101 <notifications@github.com>:
