### ISSUE TITLE
服务器合并流量数据有误

### ISSUE THREAD

**Issue by kesuki** [shadowsocks/shadowsocks-manager#243]
版本0.7.13，不勾选“合并多服务器流量统计”，流量统计正常，超出流量会自动关闭；

如勾选“合并多服务器流量统计”，流量统计数据没有叠加。

**Comment by gyteng** [comment]
勾选之后你尝试刷新页面没有？

2017-07-21 0:46 GMT+08:00 kesuki <notifications@github.com>:

**Comment by kesuki** [comment]
刷新过了，数据库已经保存进去。
我print一些log出来
[2017-07-21 11:43:28.923] [DEBUG] flowSaver - in getServerPortFlow! serverId: 1 port: 10906 isMultiServerFlow: undefined
看到在flow.js里面，有些调用getServerPortFlow函数时，isMultiServerFlow显示undefined

**Comment by gyteng** [comment]
你删除数据库的 `webguiSetting` 表然后重启 m 端重新配置试试

**Comment by kesuki** [comment]
数据库的格式都是对的
```
const getFlowFromSplitTime = async (serverId, port, start, end) => {
  let where = {};
  if(serverId) { where.id = serverId; }
  if(port) { where.port = port; }
  const time = splitTime(start, end);
  const sum = [];
  const getFlow = (tableName, startTime, endTime) => {
    return knex(tableName)
    .sum('flow as sumFlow')
    .groupBy('id')
    .select(['id'])
    .where(where)
    .whereBetween('time', [startTime, endTime - 1]).then(success => {
      if(success[0]) { return success[0].sumFlow; }
      return 0;
    });
```
我看了一下代码，把getFlowFromSplitTime函数里面的groupBy('id').select(['id'])改成groupBy('port').select(['port'])之后，传入serverid = 0，才会正确的合并多个服务器流量。但是传入port = 0，groupBy('id').select(['id'])的写法才能统计每个服务器的流量。

**Comment by gyteng** [comment]
我稍后重现一下此问题
