### ISSUE TITLE
合并所有服务器流量后流量超出问题

### ISSUE THREAD

**Issue by kesuki-recreated** [shadowsocks/shadowsocks-manager#244]
0.8.0版本，选择合并所有服务器流量后，流量超出不会自动关闭所有服务器的shadowsocks服务。

而是单个服务器的流量超出后，只关闭当前服务器的服务。

**Comment by gyteng** [comment]
超出不会自动关闭这个问题可能存在，我先自己复现一下。
单个服务器的流量超出后，只关闭当前服务器的服务，本身就这么设计的

**Comment by kesuki-recreated** [comment]
不知道我理解的对不对，逻辑是否这样的？

当勾选合并所有服务器流量，统计的流量超出就自动关闭所有服务器的服务。
当没有勾选合并所有服务器流量，某个服务器的流量超出后，就关闭相应服务器的服务。

**Comment by gyteng** [comment]
是这样的，你目前遇到的是第一种情况有bug对吧

在 2017年7月26日 下午2:30，kesuki-recreated <notifications@github.com>写道：

**Comment by kesuki-recreated** [comment]
嗯，是的，举例服务器限制100M流量，当服务器1用了50M流量，服务器2用了100M流量后，服务器2的服务器自动关闭，但是服务器1的服务没有关闭，导致最终用户可以使用150M流量。
