### ISSUE TITLE
是否有0元续费设置？且不开启alipay

### ISSUE THREAD

**Issue by Zing22** [shadowsocks/shadowsocks-manager#245]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
shadowsocks-manager 0.7.13

### What operating system are you using?
CentOS 7

### What version of Node.js are you using?
v6.11.1

### What is your config in detail (with all sensitive info masked)?
是否可以将续费价格设置为0，且不开启alipay，用户也可以点击续费？
目前看来如果没有开启alipay，续费按钮就会消失。而price设置为0之后，对应项也会消失。但由于某种原因，我不希望提供给用户无限期的账户，希望他们每个月手动点一下续费按钮，but for free。

Thanks!

**Comment by gyteng** [comment]
没有，你可以设置成1分钱续费嘛
