### ISSUE TITLE
关于某宝的问题

### ISSUE THREAD

**Issue by Moehentai2333** [shadowsocks/shadowsocks-manager#247]
### What version of shadowsocks-manager are you using?
最新版
### What operating system are you using?
centos 6.8 x64
### What version of Node.js are you using?
6.11.1
### What did you do?
测试某宝支付功能
### What is your config in detail (with all sensitive info masked)?
在测试某宝支付的时候出现了这个
[ERROR] express - [39m[xxx.xxx.xxx.xxx] POST 403 1401ms /api/user/order/qrcode
{ message: '验证支付宝签名时获取[sign]字段失败',
  info: 
   { alipay_trade_precreate_response: 
      { code: '40002',
        msg: 'Invalid Arguments',
        sub_code: 'isv.invalid-app-id',
        sub_msg: '无效的AppID参数' } } }
查找以前的提问的回答是appid没有更改,但是本鹅所有的都修改了也是这样,下面的notifyUrl,merchantPrivateKey,alipayPublicKey也修改了.
附上Nginx设置:
server {
    listen                     80 default_server;
    listen                     443 ssl http2 default_server;
    server_name                xxx;
    ssl_certificate            xxx;
    ssl_certificate_key       xxx;
    ssl_ciphers               xxx;
    ssl_prefer_server_ciphers  on;
    ssl_protocols              TLSv1 TLSv1.1 TLSv1.2;
    ssl_session_cache          shared:SSL:5m;
    ssl_session_timeout        5m;

    if ($scheme = http) {
        return  301 https://$host$request_uri;
    }

    location / {
        proxy_pass        http://127.0.0.1:8080;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  Host $http_host;
    }
}
某宝的配置:
 alipay:
    # 如果不使用支付宝，这段可以去掉
    use: true
    appid: 20888xxxxxxx9503
    notifyUrl: 'https://xxx.xxx/api/user/alipay/callback'   
    merchantPrivateKey: 'xxx'
    alipayPublicKey: 'xxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
db: 'webgui.sqlite'

**Comment by gyteng** [comment]
很可能是你的配置文件有缩进或者其它问题，另外配置文件里最好不要出现中文等非ascii字符

**Comment by Moehentai2333** [comment]
@gyteng 看了下某宝的账户中心,在PID和公钥管理中有三个选项:开放平台密钥,mapi网关产品密钥,和老版wap支付密钥,是不是只有开放平台密钥才可以啊

**Comment by gyteng** [comment]
非程序自身的bug请到tg群提出
