### ISSUE TITLE
NPM安装，ssmgr: command not found,无法使用

### ISSUE THREAD

**Issue by monsterszw** [shadowsocks/shadowsocks-manager#250]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.5.66

### What operating system are you using?
Ubuntu 17.04

### What version of Node.js are you using?
6.11.2

### What did you do?
npm i -g shadowsocks-manager

### What did you expect to see?
安装后可以正常使用

### What did you see instead?

 npm i -g shadowsocks-manager
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Killed        .....] \ extract:shadowsocks-manager: sill doParallel extract 608

**Comment by gyteng** [comment]
安装时候内存不够被杀死进程了

2017-08-03 10:03 GMT+08:00 Monster <notifications@github.com>:

**Comment by monsterszw** [comment]
谢谢您，我去看看服务器的配置
