### ISSUE TITLE
流量无法监测

### ISSUE THREAD

**Issue by ynhzzu** [shadowsocks/shadowsocks-manager#26]
ssserver --manager-address 127.0.0.1:6003 -c /root/shadowsocks.json -d start --pid-file /var/run/shadowsocks_manager.pid

这种方式启动多个端口的，但是依然没有流量监测，是哪里出现问题了吗？如何排查

**Comment by gyteng** [comment]
你先尝试换成`--manager-address 0.0.0.0:6003`能否监测流量

**Comment by ynhzzu** [comment]
我看之前的issue有反馈python版本的流量监测无法用，是不是还没有修复？
我的vps是digitalocean的centos7，python版本的ss，流量监测用的什么？能否查看进程看看是否流量监测启动了没？

**Comment by ynhzzu** [comment]
抱歉，我调好了。
我仔细看了wiki中的usage，服务器的端口要和manager-address端口一致，我重新调整了一下，是可以的。
再次非常抱歉，没有仔细研究使用文档
