### ISSUE TITLE
建议增加订单邮件通知

### ISSUE THREAD

**Issue by jxtxzzw** [shadowsocks/shadowsocks-manager#264]
建议增加订单的邮件通知，可以给用户发一封，也给管理员发一封。
内容不要多的，也不劳烦做CSS了，只一个纯文本的，包括交易账户、时间、订单号、金额等，发一下。

**Comment by gyteng** [comment]
这个功能需要等我把自定义邮件模板做好了才加上去

**Comment by zhangbolily** [comment]
我也很滋瓷这一个，现在我的邮件都是手动发的。幸苦开发者了

**Comment by gyteng** [comment]
fix in a11ff22937e9f6777d095332052529e646f88cf5
