### ISSUE TITLE
Failed running npm i

### ISSUE THREAD

**Issue by njinco** [shadowsocks/shadowsocks-manager#265]
### What version of shadowsocks-manager are you using?
version 2

### What operating system are you using?

ubuntu 17.04
### What version of Node.js are you using?
v4.7.2

### What did you do?
ran npm i after moving to the folder

### What did you expect to see?
install complete?

### What did you see instead?

root@skynet:~/shadowsocks-manager# npm i

> sqlite3@3.1.9 install /root/shadowsocks-manager/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: ‘node’: No such file or directory
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN shadowsocks-manager@0.8.40 license should be a valid SPDX license expression
npm ERR! Linux 4.10.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! sqlite3@3.1.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the sqlite3@3.1.9 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/shadowsocks-manager/npm-debug.log

### What is your config in detail (with all sensitive info masked)?
not have gotten to the part.

safe to assume install file is not compatible with ubuntu 17.04? if so which version of ubuntu is good?

**Comment by gyteng** [comment]
Please follow the README.md

1st, your node version is wrong.

**Comment by njinco** [comment]
sorry to ask this but how do i access the webgui after running node server.js?

**Comment by gyteng** [comment]
Please join telegram group and ask the questions.
