### ISSUE TITLE
运行npm i出错

### ISSUE THREAD

**Issue by zyh001** [shadowsocks/shadowsocks-manager#268]
错误信息：
root@theseus:~/shadowsocks-manager# npm i
> sqlite3@3.1.9 install /root/shadowsocks-manager/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build
sh: 1: node-pre-gyp: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN shadowsocks-manager@0.6.16 license should be a valid SPDX license expression
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/nodejs/node-v6.9.1-linux-x64/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! sqlite3@3.1.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the sqlite3@3.1.9 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /root/shadowsocks-manager/npm-debug.log
系统信息：Debian8 x86_64
----------
如果使用`npm i -g shadowsocks-manager`安装的话
运行`ssmgr`就会报错：
root@theseus:~# ssmgr
/usr/local/nodejs/node-v6.9.1-linux-x64/lib/node_modules/shadowsocks-manager/lib/
/usr/local/nodejs/node-v6.9.1-linux-x64/lib/node_modules/shadowsocks-manager/bin/ssmgr:7
process.chdir(lib);
        ^
Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (/usr/local/nodejs/node-v6.9.1-linux-x64/lib/node_modules/shadowsocks-manager/bin/ssmgr:7:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

麻烦解答一下

**Comment by gyteng** [comment]
我重现不出此问题，如果npm安装的时候报了sqlite错误，删除node_modules文件夹再多试几次就可以了

**Comment by zyh001** [comment]
我把node卸载重装了一遍，然后`npm i -g shadowsocks-manager`就没问题了

**Comment by wsepr** [comment]
我也出现了同样的错误，这是我安装的过程：
安装nodejs
cd /opt
wget --no-check-certificate https://nodejs.org/dist/v6.11.2/node-v6.11.2-linux-x86.tar.xz
yum -y install xz
unxz node-v6.11.2-linux-x86.tar.xz
tar -xf node-v6.11.2-linux-x86.tar
mv node-v6.11.2-linux-x86 nodejs
ln -s /opt/nodejs/bin/node /usr/local/bin
ln -s /opt/nodejs/bin/npm /usr/local/bin

安装ssmgr
npm i -g shadowsocks-manager

**Comment by xlliu** [comment]
我也出现了相同的问题
我是在 shadowsocks-manager 目录下 执行的：
sudo npm i
