### ISSUE TITLE
unable to delete a user from webgui

### ISSUE THREAD

**Issue by EtherealAO** [shadowsocks/shadowsocks-manager#269]
### What version of shadowsocks-manager are you using?

0.8.43
### What operating system are you using?
Centos 7
Linux version 4.12.4-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Thu Jul 27 20:03:28 EDT 2017
### What version of Node.js are you using?

1:6.11.1-1.el7
### What did you do?
try to delete a user from WebGUI
尝试从网页删除一名用户
### What did you see instead?
delete user fail
[2017-08-14 19:05:12.235] [ERROR] express - [undefined] DELETE 403 135ms /api/admin/user/3
### What is your config in detail (with all sensitive info masked)?
type: m
empty: false

manager:
  address: external IP:6002
  password: '123456'

all of plugins is enabled except alipay and paypal 启用了除支付宝和paypal外所有插件

db: 'webgui.sqlite'

**Comment by gyteng** [comment]
you can not delete a user before remove the accounts for the user

EtherealAO <notifications@github.com>于2017年8月14日 周一18:15写道：

**Comment by EtherealAO** [comment]
solved, thanks
