### ISSUE TITLE
Add a security warning in the web UI

### ISSUE THREAD

**Issue by madeye** [shadowsocks/shadowsocks-manager#27]
It's very dangerous to listen on `0.0.0.0` for manager API. Anyone can access your manager node from internet.

So, I suggest to add a security warning in the web UI when adding a remote node. Also, you can provide some tips like iptables rules to solve this problem.

**Comment by gyteng** [comment]
I found this problem at first. As we know, manager API have no security check and sometimes we need to manage remote node, I think there is 2 ways to solve it.

1. Just like you said, add iptables rules.
2. Add another program with security check before the manager port in every remote nodes.

Which way do you think is better?

**Comment by madeye** [comment]
I think you can try both ways. For the second way, you may provide a node based API proxy.

**Comment by gyteng** [comment]
OK, I will add it for the next version, thank you for your suggest.

**Comment by wangruifei** [comment]
点个赞
