### ISSUE TITLE
修改服务器失败

### ISSUE THREAD

**Issue by azumi-kiripa** [shadowsocks/shadowsocks-manager#270]
在修改服务器的时候提示修改服务器失败，已设置了.ssmgr目录的可写权限，请问是什么原因引起的，或者说需要设置其他目录权限？

**Comment by gyteng** [comment]
估计是你的服务器配置信息有误，请按模板贴出必要的信息，非bug请到tg群提问

**Comment by azumi-kiripa** [comment]
###Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
不清楚版本，但是是根据 https://github.com/shadowsocks/shadowsocks-manager/wiki/WebGUI 来安装的

### What operating system are you using?
Debian8 64bit

### What version of Node.js are you using?
6.11.2

### What did you do?
修改/新建服务器

### What did you expect to see?
修改或者新建服务器总是提示修改或添加失败

### What did you see instead?
修改/添加服务器失败

### What is your config in detail (with all sensitive info masked)?
