### ISSUE TITLE
从git 克隆安装 node server.js 如何运行 webgui？

### ISSUE THREAD

**Issue by q158073378252010** [shadowsocks/shadowsocks-manager#274]
```
/home/ssmgr/shadowsocks-manager# node server.js
use babel-core/register
[2017-08-20 11:47:54.159] [INFO] system - System start.
[2017-08-20 11:47:54.363] [INFO] system - ~/.ssmgr/default.yml not found, make file for it.
[2017-08-20 11:47:55.117] [INFO] system - Config file path:  /root/.ssmgr/default.yml
[2017-08-20 11:48:00.804] [INFO] system - server listen on 0.0.0.0:6002
```
/root/.ssmgr/default.yml  文件内容就是 git仓库中 config 文件夹中 default.yml 内容一致！

**Comment by yujincheng08** [comment]
node server.js -c webgui.yml, where the yml file is written by yourself.

**Comment by q158073378252010** [comment]
@yujincheng08 感谢！突然灵光一闪使用 `node server.js --help ` 知道了
你对 nginx 二级目录反代 webgui端口的页面有经验？

**Comment by yujincheng08** [comment]
@q158073378252010 直接反向代理就可以了。listen时候应该设置localhost防止其它端口能访问

**Comment by q158073378252010** [comment]
@yujincheng08 呵呵那是直接反代！我说的是二级目录反代。
举个例子 www.text.xyz 本身就是个网站 存在内容
ssmgr 监听本地端口。nginx 反代ssmgr 将内容挂到 www.text.xyz 的二级页面下。
就好像我访问 www.text.xyz 是一个网站(有内容）。但我访问 www.text.xyz/root 则是ssmgr管理端

**Comment by gyteng** [comment]
二级目录的话，估计前端的 "base" 部分也需要改动，所以才建议你做成一级的

**Comment by q158073378252010** [comment]
@gyteng  我只是想更好的隐藏它！

**Comment by yujincheng08** [comment]
How about using auth_basic?

Sent from Mail for Windows 10
