### ISSUE TITLE
无法正常访问

### ISSUE THREAD

**Issue by kunx-edu** [shadowsocks/shadowsocks-manager#276]
centos 6

`root@host shadowsocks-manager]# ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001`

通过浏览器访问6001端口，无法访问，防火墙未开。

能指点一下是什么原因吗

**Comment by gyteng** [comment]
使用问题请参考文档或到tg群提问

**Comment by kunx-edu** [comment]
1.在提问之前我已经尽可能的在全网进行了搜索
2.也查看了相关的文档,包括shadowsocks-libev
3.更是尝试了所有我能尝试的安装shadowsocks-manager的安装方式
4.也看到了通过tg进行联系的内容,但是我无法登陆tg,被墙了

所以,希望能够得到你的帮助.

十分感谢.

**Comment by Penguin-G** [comment]
无法访问，服务器拒绝了你的连接！
