### ISSUE TITLE
Account flow not topping up, and wrong due date in English language user account view

### ISSUE THREAD

**Issue by reversengineer** [shadowsocks/shadowsocks-manager#280]
### What version of everything
ssmgr 0.8.60 with mysql database, running ubuntu 14.04 with node v6.11.1

### What steps did you do?
Step 1. created user account
Step 2. recharged account 1 hour
Step 3. allowed account to expire after 1 hour
Step 4. recharged account 1 hour
Step 5. used all of account data flow
Step 6. recharged account 1 hour

### What did you expect to see?
1. After Step 4, in the user account view, the due date should be correct.
2. After Step 6, in the user account view, the due date should be correct.
3. After Step 6, the data usage count should be reset upon the renewal. Or, because there is still time remaining in the current cycle, the maximum data flow should be increased by the cycle flow amount. 

### What did you see instead?
1. After Step 4, In the user account view, the due date shows less remaining time than expected.
2. After Step 6, In the user account view, the due date shows less remaining time than expected.
3. After Step 6, the data usage count did not reset upon finishing the renewal transaction. This would be a problem when a user pays for additional cycle, assuming that the data is included. 

Please reference these photos after I performed step 6:

admin account view:
![admin](https://user-images.githubusercontent.com/6325257/29994857-c3d975b2-900c-11e7-93b0-a84a394e0650.png)

user account view:
![user](https://user-images.githubusercontent.com/6325257/29994858-c789ad3a-900c-11e7-809b-f6079b176f69.png)

**Comment by reversengineer** [comment]
Update --

After changing the user interface language to Chinese, the Account View is now displaying the correct Due Date. However, the English language is still showing the wrong Due date. 

Admin View:
![admin_chinese](https://user-images.githubusercontent.com/6325257/29994879-6dbbc9ea-900d-11e7-91fa-f5bfdad0793c.png)

User View (Chinese):
![user_chinese](https://user-images.githubusercontent.com/6325257/29994880-73b501a4-900d-11e7-95a9-76fc3ee3cb5b.png)

**Comment by gyteng** [comment]
I can not see anything wrong in your pictures

**Comment by reversengineer** [comment]
When the user interface is set to English, the Due Date "Time Remaining" calculation is wrong.

**Comment by gyteng** [comment]
I find the problem.
It will appear when the number is larger than 10.
I will fix it later.
