### ISSUE TITLE
关于添加帐号和单机多实例的建议

### ISSUE THREAD

**Issue by WooDragon** [shadowsocks/shadowsocks-manager#282]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.8.36

### What operating system are you using?
Centos

### What version of Node.js are you using?
8.4.0

### What did you do?
1. 在后台添加帐号时无法直接自定义可用服务器，也没有地方设置默认添加的帐号绑定哪个服务器，需要添加完成后，再点击帐号修改，启用自定义服务器。
2. 设置页面选择新用户自动分配帐号，对后台手动添加的新用户无效。
3. 我的场景是在一个服务器上开了多个ss的实例，使用不同的加密方式（服务器IP相同，端口不同），在这个情况下，新建的帐号会有问题，因为ssmgr会试图在同一个IP上开两个相同但加密方式不同的端口。

### What did you expect to see?
1. 建议可以在添加帐号界面直接绑定服务器，并在设置界面有个地方可以选择默认添加帐号时绑定的服务器。
2. 建议可以使新用户自动分配帐号对后台添加的帐号也有效，或者提供一个设置的地方。
3. 建议增加对单机多个ss后端实例的考虑，比如假设两个服务器IP相同的话，默认只绑定其中一个而不是两个都绑。

**Comment by gyteng** [comment]
第三点不会考虑，但你可以自己用 docker 隔离的方式实现

**Comment by gyteng** [comment]
第三点即将实现，到时候两个实例的端口可以错开，以达到开两种加密方式的目的

**Comment by linyanginc** [comment]
0.10.17  alpine 3.6 ss-libev 2.5.5 r2  , ss-server  已添加，新用户注册自动分配帐号无效，自定义1.json 有效，怎么设置？ 谢谢！

**Comment by Lanfei** [comment]
请问第一二点是否实现了呢？另外后台添加的用户前台无法登录？

**Comment by gyteng** [comment]
fix in 0.20
