### ISSUE TITLE
按年和按季度付费的问题

### ISSUE THREAD

**Issue by kesuki** [shadowsocks/shadowsocks-manager#283]
0.8.60版本中，管理员端添加端口，类型只有“不限量”、“按月”、“按周”、“按小时”、“按天”。没有了“按季度”和“按年”。而后台支付设置中依然有按年和按季度的设置。

而且，如果开通按年付费的流量包，结算周期应该是按年结算，但是变成按月结算流量，到期时间为一年后。

**Comment by gyteng** [comment]
就是这么设计的，按季实际上是三个月
