### ISSUE TITLE
升级到最新版本后流量统计出现异常

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#289]
### What version of shadowsocks-manager are you using?
v0.9.4
多服务器合并流量，流量系数均为1

### What operating system are you using?
Ubuntu 16.04LTS

### What version of Node.js are you using?
v6.11.3

### What did you do?
从0.8.8x(具体忘了八十几了，总之是这个月上旬的版本）升级到最新的0.9.3

### What did you expect to see?
一切正常

### What did you see instead?
账户流量突然多了好多， 有的账户甚至突然超出了百分之七八是的流量。
而历史记录里的流量加起来和统计的总量完全不符，历史记录里的加起来的要少很多

这种问题我不知道如何排查了。求助。

**Comment by gyteng** [comment]
多服务器合并流量的时候，流量系数是不起作用的。

你可以退回旧版看看统计的值有没有变化？

**Comment by cokebar** [comment]
@gyteng 流量统计是全部在m端，还是s端会统计自己的，m端只是汇总

**Comment by gyteng** [comment]
m端每2分钟会给s端发指令，把流量汇总

**Comment by cokebar** [comment]
继续使用后 发现汇总的流量是历史流量里显示的好几倍，两天内跑了十几个G实际却到了八十多
退回老版本后貌似正常了

**Comment by gyteng** [comment]
1. 有没有配置端口偏移值？
2. 未合并的情况下有无异常？
