### ISSUE TITLE
Found a ERROR help

### ISSUE THREAD

**Issue by ma6254** [shadowsocks/shadowsocks-manager#29]
![20160708132014.png](https://ooo.0o0.ooo/2016/07/08/577f3a0b1642d.png)

**Comment by gyteng** [comment]
未开启Mongodb

**Comment by ma6254** [comment]
Mongodb端口设定为多少?

**Comment by gyteng** [comment]
根据你的实际情况，默认是27017

2016-07-08 13:41 GMT+08:00 mjc <notifications@github.com>:

**Comment by ma6254** [comment]
数据库没问题了，但是网页是全白的，只有标题
![20160708134957.png](https://ooo.0o0.ooo/2016/07/08/577f40e2b37ab.png)

**Comment by gyteng** [comment]
预计是bower install这一步没装完全，你可以按F12打开调试窗口看报什么错
2016年7月8日 13:52，"mjc" <notifications@github.com>写道：

**Comment by ma6254** [comment]
![20160708141526.png](https://ooo.0o0.ooo/2016/07/08/577f469ce46d0.png)

**Comment by gyteng** [comment]
bower install的时候angularjs的版本不对
2016年7月8日 14:17，"mjc" <notifications@github.com>写道：

**Comment by ma6254** [comment]
具体怎么做?求指点

**Comment by ma6254** [comment]
npm WARN shadowsocks-manager@0.7.31 license should be a valid SPDX license expression
