### ISSUE TITLE
程序可扩展性问题

### ISSUE THREAD

**Issue by cbwang2016** [shadowsocks/shadowsocks-manager#290]
感觉支付方式的可扩展性太差。比如如果我想增加一个【比特币支付】，或者用一个什么第三方的支付宝免签约的API，得改各个地方的代码。请问这有什么比较好的解决方案吗？

**Comment by gyteng** [comment]
你仿照plugins目录下的alipay或paypal开发一个就好了

**Comment by cbwang2016** [comment]
@gyteng 是的，但是前端界面是不是还有不少地方要改？

**Comment by gyteng** [comment]
这是肯定要改的

**Comment by cbwang2016** [comment]
谢谢！刚刚尝试置换了alipay插件：https://github.com/cbwang2016/shadowsocks-manager-jsjapp
只花了不到1小时，感觉还不算特别麻烦。
