### ISSUE TITLE
Support non-periodic & manual traffic resetting

### ISSUE THREAD

**Issue by vilic** [shadowsocks/shadowsocks-manager#292]
In my use case, there are several people sharing same servers. And we collect the traffic usage to go dutch (offline payment).

It would be nice if we may have a more flexible traffic resetting condition.

### What version of shadowsocks-manager are you using?

0.9.4

### What operating system are you using?

Ubuntu 16.04

### What version of Node.js are you using?

8.6.0

### What did you do?

Setup a server and for sharing ss among some of my friends privately.

### What did you expect to see?

Hopefully a manual traffic resetting feature instead of periodic one.

**Comment by gyteng** [comment]
what do you mean traffic reset, can u give me an example?

vilicvane <notifications@github.com>于2017年10月5日 周四19:03写道：

**Comment by vilic** [comment]
It seems that now data usage is reset periodically, e.g. per month. I hope it is possible not to have data usage reset automatically, but manually instead. So I could charge my friend according to the data usage and reset it manually.

**Comment by gyteng** [comment]
there is a option named 'unlimited'

vilicvane <notifications@github.com>于2017年10月5日 周四19:32写道：

**Comment by vilic** [comment]
@gyteng I see. Just found out that I can navigate to previous weeks. Thanks for the help.
