### ISSUE TITLE
ss-manager: command not found

### ISSUE THREAD

**Issue by umangoo** [shadowsocks/shadowsocks-manager#294]
### What version of shadowsocks-manager are you using?
 0.9.5

### What operating system are you using?
Ubuntu 16.04 x86_64  

### What version of Node.js are you using?
v6.11.4

大神您好！
服务器安装安装教程：https://github.com/shadowsocks/shadowsocks/wiki/Shadowsocks-使用说明
已经成功实现代理。

我执行 npm i -g shadowsocks-manager 安装成功， 通过ssmgr -V  可以查看版本是 0.9.5
在执行 ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001 时
提醒：-bash: ss-manager: command not found
请问怎么解决，谢谢

**Comment by gyteng** [comment]
请按照 wiki 先安装 shadowsocks-libev
