### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by fishinbox** [shadowsocks/shadowsocks-manager#296]
It seems that ssmgr relies on fsevents during installation procedure. However, fsevents is an optional package and it is oly available on OSX.

Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.9.6

### What operating system are you using?
Ubuntu 16.04

### What version of Node.js are you using?
6.11

### What did you do?
npm i -g shadowsocks-manager

### What did you see instead?
/usr/local/bin/ssmgr -> /usr/local/lib/node_modules/shadowsocks-manager/bin/ssmgr
npm ERR! /root/shadowsocks-manager/node_modules/fsevents/node_modules/abbrev is not a child of /usr/local/lib

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-10T08_02_20_806Z-debug.log

**Comment by gyteng** [comment]
This problem is not about fsevents.

**Comment by fishinbox** [comment]
> This problem is not about fsevents.

Do you mean it is a problem related to fsevents?

**Comment by fishinbox** [comment]
@gyteng , And after that I tried to run ssmgr, got error output as following

~# ssmgr 
/root/shadowsocks-manager/lib/
/root/shadowsocks-manager/bin/ssmgr:7
process.chdir(lib);
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (/root/shadowsocks-manager/bin/ssmgr:7:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
