### ISSUE TITLE
接口协议文档更新

### ISSUE THREAD

**Issue by jccode** [shadowsocks/shadowsocks-manager#300]
接口协议文档中提到接口协议的规范,如下: 

> 发送：[4字节 消息长度][6字节时间戳][指令][4字节 校验码]
返回：[4字节 消息长度][指令]

这里的消息长度应该是2字节吧?

**Comment by gyteng** [comment]
确实是4个

**Comment by jccode** [comment]
https://github.com/shadowsocks/shadowsocks-manager/blob/321691c01e587bd61c4e05b091d6674353b863bf/services/manager.js#L18

这里是4个16进制的字符, 对应是2字节的长度. 代码明明是2个, 为什么确实是4个?

**Comment by gyteng** [comment]
刚刚仔细看了一下，果然是2字节，多谢提醒。
