### ISSUE TITLE
ssmgr 支持ipv6吗，如果支持怎么设置呢

### ISSUE THREAD

**Issue by KaiyangNi** [shadowsocks/shadowsocks-manager#302]
### What version of shadowsocks-manager are you using?
0.9.11

### What operating system are you using?
debian

### What version of Node.js are you using?
6.10.2

### What did you do?
访问ipv6

### What did you expect to see?
服务器支持ipv6，且使用默认的 shadowsocks. json 文件单用户能用，不知道在 ssmgr 里面怎么设置 ipv6，我找了一圈，都没有什么有用的结果，大多数都是修改默认配置文件来实现的，不知道用manage api 后的 ssmgr 怎么设置啊？

**Comment by gyteng** [comment]
不支持，因为我这没有ipv6的环境无法测试

**Comment by codgician** [comment]
如果服务器上运行的是 `shadowsocks-libev`，修改 `init/runShadowsocks.js` 中的这一行：
