### ISSUE TITLE
管理员账户和密码保存在哪个文件中?如何直接修改?

### ISSUE THREAD

**Issue by AmelieNet** [shadowsocks/shadowsocks-manager#303]
### What version of shadowsocks-manager are you using?
0.9.12

### What operating system are you using?
CentOS Linux release 7.3.1611 (Core) 

### What version of Node.js are you using?
v6.11.3

### What problem did you have?
请问'ssmgr'管理员账户和密码存放于哪个文件中?
我想要直接生成一个管理员账户
我的那个SMTP不管怎么配置都会出错误 [SendCloud(搜狐)](https://sendcloud.sohu.com/)

**Comment by gyteng** [comment]
数据库

Amelie <notifications@github.com>于2017年10月20日 周五14:35写道：

**Comment by AmelieNet** [comment]
@gyteng 哪该如何操作呢?能给个解决思路吗?
