### ISSUE TITLE
服务器端用户注册后生成的账号和口令采用明文存储，建议更改成加密存储

### ISSUE THREAD

**Issue by guanlihui** [shadowsocks/shadowsocks-manager#304]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.9.12

### What operating system are you using?
ubuntu1~14.04.3

### What version of Node.js are you using?
v6.11.3

### What did you do?
I just to test the user register.

### What did you expect to see?
User information should be encrypted.

### What did you see instead?
User information isn't encrypted.

### What is your config in detail (with all sensitive info masked)?
.shadowsocks_${port}.conf

**Comment by gyteng** [comment]
没有必要吧，用户登录密码是加密存储的

**Comment by guanlihui** [comment]
分配给用户的用户名和密码是明文存储的，不是太安全。

**Comment by gyteng** [comment]
有没有一个具体的实现方案？

2017-10-21 19:39 GMT+08:00 guanlihui <notifications@github.com>:

**Comment by guanlihui** [comment]
个人一个想法：可以模仿jenkins的一个做法，建立的口令等信息都是文件中加密存储，程序读取后有自己的解密处理方式，给用户显示的时候也解密显示，但是操作系统管理员无法查看到用户的私人口令等信息。

**Comment by gyteng** [comment]
觉得没有这个必要，因为这里假如需要加密存储的话，必须使用可逆的加密，还涉及到需要保存密码之类的事情

**Comment by gyteng** [comment]
感谢你的建议，不过近期不打算更改这一块，而且目前也没有一个具体的方案
