### ISSUE TITLE
新用户注册后管理员无法第一时间从用户列表和账户列表中查看到，需要清理浏览器缓存后才能正常加载，建议修正UI缓存策略，避免出现缓存冲突问题

### ISSUE THREAD

**Issue by guanlihui** [shadowsocks/shadowsocks-manager#305]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.9.12

### What operating system are you using?
ubuntu1~14.04.3

### What version of Node.js are you using?
v6.11.3

### What did you do?
I just to test the user register.

### What did you expect to see?
New users can be displayed in the user list。

### What did you see instead?
New users can't be displayed in the user list;but i clear the  browser cache,then I can see new user.

### What is your config in detail (with all sensitive info masked)?

**Comment by gyteng** [comment]
无法重现

**Comment by guanlihui** [comment]
我的重现步骤是：
1、管理员登录查看列表；
2、然后管理员退出；
3、新用户注册；
4、管理员登录查看列表，无法列表中看到这个新用户；
5、清理浏览器缓存后，管理员登录可以正常在列表中看到。

**Comment by gyteng** [comment]
这个加载过程不是实时的，你在列表页面停留几秒钟（取决于你服务器的网速）就有了

**Comment by BI7PRK** [comment]
久闻的用 javascript 来做服务端的极客技术。现在用上后才发现，原来体验这么差。而且作者还写那么多代码。体验主要是浏览器缓存问题
-退出不能退出。只是不能提交新数据
-用户注册，添加新项，更新参数。数据库已经更新，但UI呈现还是旧的。
-无论怎么刷新（Ctrl+F5） 都很难载入新数据到UI。
用户要解决这些的问题，必须删除浏览器的缓存数据。
浏览器是：谷歌、火狐
