### ISSUE TITLE
语言选择English后一些动态数据并没有完全完成国际化，比如“Recent Registrations”下的“2天前”

### ISSUE THREAD

**Issue by guanlihui** [shadowsocks/shadowsocks-manager#306]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

What version of shadowsocks-manager are you using?

0.9.12

What operating system are you using?

ubuntu1~14.04.3

What version of Node.js are you using?

v6.11.3

What did you do?

I choose the language.and I selected english.

What did you expect to see?

Chinese does not appear in the page.

What did you see instead?

Chinese does appear in the page

What is your config in detail (with all sensitive info masked)?

**Comment by gyteng** [comment]
请提交一些截图我好确定位置

guanlihui <notifications@github.com>于2017年10月21日 周六19:23写道：

**Comment by guanlihui** [comment]
![image](https://user-images.githubusercontent.com/8972513/31851409-b3a0a89e-b697-11e7-9497-6fb5b447f143.png)
