### ISSUE TITLE
重新发送邮件验证码没有发送出去

### ISSUE THREAD

**Issue by drlipingliu** [shadowsocks/shadowsocks-manager#307]
### What version of shadowsocks-manager are you using?
0.9.12

### What operating system are you using?
Ubuntu 14.04

### What version of Node.js are you using?
v6.11.4

### What did you do?
注册用户时第二次发送验证码邮件

### What did you expect to see?
收到第二个验证码邮件

### What did you see instead?
能收到第一个验证码，收不到第二个验证码。
在.ssmgr/log/webgui/email.log里，也显示只发出了第一个验证码邮件，发送第二个邮件的log没有显示

### What is your config in detail (with all sensitive info masked)?
type: m

manager:
  address: 127.0.0.1:6002
  password: 'XXXXXXX'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  email:
    use: true
    username: 'XXX@XXX.com'
    password: 'XXXXXXX'
    host: 'XXXXXX'
  webgui:
    use: true
    host: '127.0.0.1'
    port: '8080'
    site: 'XXXXXXXX'
    # cdn: 'http://xxx.xxx.com'
    # googleAnalytics: 'UA-xxxxxxxx-x'
    gcmSenderId: ''
    gcmAPIKey: ''
  alipay:
    use: false
    appid: 2015012104922471
    notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  paypal:
    use: false
    mode: 'live' # sandbox or live
    client_id: 'At9xcGd1t5L6OrICKNnp2g9'
    client_secret: 'EP40s6pQAZmqp_G_nrU9kKY4XaZph'

db: 'webgui.sqlite'

**Comment by gyteng** [comment]
何为第二次发送验证码？

2017-10-23 9:13 GMT+08:00 drlipingliu <notifications@github.com>:

**Comment by drlipingliu** [comment]
第一次发送的没收到，尝试重发。但是webgui并不重发（即便页面上可以让用户几分钟后重发）

**Comment by gyteng** [comment]
后端有没有错误信息

2017-10-23 17:11 GMT+08:00 drlipingliu <notifications@github.com>:

**Comment by drlipingliu** [comment]
在.ssmgr/log/webgui/email.log里，只有发出了第一个验证码邮件的log记录，没有发送第二个邮件的log记录。除此之外，没发现其它的错误信息

**Comment by gyteng** [comment]
第一个的错误信息呢

drlipingliu <notifications@github.com>于2017年10月23日 周一19:02写道：

**Comment by drlipingliu** [comment]
第一个log记录没有异常，和正常发出去的log记录一样的:

[2017-10-23 18:57:12.568] [INFO] email - [xxxxxxx@qq.com] Send code: 376111

**Comment by gyteng** [comment]
如果一次发送成功后，在这个验证码未失效前，短时间内是不会向那个地址发送的

drlipingliu <notifications@github.com>于2017年10月23日 周一19:05写道：

**Comment by drlipingliu** [comment]
理解。如果系统确实是这样设置的，那这个时间段和UI界面显示的可以发送下一个验证码的倒计时时间段如果一致的话可能不会让用户或管理员造成误解。

这个仅仅是个人看法，仅供参考。
