### ISSUE TITLE
用户注册时填写电子邮箱，获取验证码，并填写验证码后“注册”按钮还是灰色的

### ISSUE THREAD

**Issue by drlipingliu** [shadowsocks/shadowsocks-manager#308]
### What version of shadowsocks-manager are you using?
0.9.12
### What operating system are you using?
Ubuntu 14.04.5

### What version of Node.js are you using?
v6.11.4

### What did you do?
到注册页面，填写电子邮箱，获取验证码，并填写获取的验证码，准备点击“注册”按钮

### What did you expect to see?
“注册”按钮可点击，点击后显示注册成功

### What did you see instead?
“注册”按钮为灰色，没有激活，点击无效。请见截图

<img width="1199" alt="screen shot 2017-10-23 at 22 12 38" src="https://user-images.githubusercontent.com/33011751/31886577-a059fe3e-b840-11e7-8d21-f4f3eef4f07d.png">

### What is your config in detail (with all sensitive info masked)?
type: m

manager:
  address: 127.0.0.1:6002
  password: 'xxxxxxxxxxx'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  email:
    use: true
    username: 'xxxxxxx@xxxxxxx.com'
    password: 'xxxxxxxxxxxxx'
    host: 'smtp.xxxxxxxx.com'
  webgui:
    use: true
    host: '127.0.0.1'
    port: '8080'
    site: 'https://xxxxxxxxxxx.com'
    # cdn: 'http://xxx.xxx.com'
    # googleAnalytics: 'UA-xxxxxxxx-x'
    gcmSenderId: ''
    gcmAPIKey: ''
  alipay:
    use: false
    appid: 2015012104922471
    notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  paypal:
    use: false
    mode: 'live' # sandbox or live
    client_id: 'At9xcGd1t5L6OrICKNnp2g9'
    client_secret: 'EP40s6pQAZmqp_G_nrU9kKY4XaZph'

db: 'webgui.sqlite'

**Comment by gyteng** [comment]
没填密码

**Comment by drlipingliu** [comment]
啊！真丢脸！抱歉打扰！
