### ISSUE TITLE
服务器流量统计显示的日期不符

### ISSUE THREAD

**Issue by drlipingliu** [shadowsocks/shadowsocks-manager#309]
### What version of shadowsocks-manager are you using?
0.9.12
### What operating system are you using?
Ubuntu 14.04.5
### What version of Node.js are you using?
v6.11.4
### What did you do?
查看ss服务器今天流量统计（10月23日）

### What did you expect to see?
今天的流量统计，和用户使用情况相符，也和用户流量统计汇总相符

### What did you see instead?
看到了今天的流量统计是错误的（和用户使用情况不符，也和用户流量统计汇总不符）。但是明天的流量统计（10月24日）却是今天的正确流量统计。

但是用户单独流量统计的日期和流量却是正确的（显示的是10月23日，流量也正确）。

下图为今天的服务器的流量汇总图（但是显示的是10月24日）

查看服务器的日期是正确的：
root@iZj6c1q38vbvbZ:~# date
Mon Oct 23 20:42:03 CST 2017

<img width="897" alt="screen shot 2017-10-23 at 23 29 33" src="https://user-images.githubusercontent.com/33011751/31889332-371969d6-b84b-11e7-9acf-462104ba57db.png">

**Comment by gyteng** [comment]
没有提供具体的重现方法
