### ISSUE TITLE
控制服务每分钟会向SS发送一次添加端口的命令，导致日志量巨大

### ISSUE THREAD

**Issue by shishuo365** [shadowsocks/shadowsocks-manager#313]
控制服务每分钟会向SS发送一次添加端口的命令，导致日志量巨大；
按照正常逻辑，应该是每分钟向SS请求已开启的端口，只添加缺少的端口，这样就不会有错误日志了。
日志如下：
2017-10-27 18:00:00 ERROR    server already exists at 0.0.0.0:2000

**Comment by gyteng** [comment]
之前也有人出现这个情况，但我无法重现这个问题

**Comment by shishuo365** [comment]
配置环境如下：

**Comment by shishuo365** [comment]
配置环境如下：
shadowsocks-python 安装2.8.x版本，以后台方式运行 sserver -c ss.conf -f ss.log -p ss.pid -d start
shadowsocks-manager 安装0.10.2版本，作为s端，以pm2方式运行 pm2 start ss.json
在另外一台机器
shadowsocks-manager 安装0.10.2版本，作为m端，以pm2方式运行 pm2 start ss.json

**Comment by gyteng** [comment]
ss.conf 里写了什么内容，可试试改用 libev 版

2017-10-29 10:05 GMT+08:00 阿宝 <notifications@github.com>:
