### ISSUE TITLE
在Safari和Chrome上看不到最新注册用户的注册时间

### ISSUE THREAD

**Issue by drlipingliu** [shadowsocks/shadowsocks-manager#314]
### What version of shadowsocks-manager are you using?
0.9.18

### What operating system are you using?
ubuntu 16.04.5

### What version of Node.js are you using?
v6.11.4

### What did you do?
用管理员账号登录，在首页查看最新注册用户的注册时间和最近登录用户的登录时间

### What did you expect to see?
期望页面显示最新注册用户的注册时间和最近登录用户的登录时间

### What did you see instead?
使用Safari或Chrome时，最新注册用户的注册时间和最近登录用户的登录时间不显示。但是使用Firefox时，是显示的

**Comment by gyteng** [comment]
看浏览器上有无错误提示

2017-10-27 21:09 GMT+08:00 Drliping Liu <notifications@github.com>:

**Comment by drlipingliu** [comment]
从页面显示来看，没有任何错误提示。下图是截图。不知有没有其他方法查看浏览器的log

<img width="1182" alt="screen shot 2017-10-28 at 00 00 22" src="https://user-images.githubusercontent.com/33011751/32105641-e7564838-bb74-11e7-90c6-b1002e5115b0.png">

**Comment by gyteng** [comment]
打开浏览器控制台看

2017-10-27 21:15 GMT+08:00 Drliping Liu <notifications@github.com>:

**Comment by drlipingliu** [comment]
我对浏览器控制器不熟，但是我能查看Safari的控制器。它所有的tab(Element, Network, Resources, Timelines, Debugger, Storages, Console)显示的都没有发现有异常的地方。没有显示有错误的地方。唯一我觉得有可能的是在Network tab中，recentSignUp, recentLogin的返回http状态码为304，和其他很多资源都一样。

**Comment by drlipingliu** [comment]
可能发现可疑的东西了，请看截图：0px x 0px

<img width="1540" alt="screen shot 2017-10-28 at 00 32 09" src="https://user-images.githubusercontent.com/33011751/32106612-e458e03e-bb77-11e7-9cdc-93ecf0736674.png">

**Comment by gyteng** [comment]
我这里无法重写你的问题

**Comment by drlipingliu** [comment]
在我的iPhone手机的Safari浏览器也能重现同样的问题

**Comment by gyteng** [comment]
这个我在 Safari Chrome Firefox Edge 下都不能重现，建议你先更新到最新版本试试

2017-10-28 16:49 GMT+08:00 Drliping Liu <notifications@github.com>:

**Comment by drlipingliu** [comment]
升级到最新版本(0.10.2)后还是同样的问题。我用的是iMac，在这台电脑上，Safari和Chrome都有同样的问题，iPhone上的Safari也是又问题。但是我用另一台Ubuntu电脑上的Firefox, 它没有问题。

**Comment by gyteng** [comment]
你的Safari和macOS是什么版本

Drliping Liu <notifications@github.com>于2017年10月28日 周六17:05写道：

**Comment by drlipingliu** [comment]
Safari: Version 11.0 (12604.1.38.1.7)
Chrome: Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by drlipingliu** [comment]
我把Chrome升级到最新的：Version 62.0.3202.75 (Official Build) (64-bit)后，Chrome可以显示了！

**Comment by drlipingliu** [comment]
MacOS版本：10.12.6 (16G29)

**Comment by gyteng** [comment]
还是无法重现
