### ISSUE TITLE
mysql配置疑问

### ISSUE THREAD

**Issue by MaShuShu** [shadowsocks/shadowsocks-manager#315]
### What version of shadowsocks-manager are you using?
0.10.1

### What operating system are you using?
ubuntu16.04

===============================================================
请问用mysql数据库的时候，s端和m端是需要指定不同的数据库吗？

**Comment by gyteng** [comment]
使用问题请到tg群提问，s端请用SQLite，如果一定要用MySQL的话必须用不同的库

2017-10-29 11:57 GMT+08:00 MaShuShu <notifications@github.com>:
