### ISSUE TITLE
页面图标尺寸不一致

### ISSUE THREAD

**Issue by drlipingliu** [shadowsocks/shadowsocks-manager#316]
### What version of shadowsocks-manager are you using?
0.10.2

### What operating system are you using?
Ubuntu 14.04

### What version of Node.js are you using?
v6.11.4

### What did you do?
访问英语版首页

### What did you expect to see?
下方闪电，扳手，钥匙图标下方的文字上下对齐

### What did you see instead?
扳手下的文字没有对齐，整体向下移动了（在中文版是正常的）．查看了原因，很可能是因为在英文版里，＂扳手＂图标的高度（１０８）比＂闪电＂，＂钥匙＂图标（８８．８）略高．请见截图

![screenshot from 2017-10-30 12-11-08](https://user-images.githubusercontent.com/33011751/32150946-a254cd8c-bd6c-11e7-86b3-9dc81b3b2a1c.png)
![screenshot from 2017-10-30 12-11-52](https://user-images.githubusercontent.com/33011751/32150949-a58165f6-bd6c-11e7-8d9a-a8a4f01d0ad4.png)

**Comment by gyteng** [comment]
居然有这种情况？能不能放个整体的截图看看

2017-10-30 9:21 GMT+08:00 Drliping Liu <notifications@github.com>:

**Comment by drlipingliu** [comment]
![screenshot from 2017-10-30 13-57-45](https://user-images.githubusercontent.com/33011751/32152830-7e1e8bd4-bd7a-11e7-8a55-35a96744147f.png)
![screenshot from 2017-10-30 13-59-48](https://user-images.githubusercontent.com/33011751/32152847-a890ff32-bd7a-11e7-9a89-778096f64059.png)

**Comment by gyteng** [comment]
我自己电脑用Chrome访问没有出现这个问题，你的操作系统跟浏览器是？

**Comment by drlipingliu** [comment]
２台机子都有同样的问题：
１．iMac，浏览器：Safari和Chrome
２．Ubuntu16.04,　浏览器：Firefox. 版本56.0 (64-bit)

**Comment by gyteng** [comment]
终于找到问题了，英文版的描述换行导致的
