### ISSUE TITLE
Hope don't auto remove the expird accounts

### ISSUE THREAD

**Issue by Jaggle** [shadowsocks/shadowsocks-manager#318]
### What version of shadowsocks-manager are you using?
0.9.11

### What operating system are you using?
centos7

### What version of Node.js are you using?
v6.11.3

### What did you expect to see?
希望用户注册的账号，在过期后(默认)不会被自动删除

### What did you see instead?
新注册的用户，相应账号过期后被自动删除

**Comment by gyteng** [comment]
目前没有相应的地方可以配置，或许以后会有这个功能

2017-11-01 16:22 GMT+08:00 Liu Jie <notifications@github.com>:
