### ISSUE TITLE
管理员用户面板无法加载出数据

### ISSUE THREAD

**Issue by Lostars** [shadowsocks/shadowsocks-manager#320]
### What version of shadowsocks-manager are you using?
0.10.5

### What operating system are you using?
centos6.9 kernel:4.13

### What version of Node.js are you using?
v6.11.5

### What did you do?
administrator dashboard user control panel is always loading

### What did you expect to see?
show register user list

### What did you see instead?
loading icon

### What is your config in detail (with all sensitive info masked)?
![111](https://user-images.githubusercontent.com/13404175/32367394-e4363db4-c0bc-11e7-8231-f918a7e96555.png)
![222](https://user-images.githubusercontent.com/13404175/32367397-e47ff648-c0bc-11e7-9207-2ef50472833f.png)

**Comment by gyteng** [comment]
请贴出后端错误信息，多半是你的数据库有问题

**Comment by Lostars** [comment]
@gyteng 不应该的吧，其他功能都是正常的，只有用户面板一直加载无法显示

**Comment by Lostars** [comment]
@gyteng 
![333](https://user-images.githubusercontent.com/13404175/32368215-fd83f52e-c0bf-11e7-9613-77ffb107c340.png)
貌似sql问题
