### ISSUE TITLE
 [ERROR] system - { Error: insert into "command" ("code", "time") values ('6883d531', 1509886036161) - SQLITE_CONSTRAINT: UNIQUE constraint failed: command.code

### ISSUE THREAD

**Issue by Jaggle** [shadowsocks/shadowsocks-manager#323]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.9.11

### What operating system are you using?
centos 7

### What version of Node.js are you using?
v6.11.3

### What did you do?
ssmgr -c ss.yml 查看日志发现大量这种错误，另外 command表可以清空吧？为什么不用id做主键呢？

### What did you see instead?

除了以上错误，顺便贴一下这个，也比较多见：

```
[ERROR] system - Unhandled Rejection at: Promise Promise {
  <rejected> Error: ssmgr[s] return an error code [la1.v.geekerism.com:4001]
    at receiveData.then.message (/root/shadowsocks-manager/services/manager.js:71:18)
    at process._tickCallback (internal/process/next_tick.js:109:7) } reason: Error: ssmgr[s] return an error code [la1.v.geekerism.com:4001]
    at receiveData.then.message (/root/shadowsocks-manager/services/manager.js:71:18)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

### What is your config in detail (with all sensitive info masked)?
ss.yml:

```
type: s

shadowsocks:
  address: 0.0.0.0:4000
manager:
  address: 0.0.0.0:4001
  password: 'xxxxxx'
db: 'xxxxx.sqlite'
```

**Comment by gyteng** [comment]
这个表没有问题，就是这么设计了

**Comment by roy2651** [comment]
我也遇到了这个问题，如果这个错误日志在会影响使用嘛？请问是怎么解决的

**Comment by Jaggle** [comment]
不影响使用，产生的原因估计是多个节点（不同的域名）使用了相同的IP
