### ISSUE TITLE
出现错误 ： root@ubuntu:~# ssmgr -c ~/.ssmgr/webgui.yml /usr/local/node-v6.5.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/ [2017-11-14 04:00:12.851] [INFO] system - System start. [2017-11-14 04:00:13.119] [ERROR] system - Caught exception: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Yee2** [shadowsocks/shadowsocks-manager#327]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
v0.10.12

### What operating system are you using?
ubuntu 16.04

### What version of Node.js are you using?
v6.5

### What did you do?
ssmgr -c ~/.ssmgr/webgui.yml

### What did you see instead?
````
/usr/local/node-v6.5.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/
[2017-11-14 04:05:19.705] [INFO] system - System start.
[2017-11-14 04:05:19.890] [ERROR] system - Caught exception: TypeError: Path must be a string. Received undefined
````
### What is your config in detail (with all sensitive info masked)?
````
root@ubuntu:~# uname -a
Linux ubuntu 4.10.0-21-generic #23~16.04.1-Ubuntu SMP Tue May 2 12:57:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~# node -v
v6.5.0
````

**Comment by gyteng** [comment]
config file is incorrect
