### ISSUE TITLE
一些使用经验和建议

### ISSUE THREAD

**Issue by johnlui** [shadowsocks/shadowsocks-manager#33]
昨天发现了这个好用的项目，下载了之后安装、测试过发现相当的方便，能给我们小创业公司提供很多帮助。在使用的过程中，出现了一些问题，在解决这些问题的过程中，积累了一些经验，同时我也想给做着一些建议。

基本特性：

1. 通过跟踪日志，我发现用户可用性检测似乎以 2 分钟为单位在 00 秒执行
2. 新建用户没有默认可用时长，这就导致了其在两分钟后将会被删除，这个删除操作后面每两分钟还会继续尝试执行😂😂
3. 如果在两分钟内没有给新建立的用户分配时长和流量，其将在 2 分钟时被删除，如果之后被分配了时长和流量，这个账户一直要到下一个 2 分钟检查节点才会被重新加入系统
4. 为了安全，ssserver --manager-address 127.0.0.1:6001 执行时一般绑定 127.0.0.1 本地 ip（此管理接口没有任何安全认证），但是本管理系统在添加服务器时并未将“管理系统内网ip”和“用户使用的外网ip”分开，只能填一个，这样就导致了自动生成的二维码是以 127.0.0.1 作为服务器 ip 的，不可用。

建议：

1. 每 2 分钟一次的用户可用性检测功能需要加强，比如将“某个账户已超时被删除”的状态加入数据库，这样就不用每次都给 ssserver 发送删除用户的请求了，如果是开放系统，那么过期用户可能有很多，这对 ssserver 是个不必要的负担
2. 在某个服务器下添加新的 端口-密码 组合时加入别名，便于小企业内部管理区分
3. 添加新的 端口-密码 组合后默认分配的永久和不限流量的状态
4. 添加新的 端口-密码 组合后立刻触发一次账户可用性检测，将用户加入 ssserver，避免管理员以为操作无效【重要】
5. 添加服务器时，分开记录 管理系统内网地址 和 公网用户用地址，让二维码功能真正可用。

如果作者接受，我可以加入项目共同开发，给这个开源项目做出贡献~

**Comment by gyteng** [comment]
上面所说的几点之前我已经有意识到，因为刚开始做的时候没打算这么复杂的功能，后来越做越复杂，目前的版本有点混乱，除了重大bug以外并不打算修复这些问题。

现在我正在重写一个新的版本，主要想把非基础功能剥离，已插件的方式提供，方便以后添加，同时也会解决你说的上述问题。

**Comment by johnlui** [comment]
👍
