### ISSUE TITLE
关于更改首页页面的问题

### ISSUE THREAD

**Issue by hahsen** [shadowsocks/shadowsocks-manager#330]
你好，
       我装完程序后，在更改
/root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/plugins/webgui/public/controllers
下的home.js

![qq 20171119173459](https://user-images.githubusercontent.com/33789295/32989404-2037309e-cd50-11e7-9096-aab8cec7676c.png)

更改完如图所示部分后，首页依然是原始信息。

![qq 20171119173617](https://user-images.githubusercontent.com/33789295/32989405-29eb56b0-cd50-11e7-80d1-34846155b3fd.png)

已经重启过。

请问是什么原因，烦请指教

**Comment by gyteng** [comment]
npm run build 再重启

2017-11-19 17:36 GMT+08:00 hahsen <notifications@github.com>:

**Comment by hahsen** [comment]
执行完npm run-script build和npm run build以后
重启服务器网站直接502了，清理浏览器缓存无效

重新执行
- screen -dmS ss-manager ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000
- cd /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/bin/
- screen -dmS ss node ssmgr -c ss.yml
- screen -dmS webui node ssmgr -c webgui.yml

还是502

**Comment by hahsen** [comment]
贴一段执行npm的滚动

> shadowsocks-manager@0.10.12 build /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager
> gulp

[18:41:31] Using gulpfile ~/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/gulpfile.js
[18:41:31] Starting 'clean'...
[18:41:31] Starting 'webguiBuild'...

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: Entry module not found: Error: Cannot resolve module 'babel-loader' in /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager
resolve module babel-loader in /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager
  looking for modules in /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules
    module variation babel-loader-webpack-loader
      /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-webpack-loader doesn't exist (module as directory)
      resolve 'file' babel-loader-webpack-loader in /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules
        resolve file
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-webpack-loader doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-webpack-loader.webpack-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-webpack-loader.web-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-webpack-loader.loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-webpack-loader.js doesn't exist
    module variation babel-loader-web-loader
      /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-web-loader doesn't exist (module as directory)
      resolve 'file' babel-loader-web-loader in /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules
        resolve file
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-web-loader doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-web-loader.webpack-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-web-loader.web-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-web-loader.loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-web-loader.js doesn't exist
    module variation babel-loader-loader
      /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-loader doesn't exist (module as directory)
      resolve 'file' babel-loader-loader in /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules
        resolve file
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-loader doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-loader.webpack-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-loader.web-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-loader.loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader-loader.js doesn't exist
    module variation babel-loader
      /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader doesn't exist (module as directory)
      resolve 'file' babel-loader in /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules
        resolve file
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader.webpack-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader.web-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader.loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/babel-loader.js doesn't exist
  looking for modules in /root/node-v6.11.2-linux-x64/lib/node_modules
    module variation babel-loader-webpack-loader
      /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-webpack-loader doesn't exist (module as directory)
      resolve 'file' babel-loader-webpack-loader in /root/node-v6.11.2-linux-x64/lib/node_modules
        resolve file
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-webpack-loader doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-webpack-loader.webpack-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-webpack-loader.web-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-webpack-loader.loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-webpack-loader.js doesn't exist
    module variation babel-loader-web-loader
      /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-web-loader doesn't exist (module as directory)
      resolve 'file' babel-loader-web-loader in /root/node-v6.11.2-linux-x64/lib/node_modules
        resolve file
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-web-loader doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-web-loader.webpack-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-web-loader.web-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-web-loader.loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-web-loader.js doesn't exist
    module variation babel-loader-loader
      /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-loader doesn't exist (module as directory)
      resolve 'file' babel-loader-loader in /root/node-v6.11.2-linux-x64/lib/node_modules
        resolve file
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-loader doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-loader.webpack-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-loader.web-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-loader.loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader-loader.js doesn't exist
    module variation babel-loader
      /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader doesn't exist (module as directory)
      resolve 'file' babel-loader in /root/node-v6.11.2-linux-x64/lib/node_modules
        resolve file
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader.webpack-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader.web-loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader.loader.js doesn't exist
          /root/node-v6.11.2-linux-x64/lib/node_modules/babel-loader.js doesn't exist

npm ERR! Linux 2.6.32-696.10.1.el6.x86_64
npm ERR! argv "/root/node-v6.11.2-linux-x64/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! shadowsocks-manager@0.10.12 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shadowsocks-manager@0.10.12 build script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shadowsocks-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs shadowsocks-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls shadowsocks-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/npm-debug.log

**Comment by gyteng** [comment]
npm i
npm run build

**Comment by hahsen** [comment]
已解决谢谢
cd /node-v6.11.2-linux-x64/lib/node_modules/shadowsocks-manager/
rm -rf node_modules
npm i
npm run build
pm2 restart all
