### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by codgician** [shadowsocks/shadowsocks-manager#333]
### What version of shadowsocks-manager are you using?
0.10.15

### What operating system are you using?
Ubuntu 17.10 x64

### What version of Node.js are you using?
8.9.1

### What did you do?
execute ssmgr

### What did you expect to see?
It should be running.

### What did you see instead?
It reports error:
`ssmgr: /usr/bin/env: ‘node\r’: No such file or directory`

### What is your config in detail (with all sensitive info masked)?
Default.

I think it has something to do with CRLF.

**Comment by ppshadow** [comment]
I also meet this problem, how to fix?

**Comment by codgician** [comment]
It is caused by CRLF end-of-line marker.
Here's a temporary workaround using vim.

First, you'll need to locate ssmgr entry script by entering the command below:
```bash
which ssmgr
```
It will return the location of ssmgr entry script. For me (Debian), it is located here:
``` bash
/usr/local/bin/ssmgr
```

Then we open it using vim with `-b` option:
```bash
vim /usr/local/bin/ssmgr -b
```
Enter `:%s/\r//g` to remove `\r` globally.
Then Enter `:wq` to save and exit.
