### ISSUE TITLE
支持gmail ssl smtp 吗？

### ISSUE THREAD

**Issue by 007shaoye** [shadowsocks/shadowsocks-manager#335]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What is your config in detail (with all sensitive info masked)?
  email:
    use: true
    type: 'smtp'
    username: 'xxxx@gmail.com'
    password: 'yyyy'
    host: 'smtp.gmail.com'

用于发送验证码的邮箱，支持gmail ssl smtp 吗？

**Comment by gyteng** [comment]
支持

**Comment by 007shaoye** [comment]
有可以参考的配置项嘛?
尝试添加port: '587'、port：'465'配置项，页面都提示“验证码发送错误”。

**Comment by gyteng** [comment]
不需要填Port，使用问题请到tg群提问，这里只是用于提bug

**Comment by naiba** [comment]
怎么配置ssl的smtp？现在很多都是禁用了25

**Comment by kuaile1993** [comment]
怎么配置呢？我的gmail也配置不成功
