### ISSUE TITLE
流量统计问题

### ISSUE THREAD

**Issue by EvenCu** [shadowsocks/shadowsocks-manager#337]
### What version of shadowsocks-manager are you using?
0.10.22
### What operating system are you using?
debian8 64
### What version of Node.js are you using?
v6.12.0

流量：
1.50 GB / 50.00 GB   (此处流量统计每日自动重置了，现在:每日有50G，原计划50G/月)

2017-12-10 / 2017-12-16，12.95 GB

**Comment by gyteng** [comment]
请贴图看看一些具体细节

2017-12-11 22:31 GMT+08:00 EvenCu <notifications@github.com>:

**Comment by EvenCu** [comment]
![34](https://user-images.githubusercontent.com/13349843/33841334-69448d84-ded2-11e7-8e31-2b27bc72477e.PNG)
1.50 GB / 80.00 GB     (用户当前使用量/包月流量)

**Comment by gyteng** [comment]
上面的1.5G是一个统计周期内的流量
下面的9.63G是数字前面那一周时间内产生的流量

**Comment by EvenCu** [comment]
举例 包月用户80G/每月  剩余流量如何查询
