### ISSUE TITLE
在python版本的ss中，会出现2017-12-14 07:20:00 ERROR    server already exists at 0.0.0.0:59885的问题

### ISSUE THREAD

**Issue by jacklau88** [shadowsocks/shadowsocks-manager#338]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?

ss python
### What operating system are you using?
centos 6.5

### What version of Node.js are you using?
8.9.3

### What did you do?

在python版本的ss中，会出现2017-12-14 07:20:00 ERROR    server already exists at 0.0.0.0:59885的问题
### What did you expect to see?

在python版本的ss中，会出现2017-12-14 07:20:00 ERROR    server already exists at 0.0.0.0:59885的问题
### What did you see instead?

看你的代码，在

const addAccount = (() => {
  var _ref4 = _asyncToGenerator(function* (port, password) {
    try {
      if (!checkPortRange(port)) {
        return Promise.reject('error');
      }
      const insertAccount = yield knex('account').insert({
        port,
        password
      });
      yield sendMessage(`add: {"server_port": ${port}, "password": "${password}"}`);
      return { port, password };
    } catch (err) {
      return Promise.reject('error');
    }
  });
这里并有去检查端口是否存在，所以在每分钟向ss提交端口时，会出现端口已经存在的错误。

事实上 if (!checkPortRange(port)) {
        return Promise.reject('error');
      }
这里不是去ss上获取端口信息。而是从ssmgr中的配置文件中获取端口的范围。
### What is your config in detail (with all sensitive info masked)?
建议增加从服务端获取端口检查的判断

**Comment by gyteng** [comment]
py版的manager API并没有检查某个端口是否正在使用的功能，只能从返回的流量信息里得知

2017-12-14 15:33 GMT+08:00 Rodger <notifications@github.com>:

**Comment by jacklau88** [comment]
那你的意思，只能从ssmgr端来做判断了？假如某个端口已经有流量了，则表示该端口肯定在ss上添加过了。看来要改程序了。

**Comment by gyteng** [comment]
是的，libev 版有个 list 指令可以看到当前实际开启的端口，但 python 版的没有

2017-12-14 15:52 GMT+08:00 Rodger <notifications@github.com>:

**Comment by jacklau88** [comment]
貌似端口的流量数据并没有存到db下的flow表中。。。
