### ISSUE TITLE
初始化管理员账户失败？

### ISSUE THREAD

**Issue by BeatenMo** [shadowsocks/shadowsocks-manager#34]
这几天想折腾ss的多用户+流量统计，看到这个
然后服务器上拉下来
config.js配置好admin后，启动
mongo内见库，没见有数据啊....
这下问题来了，管理员帐号怎么搞？

**Comment by gyteng** [comment]
没有建数据库有可能是你把mongodb的帐号密码填错了

**Comment by BeatenMo** [comment]
不不不，我的意思是mongo内有库在，但是没有管理员的数据！

**Comment by gyteng** [comment]
在users这个表里边会有的。

**Comment by BeatenMo** [comment]
在config.js是配置好的，但是node server的时候并没有自动加上
你登录的时候会提示你用户未注册

**Comment by gyteng** [comment]
请提供你的config.js看是否有问题，注意隐去重要的信息（如密码等）

**Comment by BeatenMo** [comment]
exports.conf = {
    db: {
        host: '127.0.0.1',
        port: '27017',
        name: 'ssm',
        user: '',
        pass: ''
    },
    admin: {
        email: '8888',
        password: '8888'
    },
    mail: {
        address: 'youremailaddress@gmail.com',
        password: 'yourpassword',
        smtp: 'smtp.gmail.com',
        webaddress: 'http://8.abc.com'
    },
    express: {
        http: 81,
        https: 443,
        key: '',
        cert: ''
    }
};

**Comment by gyteng** [comment]
管理员帐号必须是邮箱地址
2016年7月12日 09:53，"BeatenMo" <notifications@github.com>写道：
