### ISSUE TITLE
default.yml是给S用还是M用？

### ISSUE THREAD

**Issue by justyu** [shadowsocks/shadowsocks-manager#341]
### What version of shadowsocks-manager are you using?
shadowsocks-manager 0.10.23

### What operating system are you using?
ubuntu 1604

### What version of Node.js are you using?
v6.12.2

### What did you do?
ssmgr -c ~/.ssmgr/ss.yml

### What did you see instead?
~/.ssmgr/default.yml not found, make file for it.
我已经指定了配置文件ss.yml，为什么会自动生成这个default.yml？
debug模式下，会显示Config file path:  /home/yang/.ssmgr/ss.yml，非debug模式下不会输出，让人误以为无论如何使用的都是default？

**Comment by justyu** [comment]
无论是ss.yml还是webgui.yml，都会出现~/.ssmgr/default.yml not found, make file for it.

**Comment by gyteng** [comment]
当这个文件不存在的时候，会自动创建

**Comment by justyu** [comment]
我知道这个会自动创建，我的问题是，我明明指定了ss.yml或者webgui.yml，为什么还会创建这个文件呢？而且我必须把这个文件修改和ss.yml一样的内容才能正常工作，是否bug？ @gyteng

**Comment by gyteng** [comment]
当你用了 -c 参数的时候，使用的是你自定的那个配置文件，
没有用 -c 时才用的是 default.yml
