### ISSUE TITLE
email是否可以不试用SMTP？

### ISSUE THREAD

**Issue by justyu** [shadowsocks/shadowsocks-manager#342]
能否直接试用mail命令发送邮件，而不是借助外部SMTP？
好多邮件服务商比如QQ，SMTP登录或者发信次数多了会被限制。

**Comment by gyteng** [comment]
mail命令指的是？

**Comment by justyu** [comment]
Linux下的mailutils这个工具，可以直接使用下面的命令发送邮件：
`echo “This is a test mail!”| mail -s test **@mail.xyz.cn`
不受邮件服务商的限制，自己的主机相当于一个邮件服务器。

**Comment by gyteng** [comment]
你可以更改一下 plugins/email 来实现

2017-12-18 15:03 GMT+08:00 Yang <notifications@github.com>:
