### ISSUE TITLE
multiuser how to config  .yml to support multi port

### ISSUE THREAD

**Issue by Hello-World-0X** [shadowsocks/shadowsocks-manager#345]
What version of shadowsocks-manager are you using?
ss python

What operating system are you using?
cnetos
7.4.1708

What version of Node.js are you using?
6.12.*
What did you do?
config default.yml

What did you expect to see?
I have multi users and ports,how to write the .yml to support this.
If all users use only one port and password , how to monitor their own flow?
What did you see instead?

**Comment by gyteng** [comment]
please join tg group and ask questions about how to use it
