### ISSUE TITLE
Use https with apache

### ISSUE THREAD

**Issue by inCHOK-broken-earphone** [shadowsocks/shadowsocks-manager#350]
### What version of shadowsocks-manager are you using?
0.10.26

### What operating system are you using?
CentOS 7

### What version of Node.js are you using?
6.12.0

### What did you do?
I want to use https with apache instead of nginx,so I proxy / to port 8080. It do work as the title change to Shadowsocks-Manager, but all the webpage is blank. What should I do?

**Comment by gyteng** [comment]
I haven't use apache before, maybe you can ask someone in telegram group
