### ISSUE TITLE
ssmgr command not found问题

### ISSUE THREAD

**Issue by blackfoxsar** [shadowsocks/shadowsocks-manager#351]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.11.11

### What operating system are you using?
Debian 9.3

### What version of Node.js are you using?
6.12.3

### What did you do?
ssmgr

### What did you expect to see?
ssmgr command not found

PS: 
安装的时候一切顺利,用git clone后npm i的方式安装了manager
ss-libev则是apt-get的方式，ss-libev版本号：2.6.3

运行ss-manager做测试完全正常，唯独运行ssmgr的时候直接提示了command not found

npm唯二的提示都是WARN，内容如下：
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by gyteng** [comment]
使用问题请到tg群提问
