### ISSUE TITLE
全局底部加了挖矿脚本？？？

### ISSUE THREAD

**Issue by naiba** [shadowsocks/shadowsocks-manager#353]
[CoinHive](https://github.com/shadowsocks/shadowsocks-manager/blob/b8e1174ec5d997ec7b56d221aaf4c1e2e4ba53f4/plugins/freeAccountMiner/views/index.html)

网站全局底部全部加入了挖矿脚本。

有没有在用的朋友留下链接，我检查一下你们的有没有被加入挖矿脚本。

**Comment by gyteng** [comment]
这个插件设计的目的就是挖矿换取可用流量，另外一个 freeaccount 插件就是不挖矿，定时更改密码的

**Comment by naiba** [comment]
@gyteng 我网站底部全局被加入了挖矿代码。`aHR0cDovL2ppYXN1LnpnYy5pbw==`

**Comment by gyteng** [comment]
请更新到最新版本
