### ISSUE TITLE
about the e-mail

### ISSUE THREAD

**Issue by vinsec** [shadowsocks/shadowsocks-manager#359]
Gmail已经开启【允许运行不安全的应用】，以及POP/IMAP;在Webgui.yml里面也已经配置了，但是主页始终无法注册，即验证码发送不出去，长时间loading，最后都会显示【网络错误】.请问如何正确配置邮箱模块，这一部分文档不是很明确，希望能予以指出。

**Comment by gyteng** [comment]
使用问题请到tg群提问

**Comment by vinsec** [comment]
然而提了问题根本没人回答
