### ISSUE TITLE
Error after starting ssmgr -c webgui.yml

### ISSUE THREAD

**Issue by Maverick0174** [shadowsocks/shadowsocks-manager#362]
### What operating system are you using?
centOS 6.9 .el6.x86_64 x86_64 

### What version of Node.js are you using?
v9.5.0

Hello,
i just installed fresh shadowsocks-manager. When i start "ssmgr" then it looks like below: (I guess that´s ok?)

**# ssmgr
/usr/lib/node_modules/shadowsocks-manager/lib/
[2018-02-08 04:04:30.578] [INFO] system - System start.**

But when i start start ssmgr -c webgui.yml then i become following error:

**# ssmgr -c webgui.yml
/usr/lib/node_modules/shadowsocks-manager/lib/
[2018-02-08 03:27:52.927] [INFO] system - System start.
[2018-02-08 03:27:55.858] [ERROR] system - { Error: connect ECONNREFUSED 127.0.0.1:6002
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6002 }
[2018-02-08 03:27:55.880] [ERROR] flowSaver - connect to server 123456@127.0.0.1:6002 fail.**

My webgui.yml: 

**type: m

manager:
  address: 127.0.0.1:6002
  password: '123456'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  email:
    use: true
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://xxx.xxx.94.155:3010'
    # cdn: 'http://xxx.xxx.com'
    # googleAnalytics: 'UA-xxxxxxxx-x'
    gcmSenderId: '456102641793'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  alipay:
    use: false
    appid: 2015012104922471
    notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  # webgui_telegram:
  #   use: true
  #   token: '191374681:AAw6oaVPR4nnY7T4CtW78QX-Xy2Q5WD3wmZ'
  paypal:
    use: false
    mode: 'live' # sandbox or live
    client_id: 'At9xcGd1t5L6OrICKNnp2g9'
    client_secret: 'EP40s6pQAZmqp_G_nrU9kKY4XaZph'

db: 'webgui.sqlite'**

The default.yml

type: s

shadowsocks:
  address: 127.0.0.1:6001
  #portRange: 50000-51000,55000,55002

manager:
  address: 0.0.0.0:6002
  password: '123456'

db: 'db.sqlite'

**# db:
#   host: '1.1.1.1'
#   user: 'root'
#   password: 'abcdefg'
#   database: 'ssmgr'
~
~
~
~
~
~
"default.yml" 17L, 248C**

I´m an absolutely newbie ... please help me *cry* I´ve no idea where to investigate next....
Thanks a lot in advance....
Andi

**Comment by gyteng** [comment]
Please ask questions in telegram group when you have some problems about deploy it.

**Comment by Maverick0174** [comment]
where? I´m sorry, I don´t know where you mean. I´m absolut new here ....

**Comment by Maverick0174** [comment]
Please ask questions in telegram group when you have some problems about deploy it. --- great help! WTF is telegram group????
