### ISSUE TITLE
流量统计问题

### ISSUE THREAD

**Issue by flishqq** [shadowsocks/shadowsocks-manager#363]
### What version of shadowsocks-manager are you using?
0.12.6

### What operating system are you using?
debian8 x64

### What did you do?
设置新用户分配按天 周期为1的账号 到期后用户自己购买了月付套餐

### What did you expect to see?
流量按月自动重置

### What did you see instead?
流量按天重置，并没有按月重置

![Image](https://s1.ax1x.com/2018/02/13/9YZQ9e.jpg)
如图，总流量跑了114.3M，但是统计流量只计算了当天的2.3M，之前使用的均被清零。
统计周期显示的是2018-02-13——2018-03-15 应该已经是按月统计了，为什么还是会按天清零呢？

**Comment by gyteng** [comment]
就是这么设计的。

首先，统计周期是以最后一次付费的周期为准。

其次，下面的“周视图”统计的是02-11到02-17这期间的流量，而2.3M是02-13到03-15的。

**Comment by flishqq** [comment]
明白了，感谢解答
