### ISSUE TITLE
管理后台BUG

### ISSUE THREAD

**Issue by Alicture** [shadowsocks/shadowsocks-manager#372]
最新版 centos 后台管理设置title，其中有‘ 的话，进不来网站了

**Comment by Alicture** [comment]
webgui.sqlite 这个在哪里？或者说怎么样可以修改我在后台设置的title。我现在无法进入网站了= =好像是json的问题。

**Comment by gyteng** [comment]
在`~/.ssmgr`目录

**Comment by Alicture** [comment]
@gyteng 感谢。刚刚我自己找到了哈哈

**Comment by Alicture** [comment]
看来需要手动转义字符233 @gyteng

**Comment by gyteng** [comment]
这不科学，除了这个字符还有其他什么字符有问题吗？

**Comment by Alicture** [comment]
@gyteng 并没有
