### ISSUE TITLE
支付宝只支持RSA(SHA256)密钥，不支持RSA(SHA1)了

### ISSUE THREAD

**Issue by xlliu** [shadowsocks/shadowsocks-manager#373]
What version of shadowsocks-manager are you using?
laster

What operating system are you using?
CentOS7

配置文件中：
alipay:
use: true
appid: 2015012108272442
notifyUrl: ''
merchantPrivateKey: 'xxxxxxxxxxxx'
alipayPublicKey: 'xxxxxxxxxxx'
gatewayUrl: 'https://openapi.alipay.com/gateway.do'
![image](https://user-images.githubusercontent.com/13271844/37014444-b69a1058-213b-11e8-97cb-e414cca5d8f5.png)

问题一：notifyUrl需要和支付宝 **授权回调地址** 相同吗？

![image](https://user-images.githubusercontent.com/13271844/37014512-1fb8d6b4-213c-11e8-9025-bf53083ad797.png)

问题二：目前支付宝只支持RSA(SHA256)密钥，不支持RSA(SHA1)了

**Comment by gyteng** [comment]
1. 不需要相同，也可以不填
2. 不支持

使用问题请到tg群里提问
