### ISSUE TITLE
续费后流量重置

### ISSUE THREAD

**Issue by reizhi** [shadowsocks/shadowsocks-manager#374]
### What version of shadowsocks-manager are you using?
0.13.5

### What operating system are you using?
Debian 8 x64

### What version of Node.js are you using?
6.11.2

### What did you do?
当账户还未到期就进行续期操作时，当前周期的流量会重置为续期所选套餐的流量。如按月付费的账户，提前续期周计划，当前月周期流量会变为周计划设置的流量。

### What did you expect to see?
续期不应影响当前周期的流量。

**Comment by gyteng** [comment]
就是这么设计的，有一个解决办法是只能让用户续费相同的周期
