### ISSUE TITLE
周视图流量呈现有问题

### ISSUE THREAD

**Issue by donnychenji** [shadowsocks/shadowsocks-manager#375]
直接上图，看3月6日周二，天视图正常，周视图曲线图无显示，饼图正常，如何解决？还是程序bug？
![qq 20180307100623](https://user-images.githubusercontent.com/36958958/37069647-3b1f88cc-21ef-11e8-9cd8-395962f871f7.png)

![qq 20180307100906](https://user-images.githubusercontent.com/36958958/37069727-95c3b992-21ef-11e8-8eeb-90f8ea7a1e84.png)

**Comment by gyteng** [comment]
截图太不详细了，要具体些，曲线图显示的是你当前所选节点的

**Comment by donnychenji** [comment]
重新截了两个图，不是某一个账号的流量，是一个服务器总的流量

![default](https://user-images.githubusercontent.com/36958958/37075383-83a66594-220c-11e8-8319-274647260780.PNG)

![2](https://user-images.githubusercontent.com/36958958/37075399-98ec459a-220c-11e8-90f4-9866dee1ecce.PNG)

**Comment by gyteng** [comment]
从这张图看确实不太正常，那3月5日、3月4日的是否正常呢？

2018-03-07 13:37 GMT+08:00 donnychenji <notifications@github.com>:

**Comment by donnychenji** [comment]
3月4日的数据不是当天出来的，我在3月5日查看周视图时，发现3月4日与3月5日的流量是正常呈现的。

**Comment by donnychenji** [comment]
现在是3月8日，刚看了周视图，发现3月6日的数据出来了，7日的却没了。
总结一下问题现象是：当天和两天前的数据正常呈现，前一天的数据无法呈现。如：3月7日时，7日和5日的数据正常，6日不呈现；3月8日时，8日和6日的数据正常，7日不呈现。说得有点啰嗦，不知道表述清楚没有。还是把今天的图也上了

![_20180308034302](https://user-images.githubusercontent.com/36958958/37114201-a3b12218-2282-11e8-87cb-c3e6024a8c40.jpg)

![_20180308034221](https://user-images.githubusercontent.com/36958958/37114221-ae62f72c-2282-11e8-92c7-f8bd05cc8854.jpg)

**Comment by donnychenji** [comment]
默认是UTC时区，2月25日～3月3日期间，我发现周视图的数据呈现日期对应错误，记得不太清楚，好像是所有的日期呈现都晚两天，3月1日上网的流量记录在了3月3日上。后来我使用
ln -sf /usr/share/zoneinfo/PRC /etc/localtime和hwclock --systohc
命令修改了时区，呈现的日期就能对应上了，这两天才发现周视图中的数据会刷新不及时
