### ISSUE TITLE
流量视图问题

### ISSUE THREAD

**Issue by justyu** [shadowsocks/shadowsocks-manager#378]
![chart](https://user-images.githubusercontent.com/5106317/37342115-92490fba-26fe-11e8-8c33-a0178e5ed457.png)

服务器流量视图，x轴没有单位，是时间吗？如果是的话是最近一天吗？
请问能否加上x轴单位和数值啊？这里显示用了流量但是chart上啥都没有感觉怪怪的

**Comment by gyteng** [comment]
最近一小时，5分钟一格

Yang <notifications@github.com>于2018年3月13日 周二20:41写道：
