### ISSUE TITLE
关于WebGui使用Apache反向代理到HTTPS无法加载的解决方案

### ISSUE THREAD

**Issue by inCHOK-broken-earphone** [shadowsocks/shadowsocks-manager#389]
版本0.14.19
使用Apache反向代理到https时,会出现页面空白的情况.经检查是页面调用的本地资源路径错误的问题,for example:
ProxyPass /shadowsocks http://localhost:8080
现在加载WebGui,由于libs下的js路径为<%= cdn%>/libs/xxx.js,会被重定向到https://localhost/libs/xxx.js,因而无法加载
一种解决方案是使用mod_proxy_html,然而容易导致同一路径下其它文件路径出错
 因而@gyteng 建议将所有绝对路径改为相对路径

**Comment by gyteng** [comment]
请勿反代到子目录
