### ISSUE TITLE
用户操作和服务器的功能建议，还有续费码续时间续不了

### ISSUE THREAD

**Issue by oocco** [shadowsocks/shadowsocks-manager#39]
生成续费码使用时只续流量，但是时间不会增加，管理员后台操作可以增加时长，
是设置的原因吗？

建议：
1.添加删除用户操作
2.添加删除续费码操作
3.续费续流量可以使用自定义数值
4.shadowsocks服务重启后账号清空，后台可以操作直接重新建立数据库现有服务器账号（同时可以显示服务器账号密码真实数据）

**Comment by codexss** [comment]
第四点的话ss服务重启之后管理端监控的话两分钟内端口进程会重新启动的

**Comment by gyteng** [comment]
1和2会在近期添加
