### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by siriusfinex** [shadowsocks/shadowsocks-manager#394]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.14.23

### What operating system are you using?
ubuntu 16.04

### What version of Node.js are you using?
Node.js 6.*

### What did you do?
Telgram bot could't set my account to administer

**Comment by siriusfinex** [comment]
怎么查看日志呢？

**Comment by siriusfinex** [comment]
我第一次申请到telegram bot之后，在服务器上的webgui.yml配置文件输入webgui telegram相关信息，然后用的是一个shadowsocks-manager的注册用户账号（非管理员账号）打开绑定telegram bot，但不能成为auth，然后我将这个telegram bot通过botFather删除，然后再新建了一个telegram bot，删除原来的telegram bot对话窗口，然后停止了服务器上的shadowsocks-manager所有服务，然后打开webgui.yml，输入新的telegram token，重启服务器的ss-manager服务，然后用管理员账号登录ss-manager网页，再点击绑定telegram，跳转到telegram页面后，输入绑定页面给的那个验证码，telegram bot没反应。

**Comment by gyteng** [comment]
使用问题请到tg群提问，另外请贴出配置文件看格式是否有误

在 2018年4月16日 下午5:05，sean <notifications@github.com>写道：
