### ISSUE TITLE
升级后公告管理无法加载

### ISSUE THREAD

**Issue by reizhi** [shadowsocks/shadowsocks-manager#397]
### What version of shadowsocks-manager are you using?
0.14.35

### What operating system are you using?
Debian 8

### What version of Node.js are you using?
6.11.2

### What did you do?
从0.14.2x更新到0.14.35

### What did you see instead?
设置-公告管理进入后持续加载，无法显示已有公告。新添加的公告可以正常发布，但也无法显示出来。
<img src="http://ww1.sinaimg.cn/large/61af290fgy1fqmt7ueyklj21h10ehjr9.jpg"/>
### What is your config in detail (with all sensitive info masked)?
type: m
empty: false

manager:
  address: ***
  password: '***'
plugins:
  giftcard:
    use: true
  macAccount:
    use: true
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  email:
    use: true
    username: '***'
    password: '***'
    host: '***'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8800'
    site: 'http://***'
    gcmSenderId: '***'
    gcmAPIKey: '***'
  alipay:
    use: true
    appid: ***
    notifyUrl: '***'
    merchantPrivateKey: '***'
    alipayPublicKey: '***'
    gatewayUrl: '***'

db: 'webgui.sqlite'

**Comment by gyteng** [comment]
配置文件缺少 group 插件
