### ISSUE TITLE
作者你在我的服务器上注册了账号吗？

### ISSUE THREAD

**Issue by 823639792** [shadowsocks/shadowsocks-manager#406]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.15

### What operating system are you using?
ubuntu 16

### What version of Node.js are you using?
6.X

### What did you do?
我发现你的qq注册了我部署的服务器

### What is your config in detail (with all sensitive info masked)?

最近几天在00fly.com上部署了ssmgr服务器，但是只有我一个人用，今天突然发现多出来一个账号，qq邮箱，还创建了一个订单，但是没有支付。

然后qq查找，应该是gyteng的qq，我申请了增加你为好友，但是你没有通过。

我比较好奇，你是如何知道我的域名的？难道是ssmgr有什么后门吗？因为各种密码，和支付宝的公钥私钥都在服务器上，所以我对此很担心。

**Comment by gyteng** [comment]
代码都在这里，有没有后门自己看。
谷歌一下就能找到你站点了

**Comment by 823639792** [comment]
谷歌都能搜到我的站点了？
