### ISSUE TITLE
用户帐号的二维码有和管理账号看到的二维码有差异

### ISSUE THREAD

**Issue by Cangol** [shadowsocks/shadowsocks-manager#407]
用户注册帐号后，使用最新shadowsocks客户端扫码连接，扫码拿到的主机显示未定义
经过实际分析比对发现：
用户得到的二维码和管理账号在后台看到的二维码不一致（缺少部分信息），管理账号在后台直接扫用户的二维码链接是正常的。

**Comment by gyteng** [comment]
多谢提醒，找到问题了，等 0.17.0 将修复它

**Comment by Cangol** [comment]
谢谢，期待中
