### ISSUE TITLE
payment create qrcode : invild qrcode

### ISSUE THREAD

**Issue by Restry** [shadowsocks/shadowsocks-manager#409]
### What version of shadowsocks-manager are you using?
0.15.0 or latest

### What operating system are you using?
ubuntu 16.4

### What version of Node.js are you using?
v 9.8

### What did you do?
在账号页面点击续费

### What did you expect to see?
生成正常二维码

### What did you see instead?
可以生成二维码但是扫描后显示invild qrcode

### What is your config in detail (with all sensitive info masked)?
log里面没有任何异常, 而且付款以前是成功的. 最近一段时间生成的二维码扫描后就是无效二维码.

key什么的都是对的.

**Comment by cw760** [comment]
有相同问题。关注

**Comment by gyteng** [comment]
请看后端控制台的log
