### ISSUE TITLE
用户配置信息无法写入数据库

### ISSUE THREAD

**Issue by Xilesun** [shadowsocks/shadowsocks-manager#41]
你好，我配置了config.js之后其中的用户信息无法写入mongodb中，打开网页登录显示用户未注册，操作数据库查看未能看到相关的用户信息，应该如何解决

**Comment by gyteng** [comment]
管理员账号能否写入数据库，是不是你配置了数据库密码？

2016-08-07 23:15 GMT+08:00 xilesun <notifications@github.com>:

**Comment by Xilesun** [comment]
谢谢该问题已解决，其他问题已经发送至邮箱
