### ISSUE TITLE
反映两个问题

### ISSUE THREAD

**Issue by donnychenji** [shadowsocks/shadowsocks-manager#410]
反映两个问题，我现在的shadowsocks-manager版本号是0.17.6，之前用的0.13.1没有这两个问题
1、目前发现使用windows的QQ浏览器和360浏览器无法登陆，IE和谷歌正常。打开欢迎页面后，点击登陆，输入后台配置的用户账号密码，点击登陆后，没有任何提示直接返回欢迎页面。
2、Iphone7（IOS10.2） Safari打开shadowsocks-manager欢迎页面，标志图片显示不完全
![_20180520202021_](https://user-images.githubusercontent.com/36958958/40278860-83ba8602-5c6b-11e8-8c3d-bebf35f9bcdc.jpg)

**Comment by gyteng** [comment]
如何重现这个问题？

**Comment by donnychenji** [comment]
重现哪个问题？第一个？现在也没有好。。。
