### ISSUE TITLE
自己搭建邮件服务器问题

### ISSUE THREAD

**Issue by smartlin** [shadowsocks/shadowsocks-manager#415]
自己搭建了一个邮件服务器，发送验证码总是收不到邮件，用foxmail测试能正常收发
尝试修改源代码依然不成功，特地来请教下作者，谢谢！

**Comment by gyteng** [comment]
使用方面的问题请到tg群提问

**Comment by smartlin** [comment]
刚刚仔细看下源码，已OK，感谢
