### ISSUE TITLE
怎样用pm2启动ss-manager命令

### ISSUE THREAD

**Issue by siriusfinex** [shadowsocks/shadowsocks-manager#418]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.17.19

### What operating system are you using?
ubuntu 16.04

### What version of Node.js are you using?
Node.js 6*

### What did you do?
大佬们，请问，怎么用pm2启动这条命令：ss-manager -m chacha20-ietf-poly1305 -u --manager-address 127.0.0.1:6000，pm2进程名字为“ssmanager”。

**Comment by cokebar** [comment]
pm2 start ss-manager --name=ssmanager  -- -m chacha20-ietf-poly1305 -u --manager-address 127.0.0.1:6000
