### ISSUE TITLE
关于找回密码问题

### ISSUE THREAD

**Issue by Wiillam** [shadowsocks/shadowsocks-manager#419]
### What version of shadowsocks-manager are you using?
0.18.9

### What operating system are you using?
Ubuntu 18.04 x86_64

### What version of Node.js are you using?
v8.10.0

### What did you do?
我的面板登录选择找回密码后邮件可以正常发出，但是不是我的域名，也无法访问。请问我改如何解决？请问这和我的域名解析到ss的ip地址有冲突吗？

### What did you expect to see?
收到的邮件地址是“http://我的域名/home/password/reset/乱码”，正常访问，重置密码

### What did you see instead?
收到的邮件地址是“http://不认识的IP/home/password/reset/乱码”，无法访问，也不是我的域名

### What is your config in detail (with all sensitive info masked)?
webgui.yml
type: m
  
manager:
  address: x.x.x.x:4001
  password: 'xxxx'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    type: 'smtp'
    username: 'xxxx'
    password: 'xxxx'
    host: 'smtp.xxxx.com'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://www.xxxx.com'

db: 'webgui.sqlite'

**Comment by gyteng** [comment]
配置文件 webgui - site 字段有误
