### ISSUE TITLE
可否实现按服务器分组，不同分组用户使用不同服务器

### ISSUE THREAD

**Issue by CoterJiesen** [shadowsocks/shadowsocks-manager#432]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.19.6

### What operating system are you using?
centos7 

### What version of Node.js are you using?

v8.11.3

### What did you do?

可否实现按服务器分组，不同分组使用不同服务器

**Comment by goodjimli** [comment]
+1
