### ISSUE TITLE
Sudden huge unrealistic spikes in data usage in saveFlow table

### ISSUE THREAD

**Issue by mklnz** [shadowsocks/shadowsocks-manager#437]
### What version of shadowsocks-manager are you using?
Commit #57cf324170d484a834eba5dfda9d6b2b2fac5191

### What operating system are you using?
Ubuntu 16.04 64-bit

### What version of Node.js are you using?
v8.10.0

I'm seeing some strange behaviour with the data usage table in saveFlow (I'm assuming it's recorded every 1-2 min or so). Sometimes I can see entries well over 50GB, or even up to 100GB in a single record, which doesn't seem to be realistic to me since you can't really transfer so much data in such little time.

Are these entries a bug, or there is something else going on here? It also seems to affect multiple accounts at the same time when it is compounded.

`select * from saveFlow where flow >= 5000000000`

<img width="392" alt="screen shot 2018-07-24 at 3 57 19 pm" src="https://user-images.githubusercontent.com/604101/43124657-548d3132-8f5a-11e8-9684-39873c69fc46.png">

**Comment by gyteng** [comment]
I can not reproduce
