### ISSUE TITLE
can't delete order if giftcard plugin is not used

### ISSUE THREAD

**Issue by linusyoung** [shadowsocks/shadowsocks-manager#439]
When giftcard plugin is not used and try do delete existing "order", it will return errData = '删除订单失败'

server side log:
` Error: SQLITE_ERROR: no such table: giftcard errno: 1, code: 'SQLITE_ERROR' }`

Once allowing giftcard plugin, no issue with deleting orders.

**Comment by hklcf** [comment]
same here

**Comment by hklcf** [comment]
https://github.com/shadowsocks/shadowsocks-manager/blob/791ab3902020b8df962bd2cc622a0d709501ccb2/plugins/webgui_order/index.js#L63
