### ISSUE TITLE
Is this not a shadowsocks client?

### ISSUE THREAD

**Issue by Crafsman** [shadowsocks/shadowsocks-manager#442]
### What version of shadowsocks-manager are you using?
0.22.2

### What operating system are you using?
windows

### What version of Node.js are you using?
8.11.32

### What did you do?
to check if this support shadowsocks client

### What did you expect to see?
this is a server manger instead of a client

### What did you see instead?
this is a server manger instead of a client

### What is your config in detail (with all sensitive info masked)?
no config

**Comment by Crafsman** [comment]
If I want to use this as a client side, what should I do?

**Comment by chrisx8** [comment]
Check out these clients:
  - [shadowsocks-windows](https://github.com/shadowsocks/shadowsocks-windows)
  - [shadowsocks-android](https://github.com/shadowsocks/shadowsocks-android)
  - [shadowsocksX-NG (macOS)](https://github.com/shadowsocks/ShadowsocksX-NG)

**Comment by yujianxuechuan** [comment]
for ubuntu client ?

**Comment by Crafsman** [comment]
@yujianxuechuan windows
