### ISSUE TITLE
proposal: add new payment method based on alipay_f2f

### ISSUE THREAD

**Issue by houstar** [shadowsocks/shadowsocks-manager#446]
### Background
Currently all the payment vendor don't allow individual developer to use its API without registered.  This proposal introduced new payment method called `Face to face (abbrev. f2f)`. And its also called `收钱码` in Chinese. 

***Pros***
* NO fee to deposit to Bank Card.
* NO fee to process transaction

***Cons***
* Manually check with Order in Alipay App

#### step 1.
Get `收钱码` from Alipay

#### step 2.
Use QrCode to scan this `收钱码` to get its qr_code.

This qr_code is string something like  `https://qr.alipay.com/tsx04037ldlrckl1elnox5c`

#### step 3. 
add plugin in config.yml
```
alipay_f2f:
      qr_code: https://qr.alipay.com/tsx04037ldlrckl1elnox5c
```

#### step 4.
When the User `createOrder` to buy our service, the `createOrder` should be like:
```
userId:
accountId:
orderId:
alipayAccount:  <---- This field is to let us identify which alipayAccount will be payed.
```

#### step 5
 Our Alipay  App will be get the notification if User payed the order.
 Manually check the order in website and change the order status to success.

 In advance, we can open the `Alipay sound notification` and  converting the sound to other protocol to notify our website the payment is done.

**Comment by hklcf** [comment]
聽說收钱码交易次數太多會封號

**Comment by gyteng** [comment]
no plan for this

**Comment by houstar** [comment]
@hklcf  不限制交易次数，但是会限制每单的交易额度不超过1000人民币

我已经在自己的仓库实现了这个功能，已经正式上线，参考 [alipay_f2f branch](https://github.com/houstar/shadowsocks-manager/commits/alipay_f2f)

**Comment by llong0625** [comment]
> @hklcf 不限制交易次数，但是会限制每单的交易额度不超过1000人民币
> 
> 我已经在自己的仓库实现了这个功能，已经正式上线，参考 [alipay_f2f branch](https://github.com/houstar/shadowsocks-manager/commits/alipay_f2f)

你好 我尝试了你的解决方法 但是好像跟现在的manager版本不一样 请教能不能帮忙看一下？
