### ISSUE TITLE
日志输出太快

### ISSUE THREAD

**Issue by goodjimli** [shadowsocks/shadowsocks-manager#448]
1.日志输出太快，没必要！
 [2018-08-16 16:03:05.652] [INFO] system - { command: 'list' }
[2018-08-16 16:03:05.825] [INFO] system - { command: 'list' }
[2018-08-16 16:03:06.022] [INFO] system - { command: 'list' }
 能提升 日志的输出级别为ERROR?
2. ss-manager  s 端掉线时候 ，webGUI 200ms查询一次？ 没必要吧。

**Comment by cokebar** [comment]
@gyteng 为什么close了，这个问题挺严重的，从我几天前更新到新版本0.25.X之后开始出现，可以看到一天的日志有6万多行：
![image](https://user-images.githubusercontent.com/9136591/45031407-6cdf0a80-b057-11e8-9d14-8f8fd44478c8.png)
是提高了查询的频率么？但是零点几秒到几秒一次也太多了。而且会导致一天几万次写操作。。
版本更新前是一分钟一次的：
![image](https://user-images.githubusercontent.com/9136591/45031607-f8589b80-b057-11e8-8176-a305472c54fc.png)
希望赶紧修复一下。

另外 @goodjimli 提出的日志输出级别的问题也很有必要改一下，现在是INFO级别就输出，更新前一天也有几千条。 建议改成能调整，默认ERROR或者WARNING级别，INFO级别是调试时候才可能用到的。
还有就是日志压缩能否把周期改长点，现在每天一个压缩文件，有点多，一周一个如何？

**Comment by gyteng** [comment]
为啥会出现这么快的情况，总共有几个服务器，几个端口？

**Comment by cokebar** [comment]
五个服务器 二三十个端口

**Comment by cokebar** [comment]
看了一下log4js的文档，似乎compress只有一个开关，目前只能一天一个压缩包。只好这样了。
这里log4js用的1.1.1，看了一下新版3.x的文档似乎用法更加清晰，日志分类/分级更方便了，可以考虑适配一下新版

**Comment by cokebar** [comment]
由于是外行，看半天还是看不懂代码，加上log4js 1.1.1版本不像现在3.x的文档齐全，目前只能将log文件输出暂时禁用（注释了checkConfig.js里相关的哪一行）

**Comment by cokebar** [comment]
@gyteng Could you please reopen this issue?

**Comment by zktz** [comment]
今天也遇到这个问题了，vps被服务商关闭了。

**Comment by zktz** [comment]
解决了，其实不光log写的频繁，db也是写的频繁。vps服务商说我每秒4k以上的io。所以又给我关机了。
我现在的解决方案是把db和log放到内存盘里，然后定时同步到磁盘上。
vps服务商说fine。

**Comment by collinsyu** [comment]
在account_checker.js 里面控制的，最后一段部分：限制了最大不超过100ms！可以在这里改下，不知道会有什么后果？是不是用户会多刷走点流量？ 0.25.X
