### ISSUE TITLE
High CPU usage in 0.25.4

### ISSUE THREAD

**Issue by Ricky-Hao** [shadowsocks/shadowsocks-manager#449]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.25.4

### What operating system are you using?
Docker with alpine

### What version of Node.js are you using?
8.11.3

### What did you do?
run webgui

### What did you expect to see?
low CPU usage as before

### What did you see instead?
high CPU usage

### What is your config in detail (with all sensitive info masked)?
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  email:
    use: true
    type: 'smtp'
    username: ''
    password: ''
    host: ''
    # 这部分的邮箱和密码是用于发送注册验证邮件，重置密码邮件
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8888'
    site: ''

**Comment by gyteng** [comment]
Please show the CPU usage chart and logs

**Comment by Ricky-Hao** [comment]
Sorry, it's my server problem.
