### ISSUE TITLE
报错：“支付宝签名验证失败”

### ISSUE THREAD

**Issue by pjxxcc** [shadowsocks/shadowsocks-manager#456]
(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.25.8

### What operating system are you using?
centos （Linux version 4.18.3-1.el7.elrepo.x86_64）

### What version of Node.js are you using?
v8.11.4

### What did you do?
尝试生成支付二维码

### What did you expect to see?
期望成功生成二维码

### What did you see instead?
生成二维码失败，后台报错：
{ message: '支付宝签名验证失败',
  info: 
   { alipay_trade_precreate_response: 
      { code: '10000',
        msg: 'Success',
        out_trade_no: '20180……6835',
        qr_code: 'https://qr.alipay.com/bax09……081' },
     sign: 'BZXl5OLy6/te5Q1MA…………ObbqolQg==' } }

支付宝2018年7月10日已经升级证书 https://open.alipay.com/platform/announcement.htm?id=1
猜测是目前程序不支持RSA2导致的？

**Comment by pjxxcc** [comment]
刚刚查看依赖库alipay-ftof的源码，发现是使用的RSA2（RSA-SHA256）。
开来我得另外找原因了

**Comment by gyteng** [comment]
估计是生成key的步骤错了

**Comment by pjxxcc** [comment]
生成的key没错，是配置错了。
错误原因：我把自己生成的公、私钥分别放到了alipayPublicKey、merchantPrivateKey上。
正确配置：
1. 自己生成的私钥配置到merchantPrivateKey上；
2. 自己生成的公钥配置到支付宝；
3. 从支付宝获取支付宝生成的公钥，配置到alipayPublicKey上。
