### ISSUE TITLE
mode m的配置文件

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#461]
程序首次运行的时候会检查这个字段，添加mode s的服务器，没有这个字段会报错，
```
manager:
  address: 1.1.1.1:4001
  password: '123456'
```

然而实际情况是后来这些mode s的服务器数据写进数据库里了，根本不需要在配置文件里配置。
希望能去掉这里的检查，新建一个webgui端的时候无mode s服务器也没有问题，后面自行在web端登录添加即可

**Comment by gyteng** [comment]
已修复
