### ISSUE TITLE
手机浏览器首页显示icon排列乱版

### ISSUE THREAD

**Issue by ojoehao** [shadowsocks/shadowsocks-manager#464]
### What version of shadowsocks-manager are you using?

A: Latest, should be 0.25.16

### What operating system are you using?

A:IOS, safari

### What version of Node.js are you using?

A: 8.0

### What did you do?

A: Entry the index page.

### What did you expect to see?

A:  Beauty frontend that buttons are below icon.  

### What did you see instead?

A: buttons are in icon. 

### What is your config in detail (with all sensitive info masked)?

A: I tested with the site: https://wall.gyteng.com

**Comment by gyteng** [comment]
有截图吗？
