### ISSUE TITLE
web加密方式显示不对？

### ISSUE THREAD

**Issue by mengzhihoing** [shadowsocks/shadowsocks-manager#466]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.26.7

### What operating system are you using?
Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-135-generic x86_64)

### What version of Node.js are you using?
8.12.0

### What did you expect to see?
aes-256-gcm

### What did you see instead?
web显示的是aes-256-cfb

### What is your config in detail (with all sensitive info masked)?

实际是我的加密方式是aes-256-gcm ,而web显示aes-256-cfb,因此二维码也是错的。
使用的是shadowsocks-python

**Comment by gyteng** [comment]
在服务器页面调整
