### ISSUE TITLE
新建管理员帐号无法看到所有用户

### ISSUE THREAD

**Issue by reizhi** [shadowsocks/shadowsocks-manager#468]
### What version of shadowsocks-manager are you using?
0.26.8

### What operating system are you using?
Debian

### What version of Node.js are you using?
v8.11.4

### What did you do?
通过后台新建管理员帐号X

### What did you expect to see?
系统中共有152个非管理员用户，其中123个默认组用户，29个特殊组用户。

### What did you see instead?
创始帐号可以看到全部152个用户，X帐号只能看到123个默认组用户。将X切换到特殊组后只能看到29个特殊组用户。
似乎X只是组管理员，如何将其设置为全局管理员？

**Comment by gyteng** [comment]
目前就是这么设计的
