### ISSUE TITLE
超级小白白痴问题，望回复。

### ISSUE THREAD

**Issue by moguogui** [shadowsocks/shadowsocks-manager#48]
`Nodejs  4.4
Mongodb 3.2
Install

git clone https://github.com/shadowsocks/shadowsocks-manager.git
npm install -g bower
cd shadowsocks-manager
npm install
bower install
Usage

cd shadowsocks-manager
mv config.js.sample config.js
node server`

已按照上述流程安装。请问最终的管理界面怎么调阅出来？还是说，需要安装别的东西？

**Comment by glasswm** [comment]
用浏览器访问！！！ http://ip或域名:6003
config里面有端口
