### ISSUE TITLE
能否添加-r启动时ss-manager的参数传入接口？

### ISSUE THREAD

**Issue by tzwjkl** [shadowsocks/shadowsocks-manager#488]
### What version of shadowsocks-manager are you using?
0.27.2

### What operating system are you using?
CentOS Linux release 7.5.1804 (Core)

### What version of Node.js are you using?
nodejs.x86_64 8.12.0-1nodesource

### What did you do?
```
ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000 --plugin obfs-server --plugin-opts "obfs=http"
ssmgr -c ss.yml
```

### What did you expect to see?
ssmgr -r 快速启动ss-manager时，用户能附带其他参数
例如`--plugin obfs-server --plugin-opts "obfs=http"`

### What did you see instead?
在用户需要使用Shadowsocks plugin时，无法同时使用ssmgr -r方式启动ss-manager。

**Comment by lol2025** [comment]
此功能未来会不会加到项目里？现在不加tls已经没法用了。

**Comment by jizusun** [comment]
同需要 obfs
