### ISSUE TITLE
每次更新m端需重新拷贝自定义skin文件，能否像icon一样放置于.ssmgr下

### ISSUE THREAD

**Issue by fastss** [shadowsocks/shadowsocks-manager#489]
### What version of shadowsocks-manager are you using?
0.27.2

### What operating system are you using?
Ubuntu1804

### What version of Node.js are you using?
8

### What did you do?
更新m端

### What did you expect to see?
每次更新m端需重新拷贝自定义skin文件至skin文件夹，能否像icon一样放置于.ssmgr下，避免重复设置

**Comment by gyteng** [comment]
欢迎提皮肤的pr
