### ISSUE TITLE
自动分配免费节点not work

### ISSUE THREAD

**Issue by glasswm** [shadowsocks/shadowsocks-manager#49]
admin登录进去后，添加了本地ss服务器，然后配置里打开了自动分配免费节点。

但新注册用户后分配不到免费服务器，+1s也看不到服务器，请问还需要啥配置吗？

**Comment by gyteng** [comment]
"选择服务器" "流量" "时间" 这三项有无填写？

在 2016年8月31日 下午4:32，glasswm <notifications@github.com>写道：

**Comment by glasswm** [comment]
填了，选的是新创建的127.0.0.1那个服务器，100M，12小时

**Comment by glasswm** [comment]
![default](https://cloud.githubusercontent.com/assets/7582070/18122246/10954068-6f9b-11e6-910f-e49a8d866383.png)

**Comment by gyteng** [comment]
请贴日志文件的内容出来

2016-08-31 16:50 GMT+08:00 glasswm <notifications@github.com>:

**Comment by glasswm** [comment]
日志没特别的显示，就是XX成功续了一秒。

刚瞎测成功了，过程是先用admin创建了一个端口，然后再普通用户登录进去点续一秒，就可以获取顺延端口了。是否未创建任何端口时无法进行免费分配？
