### ISSUE TITLE
ss订阅链接，在客户端上服务器名称显示乱码问题

### ISSUE THREAD

**Issue by siriusfinex** [shadowsocks/shadowsocks-manager#498]
如图所示：

![image](https://user-images.githubusercontent.com/31554433/48107535-048cef00-e27b-11e8-9a55-98813f760f69.png)

### What version of shadowsocks-manager are you using?
0.27.9

### What operating system are you using?
debian 9

### What version of Node.js are you using?
Node.js 10

**Comment by limaofeng** [comment]
真的解决了吗？
