### ISSUE TITLE
[Fixed][Upgrade from 0.21.3 to 0.28.9 database error, no ports list up in Account

### ISSUE THREAD

**Issue by myfingerhurt** [shadowsocks/shadowsocks-manager#512]
- What version of shadowsocks-manager are you using?
0.21.3 vs 0.28.9

- What operating system are you using?
Ubuntu 16.04

- What version of Node.js are you using?
V8.0.0

- What did you do?
Upgrade from 0.21.3 to 0.28.9

- What did you expect to see?
Account menu can list up all pre-existed ports.

- What did you see instead?
An empty list, and malfunctioning WebUI.

- What is your config in detail (with all sensitive info masked)?
Same as the previous version 0.21.3

-------------------------------

### Error logs:
```
[2018-12-10T15:21:23.184] [ERROR] express - [10.9.8.6:8080] [undefined] GET 403 18ms /api/admin/account
{ Error: SQLITE_ERROR: no such column: account_plugin.autoRemoveDelay errno: 1, code: 'SQLITE_ERROR' }
```
### Reason
The Databases are different between two versions.
account_plugin.autoRemoveDelay is missing.
### Solution 

Here is the fix.
```
alter table account_plugin add column autoRemoveDelay bigint default 0
```

**Comment by gyteng** [comment]
https://shadowsocks.github.io/shadowsocks-manager/#/upgrade
