### ISSUE TITLE
shadowsocks only supports commands add/remove/ping

### ISSUE THREAD

**Issue by luvletter1205** [shadowsocks/shadowsocks-manager#533]
### What version of shadowsocks-manager are you using?
```
$ npm list --global |grep shadowsocks
└─┬ shadowsocks-manager@0.29.14
```

### What operating system are you using?
```
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```

### What version of Node.js are you using?
```
$ npm -v
5.8.0
$ nodejs -v
v8.11.4
```

### What did you do?
i install shadowsocks via pip and shadowsocks-manager via npm.
i setup ssmgr(m) in this config:
```
type: s

shadowsocks:
  address: 127.0.0.1:6001
manager:
  address: 0.0.0.0:4001
  password: '*********'
db: 'ss.sqlite'
```
and start shadowsocks by ` ssserver -c /path/to/ss_conf.json --manager-address 127.0.0.1:6001 -d start`

but i got this in /var/log/shadowsocks.log:
```
2019-01-09 21:58:55 INFO     entering manager mode
2019-01-09 21:58:57 INFO     adding server at 0.0.0.0:4430
2019-01-09 21:58:57 INFO     adding server at 0.0.0.0:10000
2019-01-09 21:58:57 INFO     adding server at 0.0.0.0:10001
2019-01-09 21:58:57 INFO     adding server at 0.0.0.0:10002
                 -----balabala-----
2019-01-09 21:59:00 ERROR    unknown command list
2019-01-09 21:59:00 ERROR    unknown command list
2019-01-09 21:59:00 ERROR    server already exists at 0.0.0.0:4430
2019-01-09 21:59:00 ERROR    server already exists at 0.0.0.0:10000
2019-01-09 21:59:00 ERROR    server already exists at 0.0.0.0:10001
2019-01-09 21:59:00 ERROR    server already exists at 0.0.0.0:10002
                 -----balabala-----
```
it seems that shadowsocks-manager cannot get the existing server(port) listening and it is trying to add repeating servers.

### What did you expect to see?
not adding repeating servers

### What did you see instead?
as above

### What is your config in detail (with all sensitive info masked)?
ssmgr(s) is above
and shadowsocks config is following
```
{
    "server":"0.0.0.0",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
     },
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open":true
}
```
I delete all ports in ss config file because I want use ssmgr to add.
BUT if I add all ports in ss config and set nothing in ssmgr, ssmgr is trying to remove server which is flowing traffic BUT not included in ssmgr's database

Main Point:
ssmgr dont know existing server in shadowsocks
Problems may come from shadowsocks `manager.py (Line 124)`. It only support commands `add/remove/ping`

**Comment by gyteng** [comment]
use `shadowsocks-libev` or [`this fork`](https://github.com/gyteng/shadowsocks)

**Comment by luvletter1205** [comment]
Roger. I will test it later. Thanks

**Comment by luvletter1205** [comment]
would you replace shadowsocks Main repo 's `manager.py` with your repo's `manager.py`

**Comment by gyteng** [comment]
I have make a pull request, depends the owner
