### ISSUE TITLE
你好，请问这个有流量限制功能吗？

### ISSUE THREAD

**Issue by AloneFrog** [shadowsocks/shadowsocks-manager#54]

**Comment by gyteng** [comment]
有

2016年9月5日 13:07，"AloneFrog" <notifications@github.com>写道：

**Comment by AloneFrog** [comment]
可以在PC端后台管理吗？需要lnmp环境吗？多谢

**Comment by gyteng** [comment]
pc端手机端都可以，不需要lnmp，但是需要node和mongodb

2016-09-05 13:50 GMT+08:00 AloneFrog <notifications@github.com>:

**Comment by AloneFrog** [comment]
多谢，我部署一下看，到时候会反馈给您，这个可以作为商业SS的管理后台吗？

**Comment by gyteng** [comment]
请参考GPL协议

2016-09-05 13:56 GMT+08:00 AloneFrog <notifications@github.com>:

**Comment by AloneFrog** [comment]
你好，我不会拿去销售，只是给自己的SS服务做后台，如果公开的话，一定附上您的署名和本项目的github地址
