### ISSUE TITLE
how to configure the wireguard server for shadowsocks-manager?

### ISSUE THREAD

**Issue by Arhimad** [shadowsocks/shadowsocks-manager#542]
Where to see how to configure the wireguard server for shadowsocks-manager, is there an instruction?

**Comment by gyteng** [comment]
https://shadowsocks.github.io/shadowsocks-manager/#/wireguard

**Comment by Arhimad** [comment]
this configuration does not work as it should

1. does not transmit the private key, and the application does not accept the qr code
![2019-02-20_20-17-09 3](https://user-images.githubusercontent.com/34145993/53089019-bb715a00-354e-11e9-9a52-de5dfd6a7ba1.png)

2. In this configuration (https://shadowsocks.github.io/shadowsocks-manager/#/wireguard), there can be no multi-users, the Wireguard server allows only one user

it will be correct if a separate interface will be created for each user on the wireguard server
