### ISSUE TITLE
Can't login on WebGUI because Docker image doesn't have Redis installed 

### ISSUE THREAD

**Issue by Lanfei** [shadowsocks/shadowsocks-manager#544]
### What version of shadowsocks-manager are you using?
0.30.17

### What operating system are you using?
Docker/Ubuntu

### What version of Node.js are you using?
Docker/Node 8

### What did you do?
Login on WebGUI

### What did you expect to see?
Successfully login

### What did you see instead?
500 Error

### What is your config in detail (with all sensitive info masked)?
Nothing special

**Comment by gyteng** [comment]
run redis in another container
