### ISSUE TITLE
cannot login to webgui

### ISSUE THREAD

**Issue by lucapxl** [shadowsocks/shadowsocks-manager#547]
### What version of shadowsocks-manager are you using?
0.30.19

### What operating system are you using?
Ubuntu 16.04.5 LTS

### What version of Node.js are you using?
v10.15.1

### What did you do?
git clone https://github.com/shadowsocks/shadowsocks-manager.git
cd shadowsocks-manager
npm i
npm run-script build
ssserver -m aes-256-cfb -p 12345 -k abcedf --manager-address 127.0.0.1:6001
node server.js -c /root/.ssmgr/manager.yml 
node server.js -c /root/.ssmgr/webgui.yml 

created a user, received the email with the code. inserted the code with a new password and the spinner (dialog) remains there. no login

### What did you expect to see?
I expected the user to login

### What did you see instead?
the spinner (dialog) keeps rotating

### What is your config in detail (with all sensitive info masked)?
manager.yml:

type: s

shadowsocks:
  address: 127.0.0.1:6001

manager:
  address: 0.0.0.0:6379
  password: '123456'

db: 'ss.sqlite'

webgui.yml:
type: m

manager:
  address: 127.0.0.1:6379
  password: '123456'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    username: '********'
    password: '********'
    host: '********'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'

db: 'webgui.sqlite'

**Comment by ken-gor** [comment]
Redis is required

**Comment by lucapxl** [comment]
after installing redis server (apt-get install redis-server) and changing the port of the manager everything works fine. 

another small issue I have is that when creating an account it creates a qrcode for the host 127.0.0.1, where can I set the IP address of the server for the users to see the right one?

thanks

**Comment by lucapxl** [comment]
after installing redis server (apt-get install redis-server) and changing the port of the manager everything works fine
