### ISSUE TITLE
安装完后输入http://ip_address:6003/一片空白

### ISSUE THREAD

**Issue by fy138** [shadowsocks/shadowsocks-manager#55]
查看html代码输出以下内容
`
<html lang="zh-cn">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <link rel="stylesheet" href="/libs/angular-material/angular-material.min.css">
    <link rel="stylesheet" href="/public/assets/css/home.css">
    <link rel="shortcut icon" href="/public/assets/img/favicon.png"> 
    <title>Shadowsocks Manager</title>
    <base href="/">
</head>

<body ng-app="LoginApp" ng-cloak>
    <script src="/libs/angular/angular.min.js"></script>
    <script src="/libs/angular-animate/angular-animate.min.js"></script>
    <script src="/libs/angular-aria/angular-aria.min.js"></script>
    <script src="/libs/angular-messages/angular-messages.min.js"></script>
    <script src="/libs/angular-material/angular-material.min.js"></script>
    <script src="/libs/angular-ui-router/release/angular-ui-router.min.js"></script>
    <script src="/libs/fingerprintjs2/dist/fingerprint2.min.js"></script>

    
    <script src="/public/routes/home.js"></script>
    

    
    <script src="/public/controllers/home.js"></script>
    
    <div ng-controller="MainController">
        <div ui-view></div>
    </div>
</body>

</html>`

**Comment by gyteng** [comment]
请检查console里边是否有报错

2016-09-06 14:40 GMT+08:00 F.Y <notifications@github.com>:
