### ISSUE TITLE
https://shadowsocks.github.io/shadowsocks-manager/#/wireguard

### ISSUE THREAD

**Issue by Arhimad** [shadowsocks/shadowsocks-manager#552]
this configuration does not work as it should

1. does not transmit the private key, and the application does not accept the qr code
![2019-02-20_20-17-09 4](https://user-images.githubusercontent.com/34145993/53089607-62a2c100-3550-11e9-8ac7-d56a00be5212.png)

2. In this configuration (https://shadowsocks.github.io/shadowsocks-manager/#/wireguard), there can be no multi-users, the Wireguard server allows only one user

it will be correct if a separate interface will be created for each user on the wireguard server

**Comment by gyteng** [comment]
2. WireGuard server will create multi peers for every user.

**Comment by Arhimad** [comment]
![2019-02-21_09-33-36](https://user-images.githubusercontent.com/34145993/53134922-86035580-35bc-11e9-8f09-96831f0dc73a.png)

how ?

and how s-maneger to enter the private key that he passed it to the client?

each client must have its own private key
