### ISSUE TITLE
你好，已经安装成功，但是ip+6003打不开网页

### ISSUE THREAD

**Issue by AloneFrog** [shadowsocks/shadowsocks-manager#56]

**Comment by gyteng** [comment]
请贴出浏览器报错的具体内容，检查 bower install 这一步是否有报错

2016-09-09 8:47 GMT+08:00 AloneFrog <notifications@github.com>:

**Comment by AloneFrog** [comment]
无法显示此页

•确保 Web 地址 http://163.44.113.146:6003  正确。
•使用搜索引擎查找页面。
•请过几分钟后刷新页面。

**Comment by AloneFrog** [comment]
无法显示此页

•确保 Web 地址 http://ip:6003  正确。
•使用搜索引擎查找页面。
•请过几分钟后刷新页面。

**Comment by gyteng** [comment]
请贴出浏览器调试窗口console页面的内容

2016-09-09 9:49 GMT+08:00 AloneFrog <notifications@github.com>:

**Comment by AloneFrog** [comment]
Failed to load resource: net::ERR_CONNECTION_REFUSED
http://163.44.113.146:6003/:1 GET http://163.44.113.146:6003/ net::ERR_CONNECTION_REFUSED

**Comment by AloneFrog** [comment]
Failed to load resource: net::ERR_CONNECTION_REFUSED
http://ip:6003/:1 GET http://ip:6003/ net::ERR_CONNECTION_REFUSED

**Comment by gyteng** [comment]
网络不通，请检查你的防火墙或者其他什么配置

2016-09-09 10:00 GMT+08:00 AloneFrog <notifications@github.com>:

**Comment by AloneFrog** [comment]
debian7  没有安装防火墙

**Comment by gyteng** [comment]
建议你把具体情况说清楚，否则我也没办法帮你

**Comment by AloneFrog** [comment]
我也不知道从哪说起，您需要知道什么信息？

**Comment by nailuoGG** [comment]
查看下iptables吧，vps厂商为了安全一般会屏蔽80和443之外的所有端口。
