### ISSUE TITLE
更新后无法监测流量

### ISSUE THREAD

**Issue by zeroex000** [shadowsocks/shadowsocks-manager#561]
### What version of shadowsocks-manager are you using?
0.31.7

### What operating system are you using?
CentOS7

### What version of Node.js are you using?
v10.15.1

### What did you do?
消耗流量

### What did you expect to see?
监测流量变化

### What did you see instead?
流量没变化

### What is your config in detail (with all sensitive info masked)?
配置没有修改，应该是正常的

一开始配置完是正常的，直到我升级了Linux内核，更新了新的aliyun监控
就无法监控流量了，流量一直为空，而且看了日志没有报错，
请问下有没有方法排查问题。

**Comment by zeroex000** [comment]
补充下：
ss.sqlite里的数据是正常的
webgui.sqlite里的数据不对

**Comment by zeroex000** [comment]
发现所有cron.minute都没有执行=。=但是没报错

**Comment by gyteng** [comment]
清空redis

**Comment by drshiki** [comment]
> 发现所有cron.minute都没有执行=。=但是没报错

你怎么知道没有执行的，我清空了redis就行了。但是我也不知道为什么，我输入
```
HoigimdeMac-mini:logs hoigimdang$ pwd
/Users/hoigimdang/woking2/.ssmgr/logs
HoigimdeMac-mini:logs hoigimdang$ grep -rn ERROR  ./
HoigimdeMac-mini:logs hoigimdang$
```
没有错误呢，webmgr和ssmgr都查了

**Comment by jizusun** [comment]
> 清空redis

是这样吗？

```
redis-cli FLUSHALL
```

但是flush之后，今日流量会显示为所使用的流量之和，效果不是很用户友好。
