### ISSUE TITLE
登录一直提示网络异常

### ISSUE THREAD

**Issue by KmustXH** [shadowsocks/shadowsocks-manager#565]
登陆的时候一直提示网络异常请稍后再试怎么办， User[xh970307@163.com] login fail: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.

**Comment by kc910521** [comment]
同样我也有这个问题

> ESC[91m[2019-03-09T12:50:42.882] [ERROR] webgui - ESC[39mUser[779348407@qq.com] login fail: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
ESC[91m[2019-03-09T12:50:42.892] [ERROR] express - ESC[39m[45.63.95.28] [undefined] POST 500 33511ms /api/home/login

**Comment by KmustXH** [comment]
这个问题我解决了，是因为现在这个ssnanager的版本，需要在webgui.yml加一段radies的配置




| |
熊航
|
|
邮箱：xh970307@163.com
|

签名由 网易邮箱大师 定制

在2019年03月09日 20:54，kc910521 写道：

同样我也有这个问题

ESC[91m[2019-03-09T12:50:42.882] [ERROR] webgui - ESC[39mUser[779348407@qq.com] login fail: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
ESC[91m[2019-03-09T12:50:42.892] [ERROR] express - ESC[39m[45.63.95.28] [undefined] POST 500 33511ms /api/home/login
