### ISSUE TITLE
Installed according to documentation, but nothing appears when browsing to the server url

### ISSUE THREAD

**Issue by baselkhateeb** [shadowsocks/shadowsocks-manager#58]
I installed shadowsocks, shadowsocks manager, mongodb, nodejs, bower, ran everything without errors.
but when navigating to the shadowsocks URL, it finds the server, but I get an empty page.
Did I miss something?

**Comment by gyteng** [comment]
Maybe something wrong in step 'bower install'.

**Comment by baselkhateeb** [comment]
Ooops, I figured that I'm using the default shadowsocks version I installed using apt-get install shadowsocks, which is outdated, just installed version 2.9.0 manually and it worked
