### ISSUE TITLE
Can't create user account neither login with the admin account

### ISSUE THREAD

**Issue by baselkhateeb** [shadowsocks/shadowsocks-manager#59]
When I try to register a user from the UI, I get the error message "当前时段尚未开放注册" which indicates that registration isn't open yet.
I've also tried to login with the admin credentials mentioned in the "config.js" but I also get an error telling me that I'm not registered.
what the heck?

**Comment by gyteng** [comment]
If you set the password of mongodb, check the config.js file, maybe something wrong with the username or password.

**Comment by baselkhateeb** [comment]
I tried with a mongodb password and without it. but still the same.
I created a database user on "Shadowsocks-Manager" db and granted it a dbOwner role.
Shadowsocks manager is connecting correctly to the database, but, I create create or login to Shadowsocks-manager.

**Comment by gyteng** [comment]
Is there any data is mongodb after your first run the server.js?

**Comment by baselkhateeb** [comment]
Not really,, I think I will abandon shadowsocks-manager, it seems very buggy
