### ISSUE TITLE
当勾选显示流量信息时，无法访问ss订阅链接

### ISSUE THREAD

**Issue by sSAidenSs** [shadowsocks/shadowsocks-manager#598]
### What version of shadowsocks-manager are you using?
0.32.36

### What operating system are you using?
Debian 9

### What version of Node.js are you using?
v10.16.0

### What did you do?
获取订阅链接时，当勾选显示流量信息后，即链接参数flow=1时，获取订阅链接时出错
不勾选显示流量的话(flow=0)，则能正常获得返回值
<img width="502" alt="图片" src="https://user-images.githubusercontent.com/28475751/61861892-712a4580-aeff-11e9-91c5-252943048459.png">
错误信息如下
![图片](https://user-images.githubusercontent.com/28475751/61862270-32e15600-af00-11e9-9ca7-4c1268d77d49.png)

**Comment by gyteng** [comment]
无法重现这个问题
