### ISSUE TITLE
Getting error while setting up!

### ISSUE THREAD

**Issue by Super-Gil** [shadowsocks/shadowsocks-manager#600]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
latest

### What operating system are you using?
Ubuntu 18.04 LTS

### What version of Node.js are you using?
Latest

### What did you do?
I was following all the instructions from installing node.js to using "npm i" command then an error occured

### What did you expect to see?
things are all ready to go!

### What did you see instead?
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9

### What is your config in detail (with all sensitive info masked)?
I am not sure what do you mean by config
I am using AWS EC2 what I did is only
"apt-get update"
"apt-get upgrade"
"apt-get install node.js"
"apt-get install redis"
"apt-get install npm"
"git clone https://github.com/shadowsocks/shadowsocks-manager.git"
"cd shadowsocks-manager"
"npm i"

after "npm i" I got an error
" notsup Not compatible with your operating system or architecture: fsevents@1.2.9"

Is that all fine to go forward to setup ss server? Would security problem happen without "notsup"?

**Comment by gyteng** [comment]
https://github.com/nodesource/distributions
