### ISSUE TITLE
config.js 修改如何生效

### ISSUE THREAD

**Issue by cobb000** [shadowsocks/shadowsocks-manager#61]
你好，我是业余计算机爱好者，你教程里没有详细写如何使用，例如添加服务器时候，有个管理端口，我并不记得ss安装时候有什么管理端口啊？？这个端口是随便填的吗？？？、
还有就是config.js里面的内容修改后如何生效？那一步时候修改？我修改后重启服务还是不行啊，只能用你原来的youremailadderss@gmail.com登陆。
网上有其他的一些多用户管理程序，但是我看了需要安装mysql，由于机器的内存比较小，而且感觉没有必要。你的mongodb应该是轻量级的吧。但是确实有点弄不明白怎么使用。
我的安装了你的多用户管理，之前的ss中config.json中添加的多用户还是可以登录，要删除config.json吗？

**Comment by gyteng** [comment]
管理端口请参考[文档](https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users)，
config.js里的管理员邮箱会首次启动时写入数据库，需要修改必须清空数据库再运行。
