### ISSUE TITLE
webgui: servers incorrectly indicated as offline

### ISSUE THREAD

**Issue by d72337** [shadowsocks/shadowsocks-manager#612]
### What version of shadowsocks-manager are you using?
0.33.23

### What operating system are you using?
Ubuntu 16.04

### What version of Node.js are you using?
10+

### What is the issue?
When the server (SSM with libev) is not used for about 2h+ , on webgui this server indicated as red (offline), but he is working and bandwidth is counting.
https://c2n.me/43VSDwx.png

### What is your config in detail (with all sensitive info masked)?
plugins: flowSaver, user, account, giftcard, group, email, webgui_telegram, webgui
webgui DB: mysql , redis
SSM db: sqlite

**Comment by gyteng** [comment]
red means your server **might** be banned by gfw
