### ISSUE TITLE
[Feature Request] Adding a New Server Quickly by Duplicating an Existing One

### ISSUE THREAD

**Issue by gadflysu** [shadowsocks/shadowsocks-manager#619]
### What version of shadowsocks-manager are you using?

0.33.43

### What operating system are you using?

Ubuntu 18.04 x64

### What version of Node.js are you using?

v10.18.1

### What did you do?

Add a new server.

### What did you expect to see?

Adding a new server **quickly** by **duplicating an existing one**. After clicking a "Duplicate" button, get into the server-adding page with filled parameters that are the same with those of the server duplicated from.

### What did you see instead?

It is too much trouble to manually fill in the parameters that are almost similar between servers **step by step**.

### What is your config in detail (with all sensitive info masked)?

No need to provide.

**Comment by gyteng** [comment]
When you have more than one server, which will be the chosen one?

**Comment by gadflysu** [comment]
The interaction process could be that **firstly choose one server then duplicate it**. For example, the "Duplicate" button could be in the top-right menu of the server card or be a FAB on the server info page (e.g. `/admin/server/1`).

Thank you for your following up on this issue. @gyteng

**Comment by gyteng** [comment]
added in version 0.35.17
