### ISSUE TITLE
安装完了怎么使用?

### ISSUE THREAD

**Issue by youuoypi** [shadowsocks/shadowsocks-manager#62]
如题.管理界面怎么使用?没有说明...

**Comment by gyteng** [comment]
请具体说明你卡在哪一步

**Comment by youuoypi** [comment]
命令行安装完了.具体操作是什么?比如查看各个账号的流量.添加删除用户.

**Comment by gyteng** [comment]
配置好config.js，然后运行程序，进入网页管理界面

2016-10-02 17:19 GMT+08:00 youuoypi <notifications@github.com>:
