### ISSUE TITLE
mysql环境下sql报错。

### ISSUE THREAD

**Issue by gitsamyivan** [shadowsocks/shadowsocks-manager#623]
错误log：
  code: 'ER_WRONG_FIELD_WITH_GROUP',
  errno: 1055,
  sqlMessage: 'Expression #11 of SELECT list is not in GROUP BY clause and contains nonaggregated column \'ssmgr.account_plugin.port\' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by',
  sqlState: '42000',
  index: 0,
  sql: 'select `user`.`id` as `id`, `user`.`username` as `username`, `user`.`email` as `email`, `user`.`telegram` as `telegram`, `user`.`password` as `password`, `user`.`type` as `type`, `user`.`createTime` as `createTime`, `user`.`lastLogin` as `lastLogin`, `user`.`resetPasswordId` as `resetPasswordId`, `user`.`resetPasswordTime` as `resetPasswordTime`, `account_plugin`.`port` as `port` from `user` left join `account_plugin` on `user`.`id` = `account_plugin`.`userId` where `user`.`id` > 1 and `user`.`type` in (\'normal\', \'admin\') group by `user`.`id` order by `id` asc limit 80' }
[2020-03-01T14:46:08.948] [ERROR] express - [192.168.1.3:7001] [undefined] GET 403 41ms /api/admin/user?group=-1&page=1&pageSize=80&search=&sort=id_asc&type=normal&type=admin

**Comment by gitsamyivan** [comment]
plugins/user/index.js

  let users = knex('user').select([
    'user.id as id',
    'user.username as username',
    'user.email as email',
    'user.telegram as telegram',
    'user.password as password',
    'user.type as type',
    'user.createTime as createTime',
    'user.lastLogin as lastLogin',
    'user.resetPasswordId as resetPasswordId',
    'user.resetPasswordTime as resetPasswordTime',
    'account_plugin.port as port',
  ]).leftJoin('account_plugin', 'user.id', 'account_plugin.userId')
  .where('user.id', '>', 1)
  .whereIn('user.type', type).groupBy('user.id');


groupBy('user.id');  //groupBy导致错误，mysql报错。

**Comment by gitsamyivan** [comment]
放弃了，居然不兼容chrome  
登录首页报错
TypeError: t.setTitle is not a function
    at new <anonymous> (VM56 bundle.js:1)
    at Object.instantiate (VM55 lib.js:48)
    at VM55 lib.js:101
    at Object.<anonymous> (VM55 lib.js:838)
    at VM55 lib.js:20
    at Ba (VM55 lib.js:92)
    at p (VM55 lib.js:76)
    at g (VM55 lib.js:67)
    at VM55 lib.js:67
    at VM55 lib.js:72 "<div scroll="" class="scroll-container ng-scope" ui-view="" flex="" autoscroll="true">"

**Comment by ken-gor** [comment]
当使用5.7或更高版本的 MySQL 时，必须关闭only_full_group_by这个特性
