### ISSUE TITLE
部署后无法访问

### ISSUE THREAD

**Issue by mikan2000** [shadowsocks/shadowsocks-manager#63]
2.0版本，昨天部署的1.0没任何问题

这是log信息

/usr/local/lib/node_modules/shadowsocks-manager/
[2016-10-09 13:28:51.292] [INFO] init - Server start.
server listen on 0.0.0.0:6002
Send to shadowsocks: remove: {"server_port": 6666}
[ { port: 6666, flow: 22876, time: 1475990948953 } ]

请问config各项代表什么

**Comment by gyteng** [comment]
目前2.0版本正在开发中，请使用1.0版本
