### ISSUE TITLE
Use MAC and IP to allow only one user connection to proxy

### ISSUE THREAD

**Issue by Rmkek** [shadowsocks/shadowsocks-manager#658]
### What version of shadowsocks-manager are you using?
0.36.29

### What operating system are you using?
Ubuntu 20.04.1 LTS, kernel 5.4.0

### What version of Node.js are you using?
v10.19.0, npm v6.14.4

### What did you do?
Turned on MAC account filtration in admin page.

### What did you expect to see?
Only one user will be able to connect to one shadowsocks port, other user's traffic will not pass through.

### What did you see instead?
All users are still able to connect to the same port and use it concurrently.

### What is your config in detail (with all sensitive info masked)?
type: m

manager:
  address: 127.0.0.1:6002
  password: 'xxx'

devEnv: false

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    username: 'noreply@xxx.com'
    password: 'xxx'
    host: 'xxx.com'
    #secure: false
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://xxx.com'

db: 'webgui.sqlite'

--------------------------------------------------
I might be wrong thinking that MAC/IP should work like that, blocking other connections on the same proxy port, if that's where I'm wrong, can you please elaborate on how MacAccount should be used?

**Comment by gyteng** [comment]
It use for some client on the router, login with mac address instead of username/password.
