### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by yanxurui** [shadowsocks/shadowsocks-manager#66]
Because I am new to node, I encounter a question when I use this tool.
![image](https://cloud.githubusercontent.com/assets/12461110/19340792/35e92530-915d-11e6-911e-86927c82eba4.png)

node is indeed in /usr/bin.

Please help me. Thank you!

**Comment by gyteng** [comment]
Version 2 is not a stable version, it may have some bugs.
Maybe you can install from npm again and try it, I just fix the \r bug.

2016-10-13 15:55 GMT+08:00 晏旭瑞 <notifications@github.com>:
