### ISSUE TITLE
想探讨一下 node 应用的在线更新可行性

### ISSUE THREAD

**Issue by kmvan** [shadowsocks/shadowsocks-manager#669]
node 应用并不像 php 这些替换了文件就可以生效，有些文件甚至需要重新编译打包。那么问题来了，如果把新版的已打包编译的文件，做法更新包分发，web 端实现解压缩替换并重启 node server，这种是否可行？如果有 node_modules 更新，就更新 package.json 并 process 执行 npm i 更新，这样可行？

**Comment by gyteng** [comment]
流行的做法一般是用容器解决

**Comment by kmvan** [comment]
确实容器更新比较简单，但这有一个问题了，对容器内的操作，对于只会用web管理面板的用户来说，几乎没法操作啊。
