### ISSUE TITLE
can not run successfully from master branch code

### ISSUE THREAD

**Issue by ynhzzu** [shadowsocks/shadowsocks-manager#67]
#bin/ssmgr -t s -s 127.0.0.1:6001 -m 0.0.0.0:6002

/usr/local/shadowsocks-manager/
Unhandled Rejection at: Promise Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: [RangeError: Offset + length beyond buffer length],
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined } reason: [RangeError: Offset + length beyond buffer length]
/usr/local/shadowsocks-manager/services/server.js:120
  throw err;
  ^

Error: listen EADDRINUSE 0.0.0.0:6002
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at net.js:1395:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)

**Comment by gyteng** [comment]
I am not sure if the 6002 port is used by other program

**Comment by zinian** [comment]
#ssmgr -t s -s 127.0.0.1:6001 -m 0.0.0.0:6002
/usr/lib/node_modules/shadowsocks-manager/
server listen on 0.0.0.0:6002
[String: 'stat: {}']
{}

[String: 'stat: {}']
{}

[String: 'stat: {}']
{}

**Comment by ynhzzu** [comment]
lsof -i:6002
not pid is exist

environment:
centos7.2
shadowsocks2.9.0
node4.5.0

**Comment by gyteng** [comment]
maybe you can update node to 6.x and try it

2016年10月13日 18:18，"yangzzu" <notifications@github.com>写道：

**Comment by ynhzzu** [comment]
Got it!
I update node version from 4.x to 6.x.
But the index page is empty after I start it.
What should I change in config/default.yaml?

**Comment by gyteng** [comment]
I will let it work in the node 4.x a few days later.
Now the webgui of version 2 haven't finished, you have to wait or use
version 1.

2016-10-13 22:26 GMT+08:00 yangzzu <notifications@github.com>:

**Comment by ynhzzu** [comment]
OK,thanks!
The version 1 is need to much memory!
