### ISSUE TITLE
教程没看懂，帮忙解惑

### ISSUE THREAD

**Issue by jearton** [shadowsocks/shadowsocks-manager#673]
我已经用docker方式安装好了shadowsocks-libev+v2ray-plugin，并且已经能成功fq，请问接下来我想继续用docker安装shadowsocks-manager，要怎么搞？

**Comment by ChaosTop** [comment]
2021年9月6日 上午12:57，zhoudong ***@***.******@***.***>> 写道：



我已经用docker方式安装好了shadowsocks-libev+v2ray-plugin，并且已经能成功fq，请问接下来我想继续用docker安装shadowsocks-manager，要怎么搞？

**Comment by jearton** [comment]
已解决，用docker启动ss-manager暂时无解，还是用了传统安装方式
