### ISSUE TITLE
服务器好像访问不了了，请问什么时候能够修复呢？

### ISSUE THREAD

**Issue by gpsbird** [shadowsocks/shadowsocks-manager#679]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

**Comment by iquanxin** [comment]
1

**Comment by iquanxin** [comment]
刚充过季度就不能用了嘛〜

**Comment by devilmengcry** [comment]
同问，通通超时了，怎么回事。

**Comment by 1228029643** [comment]
充了年度的可怎么办？

**Comment by potazinc** [comment]
同，充了半年没用完呢

**Comment by cybibo** [comment]
1

**Comment by tianfuchao** [comment]
何时恢复

**Comment by imaoxian** [comment]
https://app.3840x2160.work/ 所有节点都无法用了，半个月了，请问什么时候能恢复呢？

**Comment by anjie0818** [comment]
同问

**Comment by ov-vo** [comment]
我的年费啊，心痛💔
