### ISSUE TITLE
账号设置了type为3（天），过期时间是一个月后，发现每天已使用流量都会重置

### ISSUE THREAD

**Issue by meet1102cyt** [shadowsocks/shadowsocks-manager#686]
账号设置了type为3（天），过期时间是一个月后，发现每天已使用流量都会重置 ，这块需要如何设置使用流量不会重置

**Comment by yunmin574269** [comment]
账号设置了type为3（天），过期时间是一个月后，发现每天已使用流量都会重置 ，这块需要如何设置使用流量不会重置
