### ISSUE TITLE
Version2 still need mongodb？

### ISSUE THREAD

**Issue by hack-skylin** [shadowsocks/shadowsocks-manager#70]
RT

Should i install mongodb for run V2?

**Comment by gyteng** [comment]
No, V2 use sqlite instead of mongodb.
Now there are some bugs in V2, I suggest u to use it later.

2016-10-19 14:54 GMT+08:00 hack-skylin <notifications@github.com>:

**Comment by hack-skylin** [comment]
OK, thanks
