### ISSUE TITLE
关于ss各个版本的区别？（小白提问...）

### ISSUE THREAD

**Issue by BlingRabbit** [shadowsocks/shadowsocks-manager#71]
大大 您好 我是小白一枚 我想知道关于shadowsocks每个版本的区别如libev go python qt等等
这些都有什么区别呢？区别仅仅是在服务端客户端还是什么？
那些用着好用呢？
路由器上就用的openwrt那个版本对吗？

**Comment by gyteng** [comment]
协议是一样的，只是不同语言的实现。
当然还是会有一点点细微差别。

**Comment by luoyanghero** [comment]
http://www.ttlsa.com/news/popular-science-about-shadowsocks/
