### ISSUE TITLE
有关Wiki的问题

### ISSUE THREAD

**Issue by Too-Naive** [shadowsocks/shadowsocks-manager#72]
![](https://cloud.githubusercontent.com/assets/16496671/19607052/e81edd92-97f9-11e6-9e15-6e475835c5c7.png)

**Comment by gyteng** [comment]
wiki是针对上个版本的，请切换到[这个branch](https://github.com/shadowsocks/shadowsocks-manager/tree/version1)

**Comment by gyteng** [comment]
是的。

**Comment by Too-Naive** [comment]
好的 感谢

**Comment by Too-Naive** [comment]
(建议做出相关说明)

**Comment by gyteng** [comment]
wiki是针对version1的，请把branch切换到对应的

2016年10月22日 02:13，"Unostvisal" <notifications@github.com>写道：

**Comment by gyteng** [comment]
是的，目前新版本尚未完善

2016-10-23 21:43 GMT+08:00 Unostvisal <notifications@github.com>:
