### ISSUE TITLE
missing  config/default.yml

### ISSUE THREAD

**Issue by mashihua** [shadowsocks/shadowsocks-manager#79]
first install shadowsocks-manager v0.3.5 from npm with command `npm i -g shadowsocks-manager`

second run `ssmgr -h` with error
`Error: ENOENT: no such file or directory, stat 'Some path/shadowsocks-manager/lib/config/default.yml'`

**Comment by gyteng** [comment]
It's a bug, I just fix it.
Please install v0.3.6 and try it again.

Thanks for report it.

2016-11-28 11:27 GMT+08:00 Shihua Ma <notifications@github.com>:
