### ISSUE TITLE
安装完成后访问网页显示空白

### ISSUE THREAD

**Issue by rugbbyli** [shadowsocks/shadowsocks-manager#80]
控制台错误如下：

> Error: [$injector:modulerr] http://errors.angularjs.org/1.2.32/$injector/modulerr?p0=LoginApp&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.2.32%2F%24injector%2Fmodulerr%3Fp0%3DngMaterial%26p1%3D%255B%2524injector%253Amodulerr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.2.32%252F%2524injector%252Fmodulerr%253Fp0%253Dmaterial.core%2526p1%253D%25255B%252524injector%25253Aunpr%25255D%252520http%25253A%25252F%25252Ferrors.angularjs.org%25252F1.2.32%25252F%252524injector%25252Funpr%25253Fp0%25253D%25252524mdUtilProvider%25250Az%25252F%25253C%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A6%25253A450%25250Adc%25252Fm.%252524injector%25253C%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A36%25253A202%25250Ac%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A34%25253A305%25250Adc%25252Fm.%252524provide.decorator%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A36%25253A67%25250A%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular-material%25252Fangular-material.min.js%25253A7%25253A6406%25250Ad%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A35%25253A34%25250Ae%25252F%25253C%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A33%25253A386%25250Ar%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A7%25253A288%25250Ae%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A33%25253A207%25250Ae%25252F%25253C%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A33%25253A284%25250Ar%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A7%25253A288%25250Ae%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A33%25253A207%25250Ae%25252F%25253C%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A33%25253A284%25250Ar%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A7%25253A288%25250Ae%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A33%25253A207%25250Adc%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A36%25253A309%25250Acc%25252Fc%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A18%25253A170%25250Acc%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A18%25253A387%25250AXc%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A17%25253A415%25250A%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A217%25253A78%25250Aa%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A146%25253A473%25250Aoe%25252Fc%25252F%25253C%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A31%25253A223%25250Ar%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A7%25253A288%25250Aoe%25252Fc%252540http%25253A%25252F%25252F45.63.127.51%25253A6003%25252Flibs%25252Fangular%25252Fangular.min.js%25253A31%25253A207%25250A%250Az%252F%253C%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A6%253A450%250Ae%252F%253C%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A34%253A97%250Ar%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A7%253A288%250Ae%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A33%253A207%250Ae%252F%253C%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A33%253A284%250Ar%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A7%253A288%250Ae%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A33%253A207%250Ae%252F%253C%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A33%253A284%250Ar%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A7%253A288%250Ae%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A33%253A207%250Adc%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A36%253A309%250Acc%252Fc%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A18%253A170%250Acc%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A18%253A387%250AXc%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A17%253A415%250A%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A217%253A78%250Aa%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A146%253A473%250Aoe%252Fc%252F%253C%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A31%253A223%250Ar%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A7%253A288%250Aoe%252Fc%2540http%253A%252F%252F45.63.127.51%253A6003%252Flibs%252Fangular%252Fangular.min.js%253A31%253A207%250A%0Az%2F%3C%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A6%3A450%0Ae%2F%3C%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A34%3A97%0Ar%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A7%3A288%0Ae%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A33%3A207%0Ae%2F%3C%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A33%3A284%0Ar%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A7%3A288%0Ae%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A33%3A207%0Adc%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A36%3A309%0Acc%2Fc%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A18%3A170%0Acc%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A18%3A387%0AXc%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A17%3A415%0A%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A217%3A78%0Aa%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A146%3A473%0Aoe%2Fc%2F%3C%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A31%3A223%0Ar%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A7%3A288%0Aoe%2Fc%40http%3A%2F%2F45.63.127.51%3A6003%2Flibs%2Fangular%2Fangular.min.js%3A31%3A207%0A
z/<()angular.min.js:6
e/<()angular.min.js:34
r()angular.min.js:7
e()angular.min.js:33
dc()angular.min.js:36
cc/c()angular.min.js:18
cc()angular.min.js:18
Xc()angular.min.js:17
<匿名>angular.min.js:217
a()angular.min.js:146
oe/c/<()angular.min.js:31
r()angular.min.js:7
oe/c()angular.min.js:31
1angular.min.js:6:450

怀疑可能是angular的版本问题？

**Comment by gyteng** [comment]
是的，angular版本过低，请采用1.5版本

**Comment by rugbbyli** [comment]
升级到1.5解决了，谢谢！
