### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadowsocks-manager#84]
按照教程安装后运行出现这个错误提示？

**Comment by gyteng** [comment]
请提供你的Node.js版本以及操作系统版本。

**Comment by DearTanker** [comment]
CentOS6.8最新纯净版
Node.js版本v0.10.46

总之就是刚在Vultr新建的机器，update更新以后就按照教程安装，不管是最新的版本还是version1版本，都是上面的错误

**Comment by gyteng** [comment]
没错，version 1 需要4.*及以上版本，version 2 需要6.*及以上，请升级你的Node.js

2016-12-15 14:58 GMT+08:00 DearTanker <notifications@github.com>:

**Comment by DearTanker** [comment]
额，那就是CentOS自带yum里面的版本太旧的原因吗。。

**Comment by gyteng** [comment]
是的。
