### ISSUE TITLE
use node server.js to run this program. 要如何运行？

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadowsocks-manager#85]
到这一步就发现停住了。已经直接把default.yml里面的用户名和密码修改了。

[root@vultr shadowsocks-manager]# node server.js
use babel-core/register
[2016-12-15 08:31:05.985] [INFO] system - System start.
[2016-12-15 08:31:06.119] [INFO] system - Config file path:  /root/.ssmgr/default.yml
[2016-12-15 08:31:06.126] [INFO] system - Config:
 {
  "type": "s",
  "empty": false,
  "shadowsocks": {
    "address": "127.0.0.1:6001"
  },
  "manager": {
    "address": "127.0.0.1:6002",
    "password": "123456"
  },
  "plugins": {
    "telegram": {
      "use": false,
      "token": ""
    },
    "cli": {
      "use": false
    },
    "flowSaver": {
      "use": false
    },
    "email": {
      "use": false,
      "username": "username",
      "password": "password",
      "host": "smtp.your-email.com"
    },
    "freeAccount": {
      "use": false,
      "host": "yourhost",
      "port": 80,
      "managerPassword": "01020304",
      "shadowsocks": {
        "method": "aes-256-cfb",
        "startPort": 55000,
        "endPort": 65000,
        "flow": 100,
        "time": 60
      },
      "limit": {
        "user": {
          "day": 0,
          "week": 0,
          "month": 0
        },
        "global": {
          "day": 0,
          "week": 0,
          "month": 0
        }
      }
    }
  },
  "db": "/root/.ssmgr/db.sqlite"
}
^C

**Comment by gyteng** [comment]
你这日志不分行我看不清楚呀，请提供更详细的信息

**Comment by DearTanker** [comment]
感觉我改了defult.yml里面东西没生效的感觉。。指导教程可不可以更傻瓜化一点呢。。

**Comment by gyteng** [comment]
你这一步没有错，参考readme，你需要运行两个ssmgr程序配合才能用的。
