### ISSUE TITLE
为 --run 参数提供自定义加密方式的支持

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/shadowsocks-manager#86]
目前使用 run 参数来启动服务端的话只能使用 aes-256-cfb 加密方式。我觉得可以考虑添加选项自定义加密方式。

**Comment by gyteng** [comment]
后面会修复这个问题的。

目前run参数还有一些其他的问题，我在测试中，所以先没考虑那么多只用了aes-256-cfb。

**Comment by t123yh** [comment]
没想到回复得这么快。我可以在生产环境中使用 `--run` 吗？

**Comment by gyteng** [comment]
目前这个分支正在开发中，各个功能还不是非常稳定，日后api也有可能发生变动，所以我无法评估。

加`--run`来运行的话，我自己测试目前运行了两周，没有发生问题。

**Comment by gyteng** [comment]
@t123yh 最新的版本增加了 `-r libev:aes-256-cfb`这种用法
