### ISSUE TITLE
Shadowsocks always using dedicated GPU

### ISSUE THREAD

**Issue by cydia2020** [shadowsocks/shadowsocks-manager#87]
I use Surface Book on Windows Insider Preview flight 15002, Shadowsocks is always using the dedicated GPU so I cannot detach the clipboard correctly.

**Comment by gyteng** [comment]
You post the wrong place, maybe you should go the [this project](
https://github.com/shadowsocks/shadowsocks-windows) and add an issue.

2017-01-12 19:02 GMT+08:00 Cheng Chih <notifications@github.com>:

**Comment by cydia2020** [comment]
Whops, sorry for that
