### ISSUE TITLE
Keep getting ECONNREFUSED

### ISSUE THREAD

**Issue by fortuna** [shadowsocks/shadowsocks-manager#88]
ssmgr is not able to connect to my server. I'm getting the following error:

````
[2017-01-23 04:50:42.937] [ERROR] system - { Error: connect ECONNREFUSED 127.0.0.1:2001
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2001 }
````

I'm starting the server with:
````
ss-server --manager-address 127.0.0.1:2001 -m aes-256-cfb -A -p 2000 -k $PASSWORD
`````
The manager API with:
````
ss-manager --manager-address 127.0.0.1:2001 -p 2000
````
And the manager ui with:
````
ssmgr -t m -m 127.0.0.1:2001
````

Is this not the right commands to set up `ssmgr` with `shadowsocks-libev`?

**Comment by fortuna** [comment]
I get the same error if I start the server with:
````
ss-manager --manager-address 127.0.0.1:2001 --executable $(which ss-server) -vv -c config.json
````
And config:
`````
{
  "server":"0.0.0.0",
  "port_password": {
    "2000": "MyTestPass"
  },
  "method": "aes-256-cfb",
  "fast_open": true
}
`````

**Comment by gyteng** [comment]
Your commands are wrong,  
First, you have to start ss-manager:  
`ss-manager -m aes-256-cfb -u -k $PASSWORD --manager-address 127.0.0.1:2001`
Second, start ssmgr:  
`ssmgr -t s -s 127.0.0.1:2001 -m 0.0.0.0:6002`
Finally, you can use plugins to manage it.
