### ISSUE TITLE
Does newest master branch support unix socket?

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#89]
Does newest master branch support unix socket?

Hope can use like this:
```
ss-manager -m aes-256-cfb -u --manager-address /var/run/ss-manager.sock
ssmgr -t s -s /var/run/ss-manager.sock -m 0.0.0.0:6002
```

**Comment by gyteng** [comment]
Not yet, it will support unix socket later.  
Because I found it has some problems in windows, I am testing it now.

**Comment by andrew0213** [comment]
关于1.0版本,使用时有一个疑问.添加服务器页面,输入ip,管理端口,加密方式.  这个管理端口输入的是哪个端口？
是服务器上,ssserver运行时，配置的那个端口吗？可是那个配置需要使用localport和password才能访问呀...还是node配置文件的某个端口? 
确实没看明白,只能来这里求教下

**Comment by andrew0213** [comment]
@gyteng

**Comment by gyteng** [comment]
@andrew0213 是运行`ssserver --manager-address`参数后带的端口，
`--manager-address`参数详见shadowsocks的文档

**Comment by gyteng** [comment]
@cokebar I found that node dropped support for unix datagram sockets since version 0.6, so maybe it won't support unix socket, you have to use [ip:port] instead.
