### ISSUE TITLE
In CLI plugin, how to go back to upper menu?

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#90]
I've tried "ESC", "Backspace",etc., and it seems not work.

**Comment by gyteng** [comment]
You can't back to upper menu from the keys.
maybe I will add a 'back' selection to the menus later, thank you for report it.

**Comment by gyteng** [comment]
I just add a 'Back' selection in 'list server' menu. Please upgrade to version 0.3.72
