### ISSUE TITLE
#BUG program crash because of invisivble characters

### ISSUE THREAD

**Issue by cxy930123** [shadowsocks/shadowsocks-manager#93]
![screenshot_2017-02-03-14-00-22-487_com sonelli juicessh](https://cloud.githubusercontent.com/assets/7006257/22581260/abf4c06c-ea19-11e6-9915-54fc2b742b57.png)

**Comment by gyteng** [comment]
Please upgrade to version 0.3.73 and try again.

**Comment by cxy930123** [comment]
There comes another bug:
![screenshot_2017-02-03-14-54-28-612_com sonelli juicessh](https://cloud.githubusercontent.com/assets/7006257/22582270/c4448132-ea20-11e6-94c4-49489c162943.png)

**Comment by cxy930123** [comment]
get error again when I run `ssmgr -t m`:
![screenshot_2017-02-03-15-13-47-901_com sonelli juicessh](https://cloud.githubusercontent.com/assets/7006257/22582770/c4033a80-ea23-11e6-925a-05345291541e.png)
![screenshot_2017-02-03-15-13-55-417_com sonelli juicessh](https://cloud.githubusercontent.com/assets/7006257/22582773/cacbba0e-ea23-11e6-94fc-7ee42db927f9.png)
And when I sent command `flow` using Telegram, I got another error:
![screenshot_2017-02-03-15-14-41-966_com sonelli juicessh](https://cloud.githubusercontent.com/assets/7006257/22582812/1b61a276-ea24-11e6-82f7-11104dc5299d.png)

**Comment by gyteng** [comment]
You are using the old version sqlite file, so delete `/root/.ssmgr/db.sqlite` and it will be normal.
