### ISSUE TITLE
telegram 模式出错

### ISSUE THREAD

**Issue by ccc1924** [shadowsocks/shadowsocks-manager#94]
系统：centos7 （openvz）
node版本：6.9.1
出现如下情况
输入list命令出现
[2017-02-03 22:48:36.451] [ERROR] system - { Error: connect ECONNREFUSED 127.0.0.1:6002
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6002 }
[2017-02-03 22:48:36.457] [ERROR] telegram - failure
add命令没有反应
auth可以认证

**Comment by gyteng** [comment]
请详细说明你的启动过程，最好把配置文件也贴上来，不过记得把telegram的token隐去

2017-02-03 22:54 GMT+08:00 ccc1924 <notifications@github.com>:

**Comment by ccc1924** [comment]
shadowsocks:
  address: 127.0.0.1:6001
#  portRange: 50000-51000,55000,55002

manager:
  address: 127.0.0.1:6002
  password: '123456'

plugins:
  telegram:
    use: true
    token: 'xxxxxxxx'
  cli:
    use: false
  flowSaver:
    use: true
  email:
    use: false
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'
  freeAccount:
    use: false
    host: 'yourhost'
    port: 80
    managerPassword: '01020304'
    shadowsocks:
      method: aes-256-cfb
      startPort: 55000
      endPort: 65000
      flow: 100
      time: 60
    limit:
      user:
        day: 0
        week: 0
        month: 0
      global:
        day: 0
        week: 0
        month: 0

db: 'db.sqlite'

**Comment by gyteng** [comment]
你应该先启动一个shadowsocks进程，带--manager-address参数，然后再启动一个ssmgr进程，请参照项目首页[Readme](https://github.com/shadowsocks/shadowsocks-manager/blob/master/README.md)的步骤进行。

**Comment by ccc1924** [comment]
我先启动了shadowsocks-libev 命令是ss-manager -m aes-256-cfb -u --manager-address 1.0.0.1:6001
还是这个错

**Comment by gyteng** [comment]
完整的步骤是这样的：

首先启动ss-manager:
`ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001`

然后启动一个ssmgr:
`ssmgr -t s -s 127.0.0.1:6001`

最后再启动一个ssmgr，用上telegram插件，这一步你应该已经做了。

我估计你是少了第二步。

**Comment by ccc1924** [comment]
按你说的做了，提示如下
[2017-02-03 23:20:25.553] [ERROR] system - Unhandled Rejection at: Promise Promise { <rejected> 'failure' } reason: failure
输入list提示如下
[2017-02-03 23:23:33.543] [ERROR] telegram - failure

**Comment by gyteng** [comment]
输入auth提示什么？

**Comment by ccc1924** [comment]
telegram提示
this user is already a manager
后台提示
[2017-02-03 23:33:54.279] [INFO] telegram - Message x x x x x from x x x x x: auth

**Comment by gyteng** [comment]
删除文件`~/.ssmgr/db.sqlite`再试

**Comment by ccc1924** [comment]
问题依旧

**Comment by gyteng** [comment]
第二步的ssmgr启动后有何提示呢？即这条命令`ssmgr -t s -s 127.0.0.1:6001`

**Comment by ccc1924** [comment]
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-02-03 23:42:53.150] [INFO] system - System start.
[2017-02-03 23:42:53.366] [INFO] system - Config file path:  /root/.ssmgr/default.yml
[2017-02-03 23:42:53.375] [INFO] system - Config:
 {
  "type": "s",
  "empty": false,
  "shadowsocks": {
    "address": "127.0.0.1:6001"
  },
  "manager": {
    "address": "127.0.0.1:6002",
    "password": "123456"
  },
  "plugins": {
    "telegram": {
      "use": true,
      "token": ""
    },
    "cli": {
      "use": false
    },
    "flowSaver": {
      "use": false
    },
    "email": {
      "use": false,
      "username": "username",
      "password": "password",
      "host": "smtp.your-email.com"
    },
    "freeAccount": {
      "use": false,
      "host": "yourhost",
      "port": 80,
      "managerPassword": "01020304",
      "shadowsocks": {
        "method": "aes-256-cfb",
        "startPort": 55000,
        "endPort": 65000,
        "flow": 100,
        "time": 60
      },
      "limit": {
        "user": {
          "day": 0,
          "week": 0,
          "month": 0
        },
        "global": {
          "day": 0,
          "week": 0,
          "month": 0
        }
      }
    }
  },
  "db": "/root/.ssmgr/db.sqlite"
}

**Comment by ccc1924** [comment]
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-02-03 23:49:03.955] [INFO] system - System start.
[2017-02-03 23:49:04.158] [INFO] system - Config file path:  /root/.ssmgr/tg.yml
[2017-02-03 23:49:04.163] [INFO] system - Config:
 {
  "type": "m",
  "empty": false,
  "shadowsocks": {
    "address": "127.0.0.1:6001"
  },
  "manager": {
    "address": "127.0.0.1:6002",
    "password": "QzKRNJg0GZvi8rhu"
  },
  "plugins": {
    "telegram": {
      "use": true,
      "token": "314962571:AAGFA0G0vTYSivd1fZbp6j50fUUpPktdpgE"
    },
    "flowSaver": {
      "use": true
    }
  },
  "db": "/root/.ssmgr/db.sqlite"
这是第三部

**Comment by ccc1924** [comment]
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-02-03 23:49:03.955] [INFO] system - System start.
[2017-02-03 23:49:04.158] [INFO] system - Config file path:  /root/.ssmgr/tg.yml
[2017-02-03 23:49:04.163] [INFO] system - Config:
 {
  "type": "m",
  "empty": false,
  "shadowsocks": {
    "address": "127.0.0.1:6001"
  },
  "manager": {
    "address": "127.0.0.1:6002",
    "password": "QzKRNJg0GZvi8rhu"
  },
  "plugins": {
    "telegram": {
      "use": true,
      "token": "xxxx"
    },
    "flowSaver": {
      "use": true
    }
  },
  "db": "/root/.ssmgr/db.sqlite"

**Comment by gyteng** [comment]
我知道问题了，你第二步跟第三步的password不一样

"manager": {
"address": "127.0.0.1:6002",
"password": "QzKRNJg0GZvi8rhu"
},

"manager": {
"address": "127.0.0.1:6002",
"password": "123456"
},

两个配置文件里的password改成一样的

**Comment by ccc1924** [comment]
成功了，谢谢您
