### ISSUE TITLE
why has no directory named libs?

### ISSUE THREAD

**Issue by just-a-stone** [shadowsocks/shadowsocks-manager#96]
i have started the node server,but with error in web.

could not access to the directory of libs.  and i did't see the directory in your project.

**Comment by gyteng** [comment]
Please post the full error message.

**Comment by just-a-stone** [comment]
eg.
request   http://115.159.109.123:6003/libs/angular-material/angular-material.min.css
but got response as this 'GET angular-material.min.css  404 Not Found'.

**Comment by gyteng** [comment]
You have to install bower and run `bower install`

2017-02-08 9:27 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by just-a-stone** [comment]
谢谢   是这个原因


还有个问题，对shadowsocks操作的部分   好像都没调用
eg.
    shadowsocks.js
    sendMessageToShadowsocks   这个方法中的日志打印都看不到



lpf599@163.com
 
From: Gu
Date: 2017-02-08 09:39
To: shadowsocks/shadowsocks-manager
CC: just-a-stone; Author
Subject: Re: [shadowsocks/shadowsocks-manager] why has no directory named libs? (#96)
You have to install bower and run `bower install`

2017-02-08 9:27 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by gyteng** [comment]
有调用的，这个分支的我自己就在用，已经稳定运行几个月了，你具体哪个地方没日志？
目前我在开发新版本的。

2017-02-08 14:45 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by just-a-stone** [comment]
刚找到日志了，不熟悉node的代码结构。


现在问题是，
    我修改shadowsocks密码，看到发送udp消息发送前的日志。但是实际应该没生效
    
    我是先本机测试的，怀疑是否我服务器管理配置错误了。请问管理端口是啥？我安装的是shadowsocks-python，以ssserver **** 命令启动



lpf599@163.com
 
From: Gu
Date: 2017-02-08 14:50
To: shadowsocks/shadowsocks-manager
CC: just-a-stone; Author
Subject: Re: [shadowsocks/shadowsocks-manager] why has no directory named libs? (#96)
有调用的，这个分支的我自己就在用，已经稳定运行几个月了，你具体哪个地方没日志？
目前我在开发新版本的。

2017-02-08 14:45 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by gyteng** [comment]
ssserver --manager-address 127.0.0.1:6001
加--manager-address配置管理端口

2017-02-08 15:03 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by just-a-stone** [comment]
基本都解决了


现在就是怎么后台运行  node server，试了试，nohup不行的。

还有就是能提供下，生成验证码的http请求参数格式吗？
我打算直接写python去模拟请求，批量生成验证码。



lpf599@163.com
 
From: Gu
Date: 2017-02-08 15:07
To: shadowsocks/shadowsocks-manager
CC: just-a-stone; Author
Subject: Re: [shadowsocks/shadowsocks-manager] why has no directory named libs? (#96)
ssserver --manager-address 127.0.0.1:6001 
加--manager-address配置管理端口 

2017-02-08 15:03 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by gyteng** [comment]
后台运行可以用pm2，nohup也是可以的，再不行你用screen也没问题。
你指什么验证码？

2017-02-08 17:01 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by just-a-stone** [comment]
哦哦  刚打错了，是续费码。



lpf599@163.com
 
From: Gu
Date: 2017-02-08 17:02
To: shadowsocks/shadowsocks-manager
CC: just-a-stone; State change
Subject: Re: [shadowsocks/shadowsocks-manager] why has no directory named libs? (#96)
后台运行可以用pm2，nohup也是可以的，再不行你用screen也没问题。 
你指什么验证码？ 

2017-02-08 17:01 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by gyteng** [comment]
post `/api/admin/code`
需要传 flow 和 time 两个字段，
实际上续费码这个功能我还没怎么用过

2017-02-08 17:07 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by just-a-stone** [comment]
不用这个功能，怎么给别人加使用期  跟流量 ？？？



lpf599@163.com
 
From: Gu
Date: 2017-02-08 17:10
To: shadowsocks/shadowsocks-manager
CC: just-a-stone; State change
Subject: Re: [shadowsocks/shadowsocks-manager] why has no directory named libs? (#96)
post `/api/admin/code`
需要传 flow 和 time 两个字段，
实际上续费码这个功能我还没怎么用过

2017-02-08 17:07 GMT+08:00 just-a-stone <notifications@github.com>:

**Comment by gyteng** [comment]
不用的话，可以手工配置的。
新开发的版本支持支付宝付款后自动加时长和流量

**Comment by just-a-stone** [comment]
嗯嗯

我一开始就用你新版本的，感觉还不是很好用，好多没搞明白。
就先换到老版本了。没想到老版本文档更少=。=！

过段时间再考虑换回新版

再次感谢



lpf599@163.com
 
From: Gu
Date: 2017-02-08 17:21
To: shadowsocks/shadowsocks-manager
CC: just-a-stone; State change
Subject: Re: [shadowsocks/shadowsocks-manager] why has no directory named libs? (#96)
不用的话，可以手工配置的。
新开发的版本支持支付宝付款后自动加时长和流量
