### ISSUE TITLE
WebGUI in English version

### ISSUE THREAD

**Issue by Booli** [shadowsocks/shadowsocks-manager#98]
Hey,

I am following your progress with this app. I really like it! Will the WebGUI also be translated / available in English? 

Thanks!

**Comment by gyteng** [comment]
English version maybe later, after the Chinese version being stable.
I'm not a native english speaker, can you help me to translate  it?

2017-02-27 23:05 GMT+08:00 Pim Rutgers <notifications@github.com>:

**Comment by Booli** [comment]
Hey Gyteng,

Yes I will be willing to help translate. I can't speak Chinese, but my GF can and I can also adapt from google translate. 

Keep up the good work!

**Comment by TheAliAbbasi** [comment]
hey guys, any updates on this?

**Comment by hsnpersia** [comment]
Hi,
Some parts of English translation doesn't work and still display in Chinese. Any solutions for this?
